- migrations/versions/0297b_change_primary_service.py
- migrations/versions/0297c_change_primary_user.py
Migrations to change the primary service and service account
> Changed primary service and user to cdn context

- migrations/versions/0298c_replace_names_template_history.py
Addes the name changes in template history
> Make changes in template history

- Makefile
- README.md
Update README with installation instructions
> Update README with installation instructions

- app/dao/services_dao.py
- tests/app/dao/test_services_dao.py
- tests/app/service/test_rest.py
- tests/app/template/test_rest.py
> Remove default letters permission when a service is created

- app/config.py
Note: we can pull this out to the .env file later
> Modify csv bucket name

- app/config.py
- app/delivery/send_to_providers.py
- tests/app/delivery/test_send_to_providers.py
Updated logo url for email branding
> Get logo url

- migrations/versions/0300d_update_invite_email.py
> Small fix on invite email

- app/__init__.py
- app/commands.py
- app/config.py
- tests/app/v2/test_errors.py
> Upstream merges

- application.py
- gunicorn_config.py
For https://github.com/cds-snc/notification-api/issues/171
> Edited gunicorn config

- app/config.py
Small tweaks to prod environment that disable some GDS specific features such as performance platform
> Tweaks to prod configuration

- app/user/rest.py
> Update email support link

- migrations/versions/0301c_update_golive_template.py
Closes #222 
I'm not entirely sure how to test this to verify that the template updated properly..
> Update go live template migration

- app/dao/services_dao.py
- tests/app/service/test_archived_service.py
> Adds timestamp to archived service name

- app/user/rest.py
- tests/app/user/test_rest.py
Sends a notification if a Fido2 key is added or deleted
> Fido notification

- ci/cloudbuild-test.yaml
- scripts/run_tests.sh
The tests failed twice with the `-n32` flag so I reduced it to `n16`.
> Faster testing

- .github/workflows/master.yaml
> EKS beat deployment

- .github/workflows/master.yaml
Fix for github action using their own docker runtime
> Ga docker fix

- app/models.py
- tests/app/invite/test_invite_rest.py
- tests/app/user/test_rest.py
> Changed default 2fa to email :skull:

- app/config.py
- app/delivery/send_to_providers.py
- app/models.py
- app/v2/notifications/post_notifications.py
- migrations/versions/0305f_sending_domain_for_service.py
- tests/app/delivery/test_send_to_providers.py
> Sending domains

- migrations/versions/0305g_remove_letter_branding.py
Removes letter branding entries.
> Letter branding migration

- app/user/rest.py
Part of https://github.com/cds-snc/notification-api/issues/477
> Adds sender email to contact form

- app/schemas.py
> Fix schema for contact

- tests/app/celery/test_reporting_tasks.py
Closee https://github.com/cds-snc/notification-api/issues/484
> Fixes current time dependant tests

- app/delivery/send_to_providers.py
- tests/app/delivery/test_send_to_providers.py
Closes https://github.com/cds-snc/notification-api/issues/544
> Adds Luhn to SIN check

- app/smtp/aws.py
Fixes a bug in the DKIM records created for SMTP
> Correct DKIM

- app/clients/sms/aws_sns.py
> Hardcode SNS

- .github/workflows/docker.yaml
Changes to deploy to staging cluster
> Deploy staging

- .github/workflows/docker.yaml
Shortens docker image tag for easier referencing
> Reduce sha for easier deploy

- app/dao/fact_notification_status_dao.py
- app/utils.py
- pytest.ini
- tests/app/test_utils.py
> Modify TZ issues

- app/__init__.py
- app/api_key/rest.py
- app/dao/fact_notification_status_dao.py
- tests/app/api_key/test_rest.py
- tests/app/dao/test_fact_notification_status_dao.py
Added a new endpoint to get stats for an api key. Added very simplistic query to get total notifications sent per key.
> Added a new endpoint for api key stats

- app/config.py
Caused all sorts of grief on staging
> Fix CSV typo

- .github/workflows/docker.yaml
- application.py
- ci/Dockerfile
Making Git SHA available in container
> Inject git sha into container

- application.py
`application.py` never gets tested :(
> Actually fix sentry

- requirements-app.txt
- requirements.txt
Based on a bug and this fix in UK https://github.com/alphagov/notifications-api/commit/5a3d2e3162d6d81594b7777b7bce59b710b7ae9b#diff-28ad48f17e559daf5f2116b1d6a7f620
> Removes custom sqs bot client

- requirements-app.txt
- requirements.txt
> Utils bump for branding migration

- app/config.py
- app/utils.py
This is so we can test the feature with our own service in prod
> Added a 3rd bulk send service for testing purposes

- app/user/rest.py
cc @anikbrazeau to verify this is the correct link
Part of #943
> point feedback_url to correct contact us url

- app/celery/research_mode_tasks.py
- tests/app/celery/test_research_mode_tasks.py
This reverts commit b599479be94cd80fa2449cb22f836df1c23f6182.
> Revert "try disabling ses callback in test sends (#1028)"

- app/notifications/validators.py
- tests/app/notifications/test_validators.py
Lets see if this fixes the issue
> Put in an aggressive rate limit for test keys

- requirements.txt
> Sprintly dependency bump

- app/service/rest.py
- tests/app/service/test_service_whitelist.py
re https://github.com/cds-snc/notification-api/issues/962
requires corresponding changes to admin: https://github.com/cds-snc/notification-admin/pull/705
> change whitelist route to safelist

- app/user/rest.py
- app/utils.py
- migrations/versions/0310_account_change_type.py
- tests/app/test_utils.py
- tests/app/user/test_rest.py
Fixes https://github.com/cds-snc/notification-api/issues/1016
Related previous PR https://github.com/cds-snc/notification-api/pull/459
Local demo:
> Make account changes email bilingual

- app/smtp/aws.py
Follow up of https://github.com/cds-snc/notification-api/issues/1117
> SMTP relay: remove DMARC's ruf setting

- .github/workflows/test.yaml
Similar to https://github.com/cds-snc/notification-admin/pull/787
> Cache pip on GitHub Actions

- app/dao/inbound_numbers_dao.py
- tests/app/dao/test_inbound_numbers_dao.py
Prevent a potential SQL injection from the platform admin UI
> Use Alembic to create an InboundNumber

- app/dao/fact_notification_status_dao.py
- app/platform_stats/rest.py
- tests/app/dao/test_fact_notification_status_dao.py
- tests/app/platform_stats/test_rest.py
This new endpoint is needed to build the trial accounts report
Trello card: https://trello.com/c/rS9V7QGu/108-trial-account-report
> Notification stats for trial services

- requirements-app.txt
- requirements.txt
Release https://github.com/cds-snc/notification-utils/pull/69
> Bump utils to 43.2.0

- gunicorn_config.py
Follow up of https://github.com/cds-snc/notification-api/pull/1193
Same PR as https://github.com/cds-snc/notification-admin/pull/856
> Remove Gunicorn kill switch for keepalive

- .github/workflows/docker.yaml
- ci/Dockerfile
Exact same changes than in https://github.com/cds-snc/notification-admin/pull/875
> Speed up docker build

- app/service/rest.py
- tests/app/service/test_rest.py
fix, previous name exists query was case sensitive, changed to insensitive
> fix case insensitive name exists query

- app/dao/date_util.py
- requirements-app.txt
- requirements.txt
- tests/app/public_contracts/__init__.py
Improved platform compatibility by offering a set of `strftime` format codes for both POSIX-like environment and Windows platforms.
The existing unit-tests should do their job and cover regressions. 
This is a suggested checklist of questions reviewers might ask during their review | Voici une suggestion de liste de vérification comprenant des questions que les réviseurs pourraient poser pendant leur examen :
> fix: Improved platform compatibility (windows)

- requirements-app.txt
- requirements.txt
Updating project dependencies in the `requirements-app.txt` file by cross-referencing the pypi.org site.
Trello: https://trello.com/c/YKTbGxUK/237-bump-python-dev-dependencies
> Update project dependencies

- .github/workflows/docker.yaml
Same PR than https://github.com/cds-snc/notification-admin/pull/918
> Update AWS CLI when building containers

- app/config.py
- app/notifications/rest.py
- app/notifications/validators.py
- app/utils.py
- docker-compose.yml
- pytest.ini
- tests/app/notifications/rest/test_send_notification.py
- tests/app/notifications/test_validators.py
- tests/app/test_utils.py
- tests/app/v2/notifications/test_post_notifications.py
[Trello Link](https://trello.com/c/bEMNSBCA)
fix: updated docker-compose and pytest.ini file so tests would run using docker-compose
fix: replaced documentation links as well as added a #FIXME when we can get the proper translations (as discussed with Anik)
refactor: updated test cases to account for the new link
1. From project root folder (on my system) modify scripts/run_tests.sh to only run single execution by modifying -n4 -> -n1
2. Launch docker-compose `docker-compose up --build`
3. Validate that the tests run to completion from the `test` container and that there are no more database connection errors
1. Get a python script that will exercise the sms and email sending via api (Thanks Antoine)
2. Setup a service, set it live (you have to be a platform admin), create a "Normal" api …
> fix: removed gov.uk from error message

- app/clients/freshdesk.py
- app/user/contact_request.py
- tests/app/clients/test_freshdesk.py
- tests/app/clients/test_zendesk_sell.py
- tests/app/user/test_contact_request.py
[Trello](https://trello.com/c/j8X6IDPs)
fix: freskdesk subject needs to be friendly_support_type
Ran through the unit tests `test_zendesk_sell.py` and `test_freshdesk.py`
Went through the contact request form for booking a demo
This is a suggested checklist of questions reviewers might ask during their review | Voici une suggestion de liste de vérification comprenant des questions que les réviseurs pourraient poser pendant leur examen :
> fix: freskdesk subject needs to be friendly_support_type

- app/clients/zendesk_sell.py
- tests/app/clients/test_zendesk_sell.py
[Trello](https://trello.com/c/Ol1UmIUK)
fix: adding hard coded source_id to a lead entry
Rationale: new leads are being triaged based upon the source, in this case "Demo request form". To set this field, it was discovered that it's a hard coded value within zendesk and doesn't relate to any human readable value.
1) run `test_rest.py`, `test_freshdesk.py`, `test_zendesk_sell.py`, `test_contact_request.py` validate that they run properly
2) Test that the new/updated leads entry now has 'Source' defined as 'Demo request form'
> fix: adding hard coded source_id to a lead entry

- app/notifications/validators.py
- app/service/rest.py
- requirements-app.txt
- requirements.txt
- tests/app/service/test_rest.py
Bump notification-utils to 43.5.0 and refactor accordinly.
Follow up of #1268
> Bump utils to 43.5.0

- app/celery/provider_tasks.py
- tests/app/celery/test_provider_tasks.py
Discovered while working on https://github.com/cds-snc/notification-api/pull/1276 https://github.com/cds-snc/notification-api/pull/1277
Callbacks are created at the delivery receipt stage for emails and SMS, as we receive an answer from AWS. This works fine for delivered notifications or when they bounce.
There is another case: technical failures. Those mean that the provider didn't send the notification. Therefore, we will never get a delivery receipt. In these cases, we still need to send a callback sharing that this notification was not sent, because of a technical failure.
Trello: https://trello.com/c/FBVmiCFe/464-send-callbacks-for-technical-failures
> feat: queue callbacks for technical failures

- requirements-app.txt
- requirements.txt
Releasing https://github.com/cds-snc/notification-utils/pull/80
> Bump utils to 43.7.0

- app/clients/zendesk_sell.py
- tests/app/clients/test_zendesk_sell.py
[Trello](https://trello.com/c/AH8gsNqx/465-update-deal-in-zensales-with-go-live-request-notes)
The problem was that the deal upsert was too specific, it should just key off of the `notify_service_id`. 
- Tested creating a service, going through the 4 steps to go live request, and then setting the request to live: validated that only one deal is created and changed
- ran `test_zendesk_sell.py` locally
que ça devrait être divisé en de plus petites demandes de tirage …
> fix: deal upsert was too specific and used the contact id

- ci/Dockerfile
We need Rust version > 1.41 at build time per [cryptography module installation notes](https://cryptography.io/en/latest/installation/#rust). Alpine 3.13 would have [Rust 1.47 installed per the Alpine packages search engine](https://pkgs.alpinelinux.org/packages?name=rust&branch=v3.13&repo=community).
By explicitly referring to 3.13 in the Alpine docker image, we could bypass the Alpine version which could have been 3.12 in the previous build runs.
Also, defining Rust and cargo in the APK dependencies will guarantee we have the Rust packages installed for the appropriate version of Alpine 3.13.
Run local docker for CI locally. Then merge this PR.
review | Voici une suggestion de liste de vérification comprenant …
> Explicitly define alpine 3.13 in docker file

- app/config.py
> fix: set NOTIFY_ENVIRONMENT in staging

- app/v2/notifications/post_notifications.py
- tests/app/v2/notifications/test_post_notifications.py
Follow up of https://github.com/cds-snc/notification-api/pull/1305
The `sender_id` was not properly set. I was using previously a method `get_reply_to_text` which was used by another controller method and assumed it was returning a UUID. I was wrong.
I began to write tests for sender IDs in `test_post_bulk_creates_job_and_dispatches_celery_task`, using a Pytest param `use_sender_id`, but actually never used this parameter in my test case 😭 
This PR fixes how `sender_id` is set on `Job`s and adds a bunch of tests proving that it works as intended.
> Fix sender ID for bulk API

- .github/workflows/docker.yaml
Instead of using a personal token. Github now provides the `GITHUB_TOKEN` to use the github bot. So I switched the workflow to use the this for the PR bot. Of course the only way to test this is to do a PR...
Created github app called Notify PR Bot. Installed it on our repos and modified the workflow to authenticate with it.
Lets see if this PR works 
N/A
Does it work ?
requests ») afin de …
> fix: have PR bot use github token

- app/celery/research_mode_tasks.py
- tests/app/celery/test_research_mode_tasks.py
Following discussion with Bryan last week, use dedicated phone numbers instead of last phone digit to simulate receipts success, temporary and permanent failures. This initiated [from changes to fix research mode](https://trello.com/c/FTzY1HLJ/563-rework-fake-sms-callbacks-for-notifications-sent-using-test-keys).
Use a TEST API KEY with the referred phone numbers in this PR to simulate different responses.
que ça devrait être divisé en de plus petites demandes de …
> Change phone numbers to be used with TEST API KEYS

- .github/workflows/docker.yaml
- .github/workflows/test.yaml
Add CI failure notification (similar to https://github.com/cds-snc/notification-admin/pull/1085)
* Code basically copied from https://github.com/cds-snc/notification-admin/pull/1085.
* tested by forcing a failure
requests ») afin de réduire le risque lié aux modifications? …
> Add ci failure notification

- app/__init__.py
- app/authentication/auth.py
- app/authentication/bearer_auth.py
- app/celery/celery.py
- app/celery/tasks.py
- app/clients/__init__.py
- app/config.py
- app/dbsetup.py
- app/errors.py
- app/models.py
- app/schemas.py
- application.py
- migrations/versions/0133_set_services_sms_prefix.py
- mypy.ini
- requirements_for_test.txt
- scripts/run_tests.sh
- tests/app/clients/test_freshdesk.py
- tests/app/clients/test_zendesk_sell.py
- tests/app/service/test_statistics.py
- tests/app/test_utils.py
- tests/app/user/test_contact_request.py
- tests/app/v2/notifications/test_notification_schemas.py
This PR adds mypy to the CI script in notification-api, similar to what we have in notification-admin: https://github.com/cds-snc/notification-admin/blob/master/scripts/run_tests.sh#L37
~I will convert this from a draft once I fix (or ignore!) the remaining errors mypy is throwing.~ Done! 
Ready for review.
> Adding mypy to CI

- app/celery/tasks.py
- tests/app/celery/test_tasks.py
Fixes the bug introduced in #1323 where an `api_key_id` of `None` would cause celery errors.
Modified a test to check this.
requests ») afin de réduire le risque lié aux modifications?
setup, etc.) | Faudra-t-il mettre à jour la …
> treat api_key_id of None appropriately

- app/celery/tasks.py
- app/dao/jobs_dao.py
- app/models.py
Adding some type definitions to the `Job` model and some of the code that uses it.
> Adding type definitions to some of the jobs code

- tests-perf/locust/README.md
- tests/app/v2/notifications/test_post_notifications.py
Just adding documentation on how to run the performance tests in the EC2s on AWS.
requests ») afin de réduire le risque lié aux modifications?
changement …
> chore: documentation for perfomance testing using ec2s

- migrations/versions/0324_fix_template_redacted.py
https://trello.com/c/BPtmAwwY/635-bug-cannot-save-template-when-updating-gc-notifys-own-limit-related-templates?menu=filter&filter=member:stephenastels
The `template_redacted` table was missing rows for a few recently added templates. This caused validate of those templates to fail (which led to a 500 error when trying to update the templates). This migration adds the rows.
- Look at your local `template_redacted`table sorted by `updated_at`.
- run `flask db upgrade`
- the table should have three rows added.
- running admin and api locally you can now edit those templates
- run `flask db downgrade` to verify that the downgrade removes these lines from the table.
review | Voici une suggestion de liste de …
> Migration to add daily limit templates to template_redacted table

- app/v2/notifications/post_notifications.py
I found a bug in my code where I included an additional argument for save_email and save_sms. Since these functions are mocked in the unit tests. We could not catch it there
---
> Description en 1 à 3 phrases de la modification proposée, avec un lien vers le
> problème (« issue ») GitHub ou la fiche Trello, le cas échéant.
---
> jouer au détective. …
> fix: additional arguments that were not needed for save_email and save_sms

- app/clients/freshdesk.py
- app/schemas.py
- app/user/contact_request.py
- app/user/rest.py
- tests/app/clients/test_freshdesk.py
- tests/app/user/test_rest.py
https://trello.com/c/IvntgBDS/640-branding-images-should-go-to-fresh-desk-inbox
We tried to use our support email address to do this, but it didn't work (https://github.com/cds-snc/notification-manifests/pull/632). Here we use the FreshDesk api to create the ticket, as we do for other customer issues (demo requests, go live requests, support)
Old email:
New ticket:
- Run the admin and api manually with Freshdesk creds in api's `.env`. 
- Make a branding request via a service's settings page. 
- The request should appear in the` #notification-ops` channel.
We can improve the code and ticket by making admin / api PRs that
- sync up the property names
- add more to the ticket (service_url for example)
review | Voici …
> Use Freshdesk api for branding request

- .github/workflows/build_and_push.yml
This is to fix the failing workflow: https://github.com/cds-snc/notification-api/runs/3303137409
> Added an argument so docker can find Dockerfile.lambda

- app/config.py
Added comments on the declaration of queues, to describe their purpose and some context.
(This PR is also a test to try out the [vscode web version now hosted by github](https://github.dev/cds-snc/notification-api/), it works pretty good).
> Added comments on a few queues definition.

- app/schemas.py
- pytest.ini
- tests/app/template/test_rest_history.py
When I looked at the admin it just sets the data returned by the route in the API. `/<sevice-id>/templates/<template-id>/version/<version-number>` If a version number is provided the TemplateHistory schema is used. So all that needs to be modified is the marshmallow schema to include the field 
1. Run unit tests
2. Test that specific template versions now have process_type
requests ») afin de …
> Add process type to template versions

- app/celery/provider_tasks.py
- app/delivery/send_to_providers.py
- app/exceptions.py
- tests/app/conftest.py
- tests/app/delivery/test_send_to_providers.py
Reverting PR #1344 which seems to cause issues with the notifications that has attachments. 
Locally tested so far and about to be tested in staging environment.
* Send notifications to the attachment to the API.
None.
> Revert "Feat/validate attachments link urls (#1344)"

- app/celery/tasks.py
> 1-3 sentence description of the changed you're proposing, including a link to
> a GitHub Issue # or Trello card if applicable.
---
> Description en 1 à 3 phrases de la modification proposée, avec un lien vers le
> problème (« issue ») GitHub ou la fiche Trello, le cas échéant.
---
> jouer au détective. Veuillez aussi inclure toutes les étapes de …
> quick fix for when sender id is provided

- tests_smoke/smoke/common.py
- tests_smoke/smoke_test.py
- fix a bug where the jwt could timeout
- print out API_HOST_NAME, SERVICE_ID, EMAIL_TEMPLATE_ID, SMS_TEMPLATE_ID, EMAIL_TO, and SMS_TO to help with debugging
Run the smoke tests!
requests ») afin de réduire le risque lié aux modifications?
risque d’utiliser des dépendances …
> smoke test: fix token issue and improve output

- requirements-app.txt
- requirements.txt
Update notification utils to 46.3.0
> Update notification utils

- app/config.py
We want to add a feature flag in order to rollout batch insertion.
Zenhub Issue: https://github.com/cds-snc/notification-planning/issues/142
> Add feature flag for batch insertion

- .github/workflows/lambda_production.yml
- .github/workflows/lambda_staging.yml
lambda's have to be deployed from a private ECR inside the same account. Currently we push the image to the ECR in staging. In this PR we also push to the ECR in prod. Note that the ECR has already been created.
~First need to create the user to use for the push: https://github.com/cds-snc/notification-terraform/pull/306~
Now just need to bump the infrastructure version of prod to create the ecr_user in the prod account
préoccupations …
> push lambda image to prod ECR

- .github/workflows/lambda_production.yml
- .github/workflows/lambda_staging.yml
We were too clever in #1385. In particular, the action was only pushing new docker images if the app actually changed. However, for k8s we push (and deploy to staging) every new gitsha, even if the code in `app/` hasn't changed, so we could have the api lambda reporting a different gitsha than the k8s api.
This PR removes the clever filtering and pushes on every merge to master.
We also rename some of the ECR related secrets to better indicate exactly what they are.
None.
modification …
> rename secrets and push all master changes

- .github/workflows/lambda_production.yml
- .github/workflows/lambda_staging.yml
Sigh.
```
The workflow is not valid. .github/workflows/lambda_staging.yml (Line: 19, Col: 16): Unexpected value 'api-lambda'
```
None.
> fix strings in merge workflows

- .github/workflows/lambda_production.yml
- .github/workflows/lambda_staging.yml
In #1391 I thought you could just give the matrix argument a string, but it really needs an array 😞 
This time I commented out the image push / deploy code and got rid of the push filter so that it ran, built and tagged the images, and logged into AWS:
staging: https://github.com/cds-snc/notification-api/runs/4105830181?check_suite_focus=true
prod: https://github.com/cds-snc/notification-api/runs/4105830116?check_suite_focus=true
(then I restored the push filter and image push / deploy)
None.
fonctionnalité …
> Fix actions (again)

- bin/execute_and_publish_performance_test.sh
- tests-perf/locust/locust-notifications.py
- tests-perf/ops/Dockerfile
Related to https://github.com/cds-snc/notification-api/pull/1395
This is makes an update from LOAD_TEST to PERF_TEST.
> COSMETIC: Change load test prefix

- .github/workflows/lambda_production.yml
- .github/workflows/lambda_staging.yml
[We currently get these errors](https://github.com/cds-snc/notification-api/runs/4168080065?check_suite_focus=true) on the workflow for building staging lambda api:
```
docker build \
--build-arg git_sha=$GITHUB_SHA \
-t $REGISTRY/api-lambda:$GITHUB_SHA \
-f ci/Dockerfile.lambda
shell: /usr/bin/bash -e {0}
env:
GITHUB_SHA: 7e65cd1958cc1133bd768dd4ec30ef47156cfcb6
REGISTRY: ***.dkr.ecr.ca-central-1.amazonaws.com/notify
"docker build" requires exactly 1 argument.
See 'docker build --help'.
```
[Previous changes](https://github.com/cds-snc/notification-api/commit/992d5e1eac971ffc09cd46027b06b84461058ca2#diff-33130583518bf7232ba0d8b0fd28ccb5dcb48a35eb451eca6e17de8464a76d98) on these files deleted too much, including the `.` to [indicate the build …
> Fixed Docker file missing current param path to build image from

- .github/workflows/lambda_production.yml
- .github/workflows/lambda_staging.yml
by default the github sha is the full sha, we only use the first 7 characters for all our other image tags. 
These changes are analogous to how the action for the k8s api image works:
https://github.com/cds-snc/notification-api/blob/master/.github/workflows/docker.yaml#L40-L51
lambda:
images in k8s:
Verified by running action on every push but just building and tagging the image:
https://github.com/cds-snc/notification-api/runs/4213767476?check_suite_focus=true#step:3:619
None. …
> Just use start of gitsha for the lambda image tags

- tests-perf/locust/locust-notifications.py
- tests-perf/ops/Dockerfile
* Removed settings of environment variables within the perf-test Dockerfile setup. These should be unnecessary now as we set these env vars through Terraform passing it to the ECS task definition.
* Removed default Notify resources' IDs from Locust code. These can be configured separately on a locust configuration file for the user and we will minimize exposing test IDs not normally accessible to the public (i.e. it's not bad but not ideal and we can configure this in some other way).
* Run the docker image by passing by the env vars through the command line parameters, as this is what the ECS task will do.
This should not break anything as the perf test is already broken as we revoked past referred API key in the header.
This is a suggested checklist of questions reviewers might ask …
> Removed env vars from perf-test dockerfile.

- tests-perf/locust/locust-notifications.py
- tests-perf/locust/locust.conf
Gentler spawn rate per second (which should bring 1,200 new users per minute instead of 12,000 up to max users of 3,000). Also reworked the task weight to bring something more representative of current usage.
Run the tests!
This should not affect Notify production but only the performance tests in staging environment.
setup, …
> Gentler perf tests on the system

- .github/workflows/build_and_push_performance_test.yml
Removed perf-test lambda deployment
The CI build should now pass.
> Removed perf-test lambda deployment

- tests-perf/locust/README.md
Updated documentation for running the performance in AWS.
Read it and get through the steps please. =)
> Updated documentation for running the performance in AWS

- heartbeat/Dockerfile
- heartbeat/execute_heartbeat.sh
- heartbeat/heartbeat.py
Change the Docker image so that the lambda invocation is similar to what is in AWS docs
.
> Change dockerfile

- app/notifications/validators.py
- tests/app/notifications/rest/test_send_notification.py
- tests/app/notifications/test_validators.py
- tests/app/v2/notifications/test_post_notifications.py
Added the template ID on error validation message so we can better debug which template was sought after by API users when a bad request occurs.
* Unit tests pass!
> Added template ID on deleted template validation error msg

- application.py
- gunicorn_config.py
[Zenhub card](https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/238)
Following on with our move to AWS Lambda, we require the ability to track the performance of API via New Relic. With the way things are AWS Lambda does not invoke gunicorn, so New Relic isn't getting initialised.
This PR simply moves the New Relic initialization code to application handler function which is invoked by the AWS Lambda.
modification de la …
> Experimental: New Relic initialisation to app handler

- README.md
- app/notifications/process_notifications.py
Log the queue that notifications will use before sending to the SQS queue.
Check at the log output!
Make sure the notifications in staging are logging their used queue in CloudWatch.
> Increased log around notifications to get used queue

- app/celery/tasks.py
- app/config.py
- app/notifications/process_notifications.py
- tests/app/celery/test_tasks.py
- tests/app/notifications/test_process_notification.py
In order to change the bulk API we need to change the underlying functionality of the code. The following is the way this occurs:
1. This is the bulk API: https://github.com/cds-snc/notification-api/blob/fe4ea28e2de29e981a96b5b391fd47a2147439ed/app/v2/notifications/post_notifications.py#L121
2.  It calls create_bulk_job https://github.com/cds-snc/notification-api/blob/fe4ea28e2de29e981a96b5b391fd47a2147439ed/app/v2/notifications/post_notifications.py#L160
3. Which calls `process_job` https://github.com/cds-snc/notification-api/blob/fe4ea28e2de29e981a96b5b391fd47a2147439ed/app/v2/notifications/post_notifications.py#L602 
Changes made in the PR:
1. Change process_job . This function will now use a feature flag to switch to the bulk insert functionality in the DB.
2. Add `process_rows` - …
> Add + test for persist_notificationss

- app/celery/tasks.py
- app/config.py
Fixes from previous Pr comments. 
This is the PR I am making fixes from :
https://github.com/cds-snc/notification-api/pull/1426
Dependency: https://github.com/cds-snc/notification-manifests/pull/850
> Fixes from previous PR for Batch Saving

- app/config.py
The env variable is currently a string, we need to change it to a int.
> Cast the env variable to int for chunk size

- app/notifications/process_notifications.py
- app/v2/notifications/post_notifications.py
- tests/app/notifications/test_process_notification.py
- tests/app/v2/notifications/test_post_notifications.py
Refactor the  `/v2/notifications/email` and `/v2/notifications/sms` endpoints a bit more to put `queue_names` in the notification object, and then use it in the `db_save_and_send_notification()` function to put the notification in the appropriate queue.
This will allow us to replace `db_save_and_send_notification()` with something that puts the notification into Redis, then on the other end we will have something that pulls out the notifications in batches and then does a batch version of `db_save_and_send_notification()`.
tested `/v2/notifications/email` and `/v2/notifications/sms` endpoints locally
None. Note that the code is still doing the same steps as before, just in different functions.
review | Voici une …
> Use queue name

- app/celery/scheduled_tasks.py
- app/celery/tasks.py
- app/config.py
- tests/app/celery/test_scheduled_tasks.py
Heartbeat code: This function is called ever 10 seconds to check the Indox Queues for SMS and Emails. It then moves the encrypted notifications into the inflight list (please read the ADR).
- Unit tested
> Add the heartbeat code for the queues - email/sms

- .gitignore
- app/celery/scheduled_tasks.py
- app/celery/tasks.py
- test_results_serial.xml
- tests/app/celery/test_scheduled_tasks.py
- tests/app/celery/test_tasks.py
Fix the batch saving code 🎉 
Need
```
FF_REDIS_BATCH_SAVING=1
REDIS_ENABLED=1
```
set.
None.
> fix the things

- app/celery/tasks.py
- tests/app/celery/test_tasks.py
The notification id sent back in the POST was being overwritten with a new id. 😞 
Also tested that the id will get passed through correctly if it's there.
None.
> don't overwrite notification id

- app/queue.py
- tests/app/test_queue.py
Have the suffix added to the name of the inflight list.
> Add suffix to inflight list

- app/notifications/validators.py
- tests/app/notifications/test_validators.py
Increased cache TTL for daily rate limit of services.
Regression tests.
Nothing special!
> Increase TTL cache for daily service limit

- .github/workflows/docker.yaml
- .github/workflows/lambda_production.yml
- .github/workflows/lambda_staging.yml
- .github/workflows/performance.yml
- .github/workflows/secret.yaml
- .github/workflows/test.yaml
Going forward, we are adopting main as our default branch,
This commit updates the workflows YAML files, replacing master with  main branch
> Update: Switch from master to main branch

- app/celery/scheduled_tasks.py
- app/celery/tasks.py
- app/v2/notifications/post_notifications.py
The main change from this sync [is the following one](https://github.com/cds-snc/notification-api/pull/1471):
> Added more logs and refined other around batch saving. Namely, I added a `Batch saving:` prefix on all related logs to make it easily searchable.
Regression tests should cover it all; no behavior changed.
None.
setup, …
> Sync master with main

- .devcontainer/scripts/notify-dev-entrypoint.sh
- app/aws/metrics.py
- app/config.py
- app/queue.py
- requirements-app.txt
- requirements.txt
- tests/app/aws/test_metrics.py
- tests/app/test_queue.py
Custom Cloudwatch logs
Added cloud watch metrics for different part of the custom queue implementation.
Note: needs to be tested in staging
> feat: scaffold custom metrics

- app/aws/metrics.py
- tests/app/aws/test_metrics.py
Change metric namespace to be `"NotificationCanadaCa"` vs `BatchSaving`
> Change the metric namespace to be the same as the Notification namespace

- app/celery/scheduled_tasks.py
- tests/app/celery/test_scheduled_tasks.py
Rename heartbeat definitions for consistency
> chore: rename heartbeats definitions for consistency

- .devcontainer/devcontainer.json
- .devcontainer/scripts/notify-dev-entrypoint.sh
Add aliases to make it simpler to manage the Staging and Production cluster kubeconfig file.
* cds-snc/notification-manifests#937
> feat: alias to set k8s staging/prod kubeconfig

- app/aws/metrics_logger.py
Disable metrics to triage performance issues.
> chore: disable metrics

- app/clients/zendesk.py
Zendesk ticket creation is currently failing in production but working in staging. Having the http response available will assist in troubleshooting the issue.
> chore: more detailed zendesk error message

- .devcontainer/devcontainer.json
- README.md
- tests-perf/locust/README.md
Update readme for performance tests, add extensions in dev container.
> Add readme for performance

- app/celery/tasks.py
- app/config.py
- scripts/run_celery_beat.ps1
* Brought down the schedule for beat **in-flight-to-inbox** task from 300s to 60s.
* Added a powershell script to run celery beat.
* Unnecessary `None` handling
* Reworking log for job start from a debug to an info level.
None.
changement (fichier …
> Miscellaneous changes

- app/clients/zendesk.py
This print statement got lost, this PR will send it home.
> chore: remove stray print

- app/config.py
- requirements-app.txt
- requirements.txt
- tests/app/test_config.py
Use [environs](https://pypi.org/project/environs/) to set boolean and integer config values.  
This was tested locally with the `Staging` and `Production` environment variables and behaved as expected with no difference found between using `dotenv` and `environs` to set the Config values.
* cds-snc/notification-planning#421
1. Capture the API's logged configuration pre-change (e.g. using `main` branch).
2. Switch to `feat/environs`and capture the API's logged configuration.
3. Compare the two logged configurations.  They should match.
Compare the API's logged configuration pre and post release to make sure they match.
que les réviseurs …
> feat: add environs for bool and int config

- .gitignore
- bin/entry.sh
- bin/sync_lambda_envs.sh
- ci/Dockerfile.lambda
Due to the 4kB lambda environment variable limit being reached. The lambda API will now have to retrieve environments from parameter store.
> feat: retrieve lambda .env from parameter store

- app/models.py
- tests/app/user/test_rest.py
> Add password_expired to user model

- app/dao/users_dao.py
- tests/app/dao/test_users_dao.py
set `user.password_expired` to `False` after a user updates their password.
- expire a user's password
- go through the expired password flow to reset it
-  ensure that you can now log in without getting to the expired password flow
- 
None.
changement …
> clear password_expired after updating password

- migrations/versions/0419_add_forced_pass_template.py
Add template for a Forced Reset Password email.
> Migration: add forced reset template

- app/config.py
Add FF_PRIORITY_LANES feature flag so everyone can use it in their PRs
This is the manifest change: https://github.com/cds-snc/notification-manifests/pull/1063
> Added feature flag

- app/queue.py
- tests/app/test_queue.py
Adding code to add new inboxes/ as well as keep old inboxes.
This was done in the queue implementation.
> Task: New Inboxes

- .github/workflows/docker.yaml
Bump up kubectl version to 1.23.6, latest known stable version and that is not affected [by this issue](https://github.com/aws/aws-cli/issues/6920).
Let the workflow run!
None.
> Upgraded kubectl version to latest known stable 1.23.6

- app/notifications/validators.py
- newrelic.ini
Our current goal is to provide the error_collector.ignore_errors configuration to ignore certain type of errors such as validation or bad request. The error types we can safely ignore for now are:
* app.v2.errors:BadRequestError
* jsonschema.exceptions:ValidationError
---
> jouer au détective. Veuillez aussi inclure toutes les étapes de configuration
> …
> Added new relic config to ignore bad request and validation errors

- app/__init__.py
- app/celery/scheduled_tasks.py
- app/celery/tasks.py
- app/v2/notifications/post_notifications.py
- tests/app/v2/notifications/test_post_notifications.py
Change the API to send the notification to the correct INBOX based on the notification type.
Relates to cds-snc/notification-planning#629
---
> Description en 1 à 3 phrases de la modification proposée, avec un lien vers le
> problème (« issue ») GitHub ou la fiche Trello, le cas échéant.
---
> jouer au détective. Veuillez aussi inclure toutes les …
> Priority lanes 629

- tests/app/celery/test_scheduled_tasks.py
Adding a test to ensure inflight queues get expired along with the existing ones.
---
> Description en 1 à 3 phrases de la modification proposée, avec un lien vers le
> problème (« issue ») GitHub ou la fiche Trello, le cas échéant.
None.
> Necessary steps to perform before and after the deployment of these changes.
> For example, emptying the cache on a feature that changes the cache data
> structure in Redis could be mentioned.
---
> Étapes nécessaires à exécuter avant et après le déploiement des changements
> introduits par cette proposition. Par exemple, vider la cache suite à des
> changements modifiant une structure de données de la cache pourrait être
> mentionné.
review | Voici une suggestion de liste de …
> test: ensure new redis inflight queues get expired

- app/celery/scheduled_tasks.py
- app/config.py
- tests/app/celery/test_scheduled_tasks.py
- tests/app/v2/notifications/test_post_notifications.py
Added the new beat workers for the 6 new queues.
> Adding code for scheduling the new queues

- app/celery/tasks.py
- tests/app/celery/test_tasks.py
Add the `process_type` to the template-not-a-tempate that gets passed to process_rows and process_row
Also added some tests with the FF on and off for `process_job` and `process_incomplete_job` which are the only things that eventually use `choose_database_queue()`
See if it still breaks staging?
None.
> Necessary steps to perform before and after the deployment of these changes.
> For example, emptying the cache on a feature that changes the cache data
> structure in Redis could be mentioned.
---
> Étapes nécessaires à exécuter avant et après le déploiement des changements
> introduits par cette proposition. Par exemple, vider la cache suite à des
> changements modifiant une structure de données de la cache pourrait être
> mentionné.
This is a suggested checklist of questions reviewers …
> add missing property to template

- app/celery/tasks.py
- tests/app/celery/test_tasks.py
After we send the notification, we need to acknowledge the notification is sent in Redis.
This PR addresses that workflow of acknowledging notifications that are already sent.
> Fix acknowledge notification code

- app/celery/tasks.py
[Zenhub card](https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/462)
This Pull Request directly fixes the indentation with the aim of ensuring that it isn't omitted down the line of invocation.
---
> jouer au détective. Veuillez aussi inclure toutes les étapes de configuration
> de …
> FIX: Reply_to when processing CSV rows

- app/celery/tasks.py
Added more logs to trace through the code
> Added more logs

- app/delivery/send_to_providers.py
> Add more logs

- app/config.py
- tests/app/v2/notifications/test_post_notifications.py
Changed default attachment file size limit from 120k to 10m. This is an individual file limit and some users send relatively big PDF at the moment that gets over 1m, hence 120k would be a too low limit.
I will bring in new changes to put a size limit on variable content (not in this PR), which is the real change we want to have. I'd like to keep that one though around individual file size limit as this could prove useful as well.
Same automated tests should act as regression.
None.
> Necessary steps to perform before and after the deployment of these changes.
> For example, emptying the cache on a feature that changes the cache data
> structure in Redis could be mentioned.
---
> Étapes nécessaires à exécuter avant et après le déploiement des changements
> introduits par cette proposition. …
> Changed individual attachment file size from 120k to 10M

- app/config.py
- app/notifications/validators.py
- app/schema_validation/__init__.py
- tests/app/conftest.py
- tests/app/v2/notifications/test_post_notifications.py
Added a size limit on the overall template variables size in order to avoid notifications stuck in SQS queues, which has a limit of 256k. This can be configured via the `PERSONALISATION_SIZE_LIMIT` environment variable. The default is set to `50kb`. The limit was determined by looking at our historic data of the past week and I found the max personalisation data we got was around 17kb.
This could be even too low considering that a batch of 10 notifications can be queued in SQS and if each of these have a size of 40kb, then only 7 are necessary to overflow the SQS limit.
Added a limit on the number of attachments a notification can contain. This can be configured via the `ATTACHMENT_NUM_LIMIT` environment variable. The default is set to `10`.
* Added new automated tests that test the …
> Added personalisation var limit

- tests/app/notifications/test_process_notification.py
We moved from `persist_notification` to `persist_notifications`
This Pr does the following:
1. Updates the tests to all be broken up by classes (for the functions they are calling)
2. All the persist_notification tests were moved to `persist_notifications` calls
3. Moved the tests around to format the code (rearranged all the tests based on their calls)
4. Marked the letter code as deprecated.
> Edit Tests related to persist_notifications

- app/celery/tasks.py
Add further logs for `send_notify_no_reply`
> Add logging

- .github/workflows/test.yaml
> Add waffles check to API

- app/models.py
- app/schemas.py
- app/service/rest.py
- migrations/versions/0421_add_sms_daily_limit.py
- tests/app/conftest.py
- tests/app/dao/test_services_dao.py
- tests/app/db.py
- tests/app/service/test_rest.py
Add new `sms_daily_limit` property. Backfill to 1000
- run `flask db upgrade` and see it in your local database
- run locally with admin and ensure that you can still use old services and create new ones
None.
> add sms_daily_limit to database and models

- .github/workflows/test.yaml
Waffles is currently [failing its checks on the API repository](https://github.com/cds-snc/notification-api/actions/runs/3054456250/jobs/4926939650). A diagnostic of the issue seems to point to an incorrect URL used to configure Waffles.
* Fixed URL targeting admin instead of API
---
> jouer au détective. Veuillez aussi inclure toutes les étapes de …
> Fixed URL targeting admin instead of API

- app/notifications/process_notifications.py
problem:
- number_of_sms_fragments() is called with a `template` fetched from the database
we are getting a `KeyError: 'template_type'` in `template.__dict__`.
Reason:
- `template` is a `TemplateHistory` object, fetched by sqlAlchemy. But it seems to be a lazy fetch, in that at first the dict is just `{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x7f3b4ccee880>}`
- after we access a property of `template` the rest of the keys are in the dict, including `template_type`
- so we add a check here (not a bad idea anyway) that sets things appropriately.
None. …
> fix number_of_sms_fragments

- app/config.py
> fix/set FF correctly

- app/celery/tasks.py
- app/delivery/send_to_providers.py
This is for testing celery and to see what happens when we kill celery when a process is still running.
> Add sleep function for testing

- app/celery/tasks.py
- app/delivery/send_to_providers.py
Reverts cds-snc/notification-api#1622
> Revert "Add sleep function for testing"

- app/models.py
- app/notifications/validators.py
- tests/app/notifications/test_validators.py
I wanted to add some type annotations to `validators.py` to help make it easier to fix the "over sms daily limit" logic and error messages. This PR should not have an effect on app behaviour - the types are purely annotations to make development easier.
I referred to the mypy docs here: https://mypy.readthedocs.io/en/stable/literal_types.html
> Added some type definitions to `models.py` and `validators.py`

- tests-perf/README.md
Add a README for tests-perf pointing user to the subdirectories, where we have the real documentation.
> perf test README redirect

- requirements-app.txt
- requirements.txt
This is to fix the errors we are getting on staging. The new import was added in this PR:https://github.com/cds-snc/notification-api/pull/1645. It looks like the requirement is satisfied in requirements_for_test.txt but not in requirements.txt.
> Add missing dependency

- requirements-app.txt
- requirements.txt
This PR updates notification-utils in order to fix the the following bugs:
- #925 
- #944 
Bugfix details: https://github.com/cds-snc/notification-utils/pull/150
> Upgrade notification-utils to fix lang tag bugs

- app/v2/errors.py
- tests/app/notifications/test_process_notification.py
- tests/app/notifications/test_validators.py
Update SMS daily limit error message content for clarity
> Update SMS daily limit error message content

- DATAFLOW.md
Was playing around with mermaid and looking at our tasks on Friday and came up with this. Figured it might be useful for new folks.
> Dataflow diagrams

- app/celery/tasks.py
- app/job/rest.py
- app/models.py
- app/notifications/process_notifications.py
- app/notifications/rest.py
- app/notifications/validators.py
- app/service/send_notification.py
- app/sms_fragment_utils.py
- app/v2/notifications/post_notifications.py
- tests/app/job/test_rest.py
- tests/app/notifications/test_process_notification.py
- tests/app/notifications/test_validators.py
- tests/app/service/test_send_one_off_notification.py
- tests/app/test_sms_fragment_utils.py
- tests/app/v2/notifications/test_post_notifications.py
This PR:
- moves all the SMS Limit logic out of celery and process_notifications.py, moves this to the "front door" of the API to where the post requests come in
- splits the "sms daily limit check" and the "send sms limit emails" logic into 2 functions
- makes the `key_type` arguments optional - often we are just passing in a default value
- adds a `sms_requested` argument to the check function, so that we chan check if the requested send would put the service over its limit
- adds the "sms daily limit check" logic to the "CSV send through admin" codepath, in app/job/rest.py. This will prevent the job from being created if the service is at or over their limit
- unit testing will be added in a separate PR by @andrewleith 
See https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc20 …
> Move all SMS Limits logic to the "front door" of the API

- app/queue.py
- requirements_for_test.txt
I wanted to get autocompletions working for statements like https://github.com/cds-snc/notification-api/blob/main/app/queue.py#L174, to ensure we are using the correct call signatures. This should now be working. I also added the logger type while I was at it.
Check out the branch locally and check that autocompletion now works. In queue.py, typing `self._redis_client.` should pull up a list of all the Redis methods.
None.
préoccupations …
> Installed Redis type annotations and added them to queue.py

- app/celery/tasks.py
- app/queue.py
- tests/app/celery/test_tasks.py
- tests/app/test_queue.py
Make sure that if we somehow try to acknowledge an inflight in the wrong queue then we catch the mistake and acknowledge in the correct queue.
This should clear up our bad inflights.
> make acknowledge more robust

- app/status/healthcheck.py
- tests/app/status/test_status.py
A user is having timing issues, added the current time to the `/_status` so that we can ensure that the lambda function is using the correct time.
Just fun the flask app (don't need celery) and go to `http://localhost:6011/`
We'll tell the user in this ticket
https://assistance.cds-snc.ca/a/tickets/9784
setup, etc.) | …
> add current time to status

- app/queue.py
> Fix a typo in the logs

- app/celery/provider_tasks.py
> Log the exception 

- requirements-app.txt
- requirements.txt
- Bump utils to make use of the new logging features in cds-snc/notification-utils/pull/162
> Bump utils version

- requirements-app.txt
- requirements.txt
This reverts commit db98d86c5427c4d4c0d63f3d3f2a031ba1764309.
> Revert "Bump utils version (#1735)"

- app/celery/process_sns_receipts_tasks.py
> fix typo in log entry

- app/celery/tasks.py
This fixes the issue where errors related to the daily limit are going uncaught if they are raised from Celery, which can cause our on-call alarms to be triggered. 
These errors are also raised as part of the request cycle, and they create the error response that the user sees if they are over their daily limit. These errors are only raised in celery if the user makes more requests than allowed by their daily limit (these would have to happen quickly). This may only be a problem for email, but I applied the fix to the `save_smss` function as well, just to be safe.
I also needed to split out a new function since flake 8 was complaining that `save_notifications` was too complex.
This should be merged after https://github.com/cds-snc/notification-api/pull/1740
Here is the test that I ran: …
> Catch and log the "over daily limit" errors if they are raised in Celery

- app/celery/tasks.py
Added documentation on the ses_receiving_emails Celery task, as part of the Notify code review sessions. We digged into the code and added documentation along the way on the lambda responsible for forwarding emails to the celery task that sends no-reply emails.
Nothing to test, except for my English writing skills. 🧑‍🏫
None.
> Necessary steps to perform before and after the deployment of these changes.
> For example, emptying the cache on a feature that changes the cache data
> structure in Redis could be mentioned.
---
> Étapes nécessaires à exécuter avant et après le déploiement des changements
> introduits par cette proposition. Par exemple, vider la cache suite à des
> changements modifiant une structure de données de la cache pourrait être
> mentionné.
This is a suggested checklist …
> Added doc for ses_receiving_emails Celery task

- app/celery/process_ses_receipts_tasks.py
- app/clients/email/aws_ses.py
This PR adds logging to capture SES responses during synchronous and asynchronous communication.
- Synchronous email send in `AwsSesClient.send_email()`
- Asynchronous response in `process_ses_results()` celery task
> Add logging for synchronous and asynchronous email replies from SES

- ci/Dockerfile
- ci/Dockerfile.lambda
- ci/Dockerfile.test
- local/Dockerfile
Reverts cds-snc/notification-api#1749
> Revert "Poetry fix ci"

- requirements-app.txt
- requirements.txt
This pr updates API to make use of v50.1.2 of notifier utils in order to take advantage of some enhanced logging features.
> Add enhanced logging feature from utils.

- .github/workflows/test.yaml
- Makefile
- app/__init__.py
- app/config.py
- app/delivery/send_to_providers.py
- poetry.lock
- pyproject.toml
- scripts/run_celery.sh
- scripts/run_celery_beat.sh
- scripts/run_celery_sms.sh
- tests/app/delivery/test_send_to_providers.py
Reverts cds-snc/notification-api#1783
> Revert "Task/redis add bounce"

- app/config.py
- app/user/rest.py
Populate the organisation that is displayed in the Freshdesk "go live" ticket from the new `organisation_notes` column.
Tested locally and it is working:
1. Run notification-admin locally with the branch: `wip/salesforce-integration` and the following in your .env from `notification-manifests/env/staging/.env`:
```
FF_SALESFORCE_CONTACT=true
SALESFORCE_USERNAME=
SALESFORCE_CLIENT_KEY=
SALESFORCE_CLIENT_PRIVATEKEY=
SALESFORCE_ENGAGEMENT_RECORD_TYPE=
SALESFORCE_GENERIC_ACCOUNT_ID=
```
2. Run this branch of the API locally, with values in your .env file for the following variables from `notification-manifests/env/staging/.env`:
```
FF_SALESFORCE_CONTACT=true
FRESH_DESK_API_URL
FRESH_DESK_API_KEY
FRESH_DESK_PRODUCT_ID
FRESH_DESK_ENABLED
ZENDESK_API_KEY
ZENDESK_API_URL
ZENDESK_SELL_API_KEY …
```
> Populate the org in Freshdesk "go live" ticket from `organisation_notes`

- app/dao/notifications_dao.py
This is preliminary work so I can fix this report in Admin with a PR similar to https://github.com/cds-snc/notification-admin/pull/1520
> Add labels that will be returned with query data for the API vs UI report

- .github/workflows/test.yaml
- poetry.lock
- pyproject.toml
Update notification-utils to 50.2.5
> Update notification-utils to 50.2.5

- .github/workflows/test.yaml
- poetry.lock
- pyproject.toml
> Update utils to 50.3.0

- .github/workflows/test.yaml
> Bump waffles to 50.3.1

- app/clients/salesforce/salesforce_auth.py
- app/clients/salesforce/salesforce_contact.py
- app/clients/salesforce/salesforce_engagement.py
- app/clients/salesforce/salesforce_utils.py
Add a unique token to all Salesforce error logs so that dedicated CloudWatch alarms can be created to alert the Salesforce team.
- cds-snc/platform-core-services#370
> feat: update Salesforce errors with metric token

- scripts/resign_database.py
Add `--notifications` if you want to resign notifications. default is to ignore the table.
Also added single character alternative for flags.
resign things
> add a flag for resigning notifications

- app/delivery/send_to_providers.py
Had a celery error
https://gcdigital.slack.com/archives/C012W5K734Y/p1686873733012959
Would be good to see what the actual exception is in this case.
> Log the exception when there's a problem sending a file

- app/notifications/rest.py
Add some logging so we know when requests are made to the V1 api. Is anyone using it? We will find out!
> Add some logging so we know when requests are made to the V1 api

- app/template/rest.py
Add logging when the email char limit is exceeded
> Add logging when the email char limit is exceeded

- .devcontainer/devcontainer.json
VSCode was complaining about how this file is organized, I did what it said to do and the squiggly orange lines went away.
rebuild devcontainer and check that the settings, extensions are still there
> reorg devcontainer.json

- scripts/run_celery.sh
Reverts cds-snc/notification-api#1947
This was just for a test, we don't want it in production.
> Revert "Double number of concurrent celery workers (DO NOT RELEASE TO PROD)"

- app/celery/scheduled_tasks.py
- app/celery/tasks.py
- app/encryption.py
- app/json_provider.py
- poetry.lock
- pyproject.toml
- tests/app/aws/test_metrics.py
- tests/app/test_json_provider.py
- tests/app/test_queue.py
- tests_cypress/package-lock.json
Having too many issues around resolving https://github.com/cds-snc/notification-api/pull/1913
This upgrade mypy to a major version 1.5
> Upgrade mypy t 1.5

- poetry.lock
- pyproject.toml
- tests/app/delivery/test_send_to_providers.py
Bump utils version to 52.0.8. 
Related work: 
* https://github.com/cds-snc/notification-utils/pull/241
> bump utils 52.0.8

- .gitignore
Just adding my production smoke test script to the gitignore.
smoketest-prod.sh should not be part of this PR
None.
> Adding prod smoketest script to gitignore

- app/celery/process_ses_receipts_tasks.py
- app/config.py
- app/delivery/send_to_providers.py
- app/models.py
- app/v2/notifications/post_notifications.py
- tests/app/conftest.py
- tests/app/delivery/test_send_to_providers.py
- tests/app/service/test_rest.py
- tests/app/test_model.py
Remove the old `FF_BOUNCE_RATE_BACKEND` feature flag.
Tests should pass in CI, the api should behave the same as before.
> Remove the `FF_BOUNCE_RATE_BACKEND` feature flag

- scripts/run_celery_send_sms.sh
upping concurrency didn't really help...
> back to 4 concurrency for sms send

- .github/workflows/test.yaml
- poetry.lock
- pyproject.toml
Update utils in api to use the latest version
> Update utils to the latest version 52.0.11

- scripts/run_celery_exit.sh
Update the celery exit script to send to stderr
> Fix script to send to std err

- scripts/run_celery_exit.sh
Instead of writing to stdout we will try the above. This is because of the following assumption:
1. celery runs on one thread
2. this script runs on another thread
the script doesnt write to the same stdout that gets picked by the cloudwatch agent. (again this is a working theory)
by making the above change, we should be writing to the same output which will then translate to logs on cloudwatch
To be tested on staging 🤞🏽
> Change the output of echo to /proc/1/fd/1

- app/config.py
- gunicorn_config.py
- newrelic.ini
Adding dev environment configuration
> Adding dev environment

- migrations/versions/0440_add_index_n_history_comp.py
- migrations/versions/0441_add_apikey_revoke_email.py
> fix alembic version

- .github/workflows/test.yaml
- poetry.lock
- pyproject.toml
Update utils to [52.0.15](https://github.com/cds-snc/notification-utils/releases/tag/52.0.15)
> update utils to 52.0.15

- app/dao/services_dao.py
- app/job/rest.py
- app/service/send_notification.py
- app/sms_fragment_utils.py
- app/v2/notifications/post_notifications.py
- poetry.lock
- pyproject.toml
- tests/app/dao/test_services_dao.py
- tests/app/v2/notifications/test_post_notifications.py
Reverts cds-snc/notification-api#2024
> Revert "Count by sms messages not sms parts for daily limit"

- .github/workflows/test.yaml
- app/dao/services_dao.py
- app/job/rest.py
- app/service/send_notification.py
- app/sms_fragment_utils.py
- app/v2/notifications/post_notifications.py
- poetry.lock
- pyproject.toml
- tests/app/dao/test_services_dao.py
- tests/app/v2/notifications/test_post_notifications.py
Merging back : https://github.com/cds-snc/notification-api/pull/2042
and https://github.com/cds-snc/notification-api/pull/2024
> Add reverted code

- .github/workflows/test.yaml
- app/dao/services_dao.py
- app/job/rest.py
- app/service/send_notification.py
- app/sms_fragment_utils.py
- app/v2/notifications/post_notifications.py
- poetry.lock
- pyproject.toml
- tests/app/dao/test_services_dao.py
- tests/app/v2/notifications/test_post_notifications.py
Reverts cds-snc/notification-api#2045
> Revert "Add reverted code"

- .github/workflows/test.yaml
- app/dao/services_dao.py
- app/job/rest.py
- app/service/send_notification.py
- app/sms_fragment_utils.py
- app/v2/notifications/post_notifications.py
- poetry.lock
- pyproject.toml
- tests/app/dao/test_services_dao.py
- tests/app/v2/notifications/test_post_notifications.py
Reverts cds-snc/notification-api#2046, restoring the original work done in [#2048](https://github.com/cds-snc/notification-api/pull/2024)
> Revert "Revert "Add reverted code""

- app/celery/process_ses_receipts_tasks.py
This PR extends the exception logging in the `process_ses_results()` method to add some extra info when an exception occurs. It adds the following to the log message, if present:
- notification ID
- notification status
- reference ID
> chore(process_ses_results): add more details in exception logging

- .github/workflows/docker.yaml
We split the scaling celery deployments into primary and scalable but forgot to update the GitHub action 😅 
Merge this PR and see what happens!
> use new primary and scalable celery deployments in github actions

- app/dao/date_util.py
- app/dao/fact_notification_status_dao.py
- tests/app/dao/test_fact_notification_status_dao.py
Reverts cds-snc/notification-api#2069
> Revert "Match the 5AM->5AM time window used to populate ft_notifications"

- tests_smoke/smoke/test_api_bulk.py
- tests_smoke/smoke/test_api_one_off.py
Fix smoke test to send the entire API key
> Fix smoke test

- tests_smoke/smoke/common.py
> Fix api key

- app/dao/fact_notification_status_dao.py
- app/dao/services_dao.py
- app/service/rest.py
- tests/app/dao/test_fact_notification_status_dao.py
- tests/app/dao/test_services_dao.py
- tests/app/service/test_rest.py
Reverts cds-snc/notification-api#2108
The language toggle on the index page was causing major slow downs and in some cases full timeouts.
> Revert "Task: Filter Heartbeats"

- app/celery/nightly_tasks.py
Getting SIGKILLs probably because of this task OOMing over a bad job. This logging should show if this is the case.
[Slack discussion here](https://gcdigital.slack.com/archives/CV38DBNVA/p1709148023544659).
To test locally:
- change [this line](https://github.com/cds-snc/notification-api/blob/260722e4ffdcf9b2f865583161dd6642e9f36fad/app/config.py#L486) to `"schedule": 10,` (to run the task every ten seconds
- change [this line](https://github.com/cds-snc/notification-api/blob/260722e4ffdcf9b2f865583161dd6642e9f36fad/app/dao/jobs_dao.py#L153) to `end_date = today + timedelta(days=7)` (to remove all jobs, not just old ones)
- purge your queues with `make run-celery-purge`
- run celery / api. You should see `TEMP LOGGING: trying to remove 0 jobs.` every 10 seconds.
- POST a job to your local …
> add more logging to the remove_sms_email_jobs task

- app/clients/freshdesk.py
- app/user/contact_request.py
- app/user/rest.py
- tests/app/clients/test_freshdesk.py
- tests/app/user/test_rest.py
This PR adds `organisation_id` and `organisation_name` to the branding contact request.
> Add organisation info to the freshdesk branding request

- migrations/versions/0447_update_verify_code_template.py
This PR updates the 2FA email to make the code easier to select.
* https://github.com/cds-snc/notification-planning/issues/603
- Receive a 2FA login email
- Ensure code 
> Enhance 2FA email template to make code easier to select

- migrations/versions/0448_update_verify_code2.py
Removed the bold, so its easier to copy paste
> Remove bold

- .github/workflows/test.yaml
- app/delivery/send_to_providers.py
- poetry.lock
- pyproject.toml
- tests/app/delivery/test_send_to_providers.py
Add alt text changes for utils to api 
Send an email through the api with a Brand that has an english and french alt text. See that it is propogated into theHTML of the email you send
> Util changes for alt text

- app/delivery/send_to_providers.py
- tests/app/delivery/test_send_to_providers.py
Tweak code to allow the shortcode pool to be configured but not the default pool
This means that:
- SMS using a shortcode pool template will be sent by Pinpoint with the shortcode pool
- SMS not using the shortcode pool template will be sent with SNS
This will allow up to dip our production toes in the Pinpoint waters.
* https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/361
Tested locally:
1. Set env vars (from staging):
```
AWS_PINPOINT_SC_POOL_ID = "pool-b20333ce1e4e49309ba1db3bf94a3f57"
AWS_PINPOINT_SC_TEMPLATE_IDS = <one of your sms templates>
```
2. Send an sms using a template in the SC list. It should be sent by Pinpoint (in the logs you should see `AWS Pinpoint request finished in ...`)
3. Send an sms using …
> Send with Pinpoint shortcode pool if appropriate and otherwise SNS

- .github/workflows/docker.yaml
Moving away from Github ARC and instead using a VPN to connect to K8s to deploy API.
Docker build/push/deploy works and the new image is deployed to staging.
> API using staging vpn

- migrations/versions/0456_update_template_categories.py
Added a new column to the TemplateCategory table called "sms_sending_vehicle". Added reasonable defaults.
Updated priority type for old template categories.
SMS_sending_vehicle is currently determined here: https://docs.google.com/document/d/1xhBHjVywBgZTk2A76B7hJOSj0RjpR5ttu6cGDBI98PQ/edit
we can change it through a another migration once further discussion has taken place
* https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1609
```
notification_api=# select name_en, sms_sending_vehicle from template_categories;
name_en          | sms_sending_vehicle 
--------------------------+---------------------
Authentication           | short_code
Automatic reply          | short_code
Decision                 | short_code
Reminder …
```
> Added a new column and updated existing template categories

- app/clients/sms/aws_sns.py
Fixes an error introduced in #2216 
* https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/382
Send SMS without Pinpoint pools configured
None.
> add sending_vehicle argument to sns send_sms

- app/dao/template_categories_dao.py
- app/template/template_category_rest.py
Reverts cds-snc/notification-api#2228
> Revert "Add logs when getting all TC's"

- migrations/versions/0457_update_categories.py
```
notification_api=# select name_en, email_process_type, sms_process_type from template_categories ;
name_en          | email_process_type | sms_process_type 
--------------------------+--------------------+------------------
Information blast        | bulk               | bulk
Test                     | bulk               | bulk
Low Category (Bulk)      | bulk               | bulk
Medium Category (Normal) | normal             | normal
Alert                    | normal             | normal
Authentication           | priority           | priority
Automatic reply          | priority           | priority
Decision                 | low                | low
Reminder                 | normal             | normal
Request                  | normal             | normal
Status update            | …
```
> Fix process type for alert category

- migrations/versions/0458_drop_null_history.py
Drop null constraint for process_type :
```
Table "public.templates_history"
Column           |            Type             | Collation | Nullable | Default 
---------------------------+-----------------------------+-----------+----------+---------
id                        | uuid                        |           | not null | 
name                      | character varying(255)      |           | not null | 
template_type             | template_type               |           | not null | 
created_at                | timestamp without time zone |           | not null | 
updated_at                | timestamp without time zone |           |          | 
content                   | text                        |           | not null | 
service_id                | uuid                        | …
```
> Drop null constraint for process_type

- poetry.lock
- pyproject.toml
> New Relic Agent 8.10.1 Test

- poetry.lock
- pyproject.toml
Reverts cds-snc/notification-api#2241
> Revert "New Relic Agent 8.10.1 Test"

- run_celery.py
Minor bit of code to add the middleware.  We will see how this reacts in Staging before enhancing the code.
> attempting to get celery to show up in xray

- app/celery/celery.py
- app/celery/scheduled_tasks.py
Reverts cds-snc/notification-api#2248
> Revert "Moving xray code to a more centralized location"

- app/aws/xray_celery_handlers.py
- app/celery/celery.py
This is a tentative revert of cds-snc/notification-api#2266 , in case things catch 🔥 in the staging environment once deployed.
> Revert "Added back logging signals for beat workers"

- app/models.py
- app/schemas.py
- tests/app/dao/test_services_dao.py
- tests/app/service/test_rest.py
Reverting this PR https://github.com/cds-snc/notification-api/pull/2255/files
> Revert PR #2255 as it is causing some failures

- app/dao/notifications_dao.py
- tests/app/dao/notification_dao/test_notification_dao_delete_notifications.py
We were deleting data from the notifications table for partial days. We want to delete the data for the entire day. This PR changes our datetime handling to fix that
> Fix Notification History to have the full day of data

- app/config.py
For testing purposes on staging
> kick off job

- app/config.py
_TODO: 1-3 sentence description of the changed you're proposing._
None.
> change the schedule to run on prd

- .github/workflows/ai-code-scanner.yml
Bringing in the AI code review into notification-api. Include the `[review]` snippet into your commit message to trigger a GitHub action AI review on the associated PR. 
Please review the _included_ and _excluded_ patterns for the AI review bot to consider.
* None
Submit a commit with an opened PR to trigger the action. 
None.
> Configure the AI review on new PRs

- ci/Dockerfile.lambda
Reverts cds-snc/notification-api#2330
> Revert "Pull libexecinfo-dev from alpine 3.16 repo"

- tests_cypress/package-lock.json
- tests_cypress/package.json
Axe-core 4.10.10 doesn't exist. Moved to an earlier version
Setup the app locally
> Axe-core 4.10.10 doesn't exist

- .devcontainer/scripts/notify-dev-entrypoint.sh
Found this branch I made a month ago but didn't make a PR! Still useful for quickly testing dev.
smoke test dev (when it's up 😬 )
None.
> add a smoke-dev alias to devcontainer

- .github/workflows/docker.yaml
Forgot to install terraform/grunt for the auto vpn.
chore
Build/Push works
None.
> Terraform prereq for build and push

- .github/workflows/build_and_push_performance_test.yml
- .github/workflows/docker-vulnerability-scan.yml
- .github/workflows/docker.yaml
- .github/workflows/lambda_production.yml
- .github/workflows/lambda_staging.yml
Reverts cds-snc/notification-api#2368
> Revert "normalizing secrets"

- migrations/versions/0469_edit_emails.py
Edit emails as the links were formatted incorrectly
> Edit the emails as the links were formatted incorrectly

- app/celery/reporting_tasks.py
> Reduce chunk size for sfetch notification status job

- poetry.lock
Needed to update poetry.lock to the latest sha
> update to the latest version of util

- app/celery/reporting_tasks.py
- app/dao/fact_notification_status_dao.py
Added more logging so we can see how celery jobs are called and processed.
None.
> Added more logging

- app/notifications/process_notifications.py
- tests/app/notifications/test_process_notification.py
Reverts cds-snc/notification-api#2422
> Revert "incident fix maybe - stop updating api key last used"

- bin/execute_and_publish_performance_test.sh
#2449 Had a typo 😞 
* https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/485
Hopefully the perf tests run this time...
None.
> Fix typo in perf test script

- app/config.py
- app/v2/notifications/post_notifications.py
Removed letter-tasks and antivirus tasks - these were only used for letters
> Remove old queue tasks

- app/celery/provider_tasks.py
- app/dao/notifications_dao.py
- app/models.py
- tests/app/celery/test_provider_tasks.py
- tests/app/dao/notification_dao/test_notification_dao.py
- tests/app/test_model.py
- tests_cypress/package-lock.json
Reverts cds-snc/notification-api#2448
> Revert "Set notification status when international-bound SMS fail"

- app/celery/provider_tasks.py
- app/dao/notifications_dao.py
- app/models.py
- tests/app/celery/test_provider_tasks.py
- tests/app/dao/notification_dao/test_notification_dao.py
- tests/app/test_model.py
- tests_cypress/package-lock.json
Reverts cds-snc/notification-api#2462
> Set notification status when international-bound SMS fail - Round 2

- app/email_branding/rest.py
- app/errors.py
- app/template/template_category_rest.py
- tests/app/email_branding/test_rest.py
- tests/app/template/test_template_category_rest.py
- tests/app/test_errors.py
Reverts cds-snc/notification-api#2471
> Revert "Revert "Add integrity error handling for email branding and template categories""

- app/aws/s3.py
- app/celery/scheduled_tasks.py
- app/celery/tasks.py
- app/config.py
- app/dao/reports_dao.py
- app/models.py
- app/report/utils.py
- app/schemas.py
- tests/app/aws/test_s3.py
- tests/app/celery/test_scheduled_tasks.py
- tests/app/celery/test_tasks.py
- tests/app/conftest.py
- tests/app/report/test_utils.py
Add a celery task to generate the reports. This PR does the following:
- adds a new scheduled celery task `run-generate-reports` that runs every minute
- adds a new celery task `generate-report` that is called by the scheduled task
- adds a new function `create_report_in_s3` that gets the report data from the db and uploads the file to s3
- adds some new functions in app/report/utils.py that are used to generate the csv file
What this PR doesn't do - I'll do these in follow up PRs:
- doesn't get more than the first page of report data (only the first 5000 rows)
- doesn't do a multipart s3 upload - this will be needed for large reports
- doesn't generate a pre-signed s3 url
- doesn't translate the csv file into french
* https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed2 …
> Add a celery task to generate the reports

- app/celery/scheduled_tasks.py
- tests/app/celery/test_scheduled_tasks.py
Fix the log level in the `run-generate-reports` celery task.
> Log level error -> info

- app/models.py
- app/schemas.py
This will allow it to be displayed by the "Delivery reports" page on admin.
You could test this locally running api and admin, or could test more easily in the admin review app once this is deployed in staging: https://github.com/cds-snc/notification-admin/pull/2136
> Add requesting user to the api response

- app/aws/mocks.py
- app/celery/process_ses_receipts_tasks.py
- app/dao/notifications_dao.py
- app/notifications/notifications_ses_callback.py
- tests/app/celery/test_process_ses_receipts_tasks.py
- tests/app/notifications/test_notifications_ses_callback.py
Reverts cds-snc/notification-api#2489
> Revert "Batch save ses receipts"

- app/celery/process_ses_receipts_tasks.py
Reverts cds-snc/notification-api#2520
> Revert "Fix a bug with `process_ses_receipts_tasks` logging"

- app/aws/mocks.py
- app/celery/process_ses_receipts_tasks.py
- app/dao/notifications_dao.py
- app/notifications/notifications_ses_callback.py
- tests/app/celery/test_process_ses_receipts_tasks.py
- tests/app/notifications/test_notifications_ses_callback.py
Reverts cds-snc/notification-api#2518
> Revert "Batch save ses receipts - V2"

- .github/workflows/test.yaml
- app/annual_limit_utils.py
- app/celery/process_ses_receipts_tasks.py
- poetry.lock
- pyproject.toml
- tests/app/celery/test_process_ses_receipts_tasks.py
Reverts cds-snc/notification-api#2527
> Revert "Fix mapping by adding a double check"

- app/config.py
- app/dao/fact_notification_status_dao.py
This will return the stats on the /activity page to what they were before the migration to the new heartbeat service.
> Add the new heartbeat service id

- app/annual_limit_utils.py
_TODO: 1-3 sentence description of the changed you're proposing._
None.
> Reseed data if we are missing either email or sms annual data

- bin/entry.sh
outputting some better logging info for env variables to the entry.sh script
> Better ENV Logging

- bin/entry.sh
- ci/Dockerfile.lambda
adding enhanced logging to the entry.sh script for more visibility of injected env variables from param store
None.
> Enhanced Env Var Logging in Entry.sh

- README.md
Reverts cds-snc/notification-api#2637
> Revert "TEST (No Changes)"

- bin/entry.sh
- ci/Dockerfile.newrelic.lambda
- newrelic.ini
rolling back these 3 files to state prior to NR being disabled
> Rolling back these 3 files to state prior to NR being disabled

- README.md
Reverts cds-snc/notification-api#2652
> Revert "Dummy to fix CI"

- application.py
Trying the wsgi wrapper for new relic to enable metrics in our Lambda APM Setup
https://docs.newrelic.com/docs/apm/agents/python-agent/python-agent-api/wsgiapplication-python-agent-api/
Also adding some mild logging to expose our new relic Env variable configuration for debugging.
> adding wsgi and some logging

- application.py
Reverts cds-snc/notification-api#2657
> Revert "adding wsgi and some logging"

- application.py
Reverts cds-snc/notification-api#2659
> Revert "New Relic WSGI Wrapper"
