app/config.py, app/notifications/rest.py, requirements-app.txt, requirements.txt, tests/app/celery/test_tasks.py, tests/app/conftest.py, tests/app/dao/notification_dao/test_notification_dao.py, tests/app/dao/test_services_dao.py, tests/app/db.py, tests/app/delivery/test_send_to_providers.py, tests/app/inbound_sms/test_rest.py, tests/app/notifications/rest/test_send_notification.py, tests/app/notifications/test_process_notification.py, tests/app/notifications/test_receive_notification.py, tests/app/notifications/test_rest.py, tests/app/notifications/test_validators.py, tests/app/public_contracts/test_POST_notification.py, tests/app/service/test_rest.py, tests/app/service/test_send_one_off_notification.py, tests/app/service/test_service_whitelist.py, tests/app/test_model.py, tests/app/test_schemas.py, tests/app/user/test_rest.py, tests/app/v2/notifications/test_get_notifications.py, tests/app/v2/notifications/test_notification_schemas.py, tests/app/v2/notifications/test_post_notifications.py
Bumped the utils version to the version that uses `local` phone number function vs a `uk` phone number function. Many of the tests used UK specific prefixes, ex: `07`, replaced those with North American prefixed  `1-XXX` or just plain area code.
=> Utils bump

app/__init__.py, app/celery/process_ses_receipts_tasks.py, requirements-app.txt, requirements.txt, tests/app/celery/test_process_ses_receipts_tasks.py
There is currently no way for SES to report the status of message delivery back to the API. Based on code fragments and some of the code in AU code base it looks like there used to be a route that was called by SNS when an email was processed. It looks like the GDS code base took this out and put it into a lambda function that updates the database directly, or uses a second non-api queue to handle the insertion. I have restored the URL based on the AU code and added tests. This should close #63
=> SES callback

ci/Dockerfile.statsD, ci/cloudbuild-statsd.yaml
Added a docker file that can be used to deploys to a k8s cluster in GKE that will forward the StatsD data to Stackdriver. Closes #92
=> Added statsd container for stackdriver

README.md, app/delivery/send_to_providers.py, tests/app/delivery/test_send_to_providers.py
Mark SMS messages as SENT after sending, because SNS has no success callback, closes #96
=> Mark SMS messages as SENT after sending

app/dao/users_dao.py, app/user/rest.py, tests/app/dao/test_users_dao.py
Fixes: https://github.com/cds-snc/notification-api/issues/124
This PR adds a query to look at verification codes sent within a given timeframe.
If multiple codes are founds it will fire an 
```
raise InvalidRequest("Code already sent", status_code=400)
```
Not sure if that's the best response code.
@JuliannaR had this occur today as well as 2 other testers so far.
=> Block multiple verify codes from being sent within a given timeframe

migrations/versions/0300c_remove_email_branding.py, migrations/versions/0300d_update_invite_email.py
Closes #140 and also removes the default email branding
=> Migrations to remove default email branding

app/config.py
We are having trouble automatically extracting the correct domain to use for the Fido2 server, so we might as well just define it through ENV
=> Make Fido2_Domain configurable

app/clients/document_download.py, app/clients/email/aws_ses.py, app/delivery/send_to_providers.py, ci/Dockerfile, ci/Dockerfile.test, requirements-app.txt, requirements.txt, tests/app/clients/test_aws_ses.py, tests/app/clients/test_document_download.py, tests/app/delivery/test_send_to_providers.py
Closes #287 
Added the following changes:
- Instead of returning just the public URL the upload document now returns the direct download and public URL, which is then substituted in for the personalization.
- When the message is processed for sending it checks if any of the personalizations are a download link.
- If it is a download link, it downloads the content, determines the mime type, and if it is a PDF, attaches it to the message.
- Currently only AWS SES is implemented (also it is the only option we have)
=> Adds attachments to emails if they are part of download links

app/notifications/notifications_ses_callback.py
The custom formatter for logging is not able to properly handle nested json objects. This may not be the perfect fix but it allows the log to remain readable by a human while fixing the celery error.
=> Fix JSON logging bug

app/api_key/rest.py, app/dao/fact_notification_status_dao.py, tests/app/api_key/test_rest.py, tests/app/dao/test_fact_notification_status_dao.py
Working on addressing @timarney's [comment](https://github.com/cds-snc/notification-admin/pull/411#issuecomment-601642344).
This PR:
- changes the endpoint name from "total-sends" to "summary-statistics" since we are now returning more data
- fixed an error where I was querying the wrong table 😓 
- added a new query to get the last time the api key was used, added that to the data returned from the endpoint
- tests
=> More API key stats

app/dao/services_dao.py, tests/app/dao/test_services_dao.py
This query is used only for the endpoint /live-services-data. In notification-admin this endpoint is used for a number of pages, not just the homepage. The structure of the data returned should not change so I don't think this will break any of those pages. 
The fiscal year is in there for billing purposes, so this will probably make the billing pages/data incorrect. But we're not using that anyway. 
A better approach here would be to create a new endpoint - but that would need some new tests and would take longer to get online. If that's the direction we want to go I will have time to work on that later today.
=> Removed the limit on financial year from the query that is used for homepage stats

.gitignore, README.md, app/delivery/send_to_providers.py, application.py, requirements-app.txt, requirements.txt
Closes #759 and possibly #763 
This PR, in tandem with the matching PRs in notification-utils and notification-admin, allows devs to use local in-project jinja for sending emails. This allows us to easily preview our markup changes without having to have first pushed them through the notification-utils repo.
Tests will fail until notification-utils has been updated
=> Add ability to use local jinja template for html emails

app/smtp/aws.py
When removing an SMTP integration it would delete DNS records for other integrations that were alphabetically behind. Each integration has six records, so it should only remove those six.
=> Fix DNS bug with SMTP

app/clients/sms/aws_pinpoint.py
This is to make pinpoint and sns behave more like independent services. 
Here is the test I did to arrive at this:
- spun up my local admin and connected it to the api running  locally
- sent myself an SMS from a service with no longcode attached
- observed that I received an SMS from one of our longcodes in us-east-1
- deleted all our longcodes in us-east-1 (on staging)
- send myself a 4 texts from the same service
- observed that I received them from 4 different US longcodes (none were sent from the deleted pinpoint longcodes, hooray)
- created a new Pinpoint project in us-west-2, provisioned a Canadian long code there
- locally switched my pinpoint client region and AWS_PINPOINT_APP_ID (an env variable) over to the new project in us-west-2
- added the new longcode to my local db, then …
=> Move pinpoint region to us-west-2

app/clients/email/aws_ses.py
This reverts a previous fixing of the SES region to us-east-1 because the staging cluster is in ca-central-1 and there was no SES in ca-central-1 (See https://github.com/cds-snc/notification-api/pull/671). Now that ca-central-1 has SES we can use SES in the region that the cluster is in. The production cluster will default to us-east-1 and staging will default to ca-central-1.
=> Un-fixes the SES sending region

app/notifications/notifications_sms_callback.py, tests/app/celery/test_research_mode_tasks.py
Add success callbacks for sns and pinpoint that get used by research mode/test api key sends
This is to fix the error we are seeing in prod when someone uses a test api key:
```API POST request on http://api.notification-canada-ca.svc.cluster.local:6011/notifications/sms/sns failed with None```
Thanks to @maxneuvians for the fix!
I tested locally using a test api key to make calls to send sms to the api running locally. I verified that this code resolved the error.
=> Fix research mode error

app/models.py, migrations/versions/0306c_branding_organisation.py, tests/app/organisation/test_rest.py
Closes #875 
Adds the 'default_branding_is_french' column to the organisation table in the DB as well, similarly to my last PR for services.
=> Add "default_branding_is_french" column to organisations as well

app/celery/tasks.py, app/config.py, app/utils.py, requirements-app.txt, requirements.txt
I can't actually test this locally because csv jobs don't seem to work locally - they are just stuck in pending. Not sure why. So I'll need to test this on staging instead. I have verified that the API behaves as before - nothing will change until the env variables `HC_EN_SERVICE_ID` and `HC_FR_SERVICE_ID` are set.
=> Change max CSV row limit for bulk sending services

app/accept_invite/rest.py, tests/app/accept_invite/test_accept_invite_rest.py
fixes https://github.com/cds-snc/notification-api/issues/784
Rather than having the content here I've changed to simple error messages, the idea being that admin will handle both the English and French content to display to the user.
corresponding admin PR: https://github.com/cds-snc/notification-admin/pull/565
=> send invite error codes for admin to translate

app/celery/tasks.py, app/utils.py
I found these by running a csv send through my local api, with `CSV_MAX_ROWS` and `CSV_MAX_ROWS_BULK_SEND` set to low numbers. Also had to implement a mock email client to do it. Wow that was a lot of work to fix 4 lines.
=> Fixed the bugs in setting max rows

app/user/rest.py, migrations/versions/0307_update_email_2fa_template.py, tests/app/conftest.py, tests/app/user/test_rest_verify.py
Closes #895 
Most of the changes were on the admin side. All I had to do here was switch the email 2fa to use the existing code generation that we use for SMS, and remove the old code.
Also added a new DB migration to update the email 2fa template. I did this as a migration to ensure the new variables / content filter through to staging / local dev environments etc. I did not add this as a new version, but the content will replace whatever the current version is on each of these systems. I did this to account for there possibly being different version numbers on staging vs prod, and not knowing what version the template will have anytime this migration is run.
A consequence of this is that all old versions of this template will also have the new content written into them, so we will …
=> Email two-factor now sends a 5 digit code instead of a clickable link

app/dao/users_dao.py, app/service/rest.py, tests/app/service/test_rest.py, tests/app/user/test_rest.py
Just updating a couple error strings.
I split an error message into multiple keys to be strung back together on the admin side to account for a variable in the middle.
Closes #953
=> Update some error messages for translation

app/user/rest.py
resolves https://github.com/cds-snc/notification-api/issues/1014
Stop sending the "account change" email when a user gets blocked.
=> no email when we block users

app/user/rest.py, tests/app/user/test_rest.py
Return an error if a blocked user attempts to reset password.
Corresponding admin PR: https://github.com/cds-snc/notification-admin/pull/657
=> Don't allow blocked users to reset password

app/notifications/validators.py, tests/app/notifications/test_validators.py
Reverts cds-snc/notification-api#1038
Since this didn't seem to do anything, and since our problems seem to be related to other things, figured it was best to remove this.
=> Revert "Put in an aggressive rate limit for test keys"

requirements.txt
new pods are crashing with `dnspython` 2.0.0 (introduced in https://github.com/cds-snc/notification-api/pull/1051). Fix this for now, and investigate how to adapt our code later.
=> downgrade dnspython to 1.16.0

app/models.py, app/schemas.py, app/service/utils.py, tests/app/dao/test_service_whitelist_dao.py, tests/app/notifications/rest/test_send_notification.py
re https://github.com/cds-snc/notification-api/issues/962
change property service.whitelist to service.safelist
should have been part of https://github.com/cds-snc/notification-api/pull/1040 🤷
=> rename service.whitelist property

app/models.py, migrations/versions/0308_rename_service_whitelist_table.py
re https://github.com/cds-snc/notification-api/issues/962
rename database table `service_whitelist` to `service_safelist`. This requires a database migration as well as updating the place we join in the table.
To test:
- run everything locally
- use service / api integration / safelist to add add some more email address to a service's safelist
- look at the stuff in the `service_whitelist` table in the database
- run migration
- verify that local table `service_whitelist` was renamed to `service_safelist` and still has the same content as before
- restart api
verify via service / api integration / safelist that you can see the email addresses added to the service
=> rename service_whitelist table

requirements-app.txt, requirements.txt
To be merged after https://github.com/cds-snc/notification-utils/pull/60 is merged and released
=> Bump utils to 43.0.2

app/user/rest.py
**Story**
When users upload branding images we need to have the email address included so we know who to respond to.
**What?**
Branding requests currently come in like this https://assistance.cds-snc.ca/a/tickets/901 They need an email.
**Done When**
A branding Request has email in it.
Demo: (note the different recipient/request address - Freshdesk is the recipient in prod)
https://trello.com/c/0fGhyLwF/45-include-users-email-in-a-branding-request-notification
=> Fill the requester's email in a branding request

requirements-app.txt, requirements.txt
Trello card https://trello.com/c/sjXUFIY9/62-recurring-dev-tasks
I'll make a note for fido2, flask-marshmallow has not been updated by GDS so we may hold on
=> Bump dependencies on 2020-10-06

app/config.py
re #962 
Delete the environment variable SMS_INBOUND_WHITELIST instead of renaming it, as the code doesn't use it after it's set, and we don't set it locally or in staging or prod.
App seems to run fine locally without it.
=> delete unused environment variable SMS_INBOUND_WHITELIST

app/authentication/auth.py, app/dao/api_key_dao.py, tests/app/authentication/test_authentication.py, tests/app/dao/test_api_key_dao.py
This PR adds an alternative authentication mechanism to JWT tokens: API keys only. It's limited in scope for now:
- we don't advertise it so we don't change error messages for now
- it's backend only, no UI changes
- it's not straightforward to get only your API key from the UI for now (as we display key name + service ID + key)
To test it locally:
- create an API key, keep only the API key part (the displayed key is `key_name-service_id-api_key`
- hit an endpoint where you need an API key, for example, `curl -H 'Authorization: ApiKey-v1 $api_key' http://localhost:6011/notifications`
Authentication is well covered by tests. `pytest -k 'test_authentication.py' --maxfail=1 --ff -v` reports 40 tests executed.
Trello card: https://trello.com/c/xXoa6LwD/83-spike-what-is-needed-to-remove-jwt-fro …
=> Auth with API key only

app/dao/fact_notification_status_dao.py, app/service/rest.py, tests/app/dao/test_fact_notification_status_dao.py
Needed by the new activity dashboard.
Would be good to ship before https://github.com/cds-snc/notification-admin/pull/810 so that the review app could call the new endpoint
=> Endpoint to get delivered notifications stats by month

app/delivery/send_to_providers.py, tests/app/delivery/test_send_to_providers.py
If we want to track delivery statuses for SNS and Pinpoint, we should store the AWS ID in the `Notification` model, in the `reference` column. AWS will include this ID in the callback later and we'll use this information to update the notification status.
SNS and Pinpoint clients already return this ID, we need to store it.
https://github.com/cds-snc/notification-api/blob/6781341dfe03a26ac145228265517ab8b62d5f15/app/clients/sms/aws_sns.py#L53
https://github.com/cds-snc/notification-api/blob/6781341dfe03a26ac145228265517ab8b62d5f15/app/clients/sms/aws_pinpoint.py#L96
The code is very similar to the email part
https://github.com/cds-snc/notification-api/blob/6781341dfe03a26ac145228265517ab8b62d5f15/app/delivery/send_to_providers.py#L176-L186
=> Store the provider's ID when sending SMS

app/clients/sms/aws_sns.py
This will only affect staging as production is on `us-east-1` at the moment.
Checked that pods in staging and production have the expected value for this env variable
=> Change AWS region for SNS

app/celery/tasks.py
Follow-up of https://github.com/cds-snc/notification-api/pull/1169
The Celery task was not properly registered. Importing the file does the trick ✨
=> Celery: register process_sns_receipts_tasks

app/__init__.py, app/celery/process_ses_receipts_tasks.py, requirements-app.txt, requirements.txt, tests/app/celery/test_process_ses_receipts_tasks.py
Callbacks go through SNS and not HTTP anymore. Delete these HTTP endpoints and clean out unused code 🧹
=> Remove HTTP callbacks for SES

app/dao/notifications_dao.py, app/platform_stats/rest.py, tests/app/dao/notification_dao/test_notification_dao.py, tests/app/dao/test_fact_notification_status_dao.py, tests/app/platform_stats/test_rest.py
New API endpoint to build API keys report (know which services use the admin VS the API).
Trello card: https://trello.com/c/dFATfrV6/114-new-report-api-key-send-vs-ui-send
=> Send methods stats by service endpoint

README.md
* Added how to create the *postgres* user if not already existing. 
* Removed a few unnecessary env var setup from the shell profile instructions for `virtualenvwrapper`. It seems these were copied from its documentation but are only useful in the context of the tool's example. Please see: https://virtualenvwrapper.readthedocs.io/en/latest/
=> docs: Added more details for the postgres setup

docker-compose.yml, local/Dockerfile, local/initdb/notify-db-entrypoint.sh, local/scripts/notify-web-entrypoint.sh
The `docker-compose up` series of commands did not work from a fresh installation. The database especially was missing creation and the `flask db upgrade` command. This should fix it.
I created new files in the `/local` folder. I didn't want to touch the existing Docker files in `/ci` as at least one is used by the GitHub workflows. 
So now a command such as `docker-compose up web` should bring the necessary ecosystem to work in tandem with the notification-admin project for example.
=> fix: repaired the docker-compose up setup

docker-compose.yml, local/scripts/notify-worker-entrypoint.sh
The celery binary was not installed anymore in the workers defined in the docker-compose.yml file. This might have been provoked by the latest changes I did, as I moved the pip install upon containers startup via entrypoint shell scripts. Hence simply adding entrypoint shell script for the workers was sufficient to fix this minor issue. 
Manually tested in my setup. Having the workers up and running allowed me to register locally in the setup as I received the expected registration emails.
=> fix: The celery dependency should be in the docker-compose workers

app/config.py, app/delivery/send_to_providers.py, app/user/rest.py, app/utils.py, migrations/versions/0312_update_branding_request.py, tests/app/delivery/test_send_to_providers.py, tests/app/test_utils.py
Edit the [branding request template](https://notification.alpha.canada.ca/services/d6aa2c68-a2d9-4437-ab19-3ae8eb202553/templates/7d423d9e-e94e-4118-879d-d52f383206ae) to remove the hardcoded S3 domain. Cleans up the `get_logo_url` method at the same time
Trello card: https://trello.com/c/5wylvewO/122-review-notify-templates-for-hardcoded-domains
=> Remove hardcoded domain from branding request

application.py, run_celery.py
Update Flask app names to have consistent StatsD prefixes.
The `NOTIFY_APP_NAME` is overridden to be set to the Flask app name here
https://github.com/cds-snc/notification-api/blob/8a1de76bd92ac20c08a2e1d953f2c8fba84d5c26/app/__init__.py#L75
This is then used by the StatsD client to create a namespace according to the environment and the application name
https://github.com/cds-snc/notification-utils/blob/72dea8e0bfe470a254655aef81d257d75a1f4b1d/notifications_utils/clients/statsd/statsd_client.py#L55-L58
Currently, this is a bit messy
- the `production` env is logged as `live` for the admin
- the app name is set to `app` instead of `api` for the API
Celery uses a different app name to distinguish API/Celery (this is the same codebase) …
=> Update Flask app name

README.md
Updated `.env` setup to latest practice. We don't use `gcloud` KMS storage anymore to store and setup our developers' environment variable.
=> fix: Rework doc section about gcloud env decryption

app/celery/provider_tasks.py, app/celery/tasks.py, app/config.py, app/delivery/send_to_providers.py, app/notifications/process_notifications.py, scripts/run_celery.sh, scripts/run_celery_sms.sh, tests/app/celery/test_provider_tasks.py, tests/app/celery/test_tasks.py, tests/app/notifications/test_process_notification.py, tests/app/test_config.py, tests/app/v2/notifications/test_post_notifications.py
Added a new SMS task, SMS will now be:
- unthrottled and handled by Celery workers if they are not sent using a specific phone number
- throttled system-wide at 1 SMS/s by a single SMS Celery worker if they are sent using a dedicated long code phone number
This introduces a new Celery task and a new queue but doesn't require Kubernetes changes.
The code changes aren't too bad but I really want to test this extensively in staging as it is critical.
=> Adjust rate limit for SMS

.github/workflows/docker.yaml
Same PR than https://github.com/cds-snc/notification-admin/pull/845 in admin
Changed the trigger condition to `push` to make sure that the CI job works as intended. API pods in staging run with Docker images pulled from AWS at the moment.
Gallery link: https://gallery.ecr.aws/v6b8u5o6/notify-api
=> Push Docker images to AWS ECR

app/celery/process_sns_receipts_tasks.py, tests/app/celery/test_process_sns_receipts_tasks.py, tests/app/db.py
Choose between delivered, temporary failure, permanent failure and technical failure for SNS delivery receipts
https://trello.com/c/PjWvWIOl/170-communicate-text-message-errors-to-the-ui-user-api-user
=> Better notification statuses for SNS text messages

README.md, app/notifications/validators.py, requirements-app.txt, requirements.txt, tests/app/conftest.py, tests/app/notifications/test_validators.py, tests/conftest.py
Review this PR in notification-utils as this PR relies on it:
https://github.com/cds-snc/notification-utils/pull/72
https://trello.com/c/62gscLJH/169-graph-the-services-going-over-the-daily-rate-limit
Added a statsd metric when daily rate usage of services have been reached.
* Added two tests covering the two scenarios of when the service rate is within and outside the limit.
=> feat: increment statsd counter when services reach daily limit

app/celery/provider_tasks.py
The SNS rate limit is set at 20 messages per second but we asked AWS for a limit increase.
As we run 6 Celery instances with 4 workers, we need to set a rate limit at the task level if
we want to avoid hitting rate limits per second on AWS, even with increased limits.
Follow up of https://github.com/cds-snc/notification-api/pull/1185
Slack thread for more details https://gcdigital.slack.com/archives/CNWA63606/p1607979769008500
=> Adjust Celery rate limit for deliver_sms

app/celery/process_ses_receipts_tasks.py
Put a temporary rate limit on the process-ses-result Celery task, in charge of dealing with delivery receipts from SES.
We saw that with the current production settings we can execute 10k/5 minutes of deliver_email and process-ses-result in parallel. If we reduce the rate of process-ses-result from 10k/5 minutes = 33.33 tasks/s to 12 tasks/s, we would have more ressources to deliver emails faster. The tradeoff is that delivery receipts will be delayed.
This is a temporary measure before putting horizontal scaling/database improvements in place in January 2021.
=> Temporary rate limit Celery process-ses-result task

app/celery/process_ses_receipts_tasks.py
Remove rate limit introduced today for the process-ses-result task
=> Remove rate limit for process-ses-result

app/config.py, tests/app/notifications/rest/test_send_notification.py, tests/app/notifications/test_process_notification.py, tests/app/v2/notifications/test_post_notifications.py
Use a canada.ca domain and not a gov.uk one. Aligns with [the documentation](https://github.com/cds-snc/notification-documentation/commit/7509df47cf00c161b2c2af037b27b91f82ce17f4).
We don't know anyone using these fake email addresses to perform tests at the moment (we never communicated these were available) so the change should not be a problem.
=> Update simulated email addresses

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .github/workflows/test.yaml, Makefile, README.md, ci/Dockerfile, ci/Dockerfile.test, local/Dockerfile, requirements-app.txt, requirements.txt, runtime.txt
Trello
https://trello.com/c/POlbTAih/238-prepare-the-upgrade-to-python-39
Upgrading app to python 3.9.1
This upgrade requires Kombu 5 which requires Celery 4+, we are opting to upgrade to celery 5x and some small dependency bumps.
Dockerfiles, CI and docs updated.
@AntoineAugusti suggesting to load test partly influenced from GDS decision to revert from Celery 4 to Celery 3: https://github.com/alphagov/notifications-api/pull/2142
Test plan:
Local:
* Tested API locally with ad-hoc and scheduled jobs OK
* Tested API locally with built Docker image with ad-hoc and scheduled jobs OK
* Local minor load testing OK
Staging:
* Gather baseline load testing data with various sustained loads (done, some data linked in Trello card)
* Other testing: …
=> Upgrade Python 3.9.1 plus celery 5x

app/user/rest.py
The contact page is not available at the URL `/support/ask-question-give-feedback` anymore for several months.
There is a redirection in place so the current link is not broken, fortunately.
https://github.com/cds-snc/notification-admin/blob/0237926c01c58d72a927e85aba58bb5b80dd20e9/app/main/views/contact.py#L155-L157
This PR is a small clean up.
Note that we don't have a clean and reliable way to link to the admin from the API as these are 2 different codebases. Maybe we'll move some URLs to the utils repo at some point? Food for thoughts.
=> feat: update contact page URL

app/celery/celery.py
Follow up of https://github.com/cds-snc/notification-api/pull/1209
Changed Celery settings name because those are going to be deprecated in 6.0. Config values stay in `app/config.py` but keys are remapped when passed to the Celery app.
Followed the documentation at https://docs.celeryproject.org/en/stable/userguide/configuration.html#new-lowercase-settings and warning messages when running Celery locally.
=> feat: use Celery lowercase settings

app/config.py, scripts/run_celery.sh, tests/app/test_config.py
At the moment, SES and SNS delivery receipts are routed to the `notify-internal-tasks` SQS queue. This queue is used by Notify to send Notify notifications (inception) and some Notify specific tasks.
Delivery receipts should not clog up this queue and should be prioritized accordlingly.
This PR introduces a new queue on the API, we will need to update our Terraform code afterwards to route messages to this new queue.
Terraform code:
- SES: https://github.com/cds-snc/notification-terraform/blob/517400d0c7513486530576c5f400cc3a22a360b3/aws/common/lambdas/ses_to_sqs_email_callbacks.py#L10
- SNS: https://github.com/cds-snc/notification-terraform/blob/517400d0c7513486530576c5f400cc3a22a360b3/aws/common/lambdas/sns_to_sqs_sms_callbacks.py#L64
Trello card: …
=> feat: add queue for delivery receipts

app/dao/api_key_dao.py
Run the method `get_api_key_by_secret` on reader instances as introduced in #1219
=> feat: run get_api_key_by_secret on reader instances

requirements-app.txt, requirements.txt
Reinstating boto dependency to address issues with Celery Pods in Staging
=> Dependency upgrade

requirements.txt
Revert the bump introduced in https://github.com/cds-snc/notification-api/pull/1229
=> feat: revert cryptography to 3.3.1

gunicorn_config.py
Lowered the value for `graceful_timeout` within gunicorn configuration. The default is `30` seconds but we set it at `20` seconds.
Following our recent incident which caused an increase of database connections to get past the RDS instance limit, our current theory is that as the kubernetes pods kept restarting the instances, these did not clean up resources including their database connections in a clean manner.
Lowering the gunicorn configuration value for `graceful_timeout` might provide a better heads up to the gunicorn workers to properly work out the clean up of resources. Because the previous default value of 30 seconds matched the exact value for kubernetes graceful pod timeout as well (i.e. `terminationGracePeriodSeconds`), which might not give the proper time for gunicorn to …
=> Avoid hard termination of API pods

app/celery/tasks.py, tests/app/celery/test_tasks.py
1) Reply to No-reply email from Notify
2) Check Freshdesk
- Email goes to the void
- People sending us their personal information
We worked recently on providing feedback for people replying to emails sent by Notify where services did not put a reply-to email address (see linked Trello card). This "no reply" email is sent by the GC Notify service and uses the default reply-to email address of this service, which goes to Freshdesk.
We've seen that some people reply to these emails and provide personal information, which is a privacy concern for us. **Make sure that we don't get these emails by changing the reply-to email address of these notifications only.** We can do this by setting the reply-to email address to the Notify service email address, [this is handled by our …
=> feat: remove reply-to for Notify no reply emails

.github/workflows/test.yaml, app/utils.py, tests/app/dao/test_ft_billing_dao.py, tests/app/test_utils.py
[Trello](https://trello.com/c/hOCUVQRc)
fix: localized naive time to GMT so that test would pass on Ubuntu and Mac OS
refactor: update cron timing
refactor: added typing information
refactor: split out the tests, date was both date and datetime type
refactor: renamed date to date_val because it was shadowing a parent date, worried about naming colision
1) With a Mac run `test_utils.py` manually and validate that the tests pass
2) Was able to copy and paste the code below into https://www.programiz.com/python-programming/online-compiler/ and validate that both on Mac (tested locally) and this platform (which I assume is a flavour of *nix) both give the right datetime for `local`
`local_timezone = pytz.timezone("America/Toronto")`
`val = datetime(2016, 1, 15, 0, 30, tzinfo=timezone.utc)` …
=> Fix overnight tests tz failure

app/authentication/auth.py, tests/app/authentication/test_authentication.py
JWT tokens are only valid for 30 seconds. When clients send requests to the Notify API, they can get a clock error, but it's a bit too generic to be helpful.
> Error: Your system clock must be accurate to within 30 seconds
This PR adds some logging, to be able to hunt down specific values in AWS log groups to have more evidence to help clients.
Trello card: https://trello.com/c/Mbkumte7/376-log-jwt-iat-field-value-to-ease-debugging-with-clock-errors
=> feat: log iat value to ease debugging with JWT tokens

app/__init__.py, tests/app/test_user_agent_processing.py
Fix a possible 500 error when people submit a custom user agent, starting with `notify` but with an unexpected format.
See occurence on Slack: https://gcdigital.slack.com/archives/CNWA63606/p1617214953097200
=> fix: handle hand crafted Notify user agents

app/service/rest.py, tests/app/service/test_rest.py
Remove the daily limit cache key from Redis when a service's message limit value is updated.
At the moment, if a service goes above its message limit and we update the message limit value, the cache may be used for up to 1h before expiring. This is not a great experience because if we change limits we want that to be reflected right rather than telling clients to wait for up to 1h.
https://github.com/cds-snc/notification-api/blob/3db95eb950de58faeecefe0818c95c7872863d1f/app/notifications/validators.py#L38-L44
You can check for other places where `daily_limit_cache_key` is used in this codebase to understand how it works.
Trello: https://trello.com/c/7VIM7U6r/419-delete-daily-limit-cache-when-updating-a-services-message-limit
=> feat: delete daily limit cache when updating limits

app/v2/notifications/post_notifications.py, tests/app/v2/notifications/test_post_notifications.py
Save stats when attachments are sent.
Store:
- number of attachments in the notification
- number of attachments sent on Notify
- number of attachments sent per service
- number of attachments sent per template
- number of attachments sent per sending method
- number of attachments sent per file type
- number of attachments sent per file size (1mb bucket size)
Uses MIME type and file size from https://github.com/cds-snc/notification-document-download-api/pull/35
Trello: https://trello.com/c/LJ3Ae6Of/422-store-stats-about-attachments
=> feat: save stats for attachments

app/clients/email/aws_ses.py, app/clients/email/sendgrid_client.py, tests/app/clients/test_aws_ses.py
Reword the SES logic to craft emails with attachments.
The logic:
- If sending a TXT email without attachments:
=> Multipart mixed
- If sending a TXT + HTML email without attachments:
=> Multipart alternative
- If sending a TXT + HTML email with attachments
=>  Multipart Mixed (enclosing)
- Multipart alternative (TXT + HTML)
- Attachment(s)
See AWS doc: https://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-email-raw.html#send-email-raw-mime
StackOverflow: https://stackoverflow.com/a/64174056
I'm sorry I didn't update tests but unfortunately test coverage is not good for this file: https://github.com/cds-snc/notification-api/blob/master/tests/app/clients/test_aws_ses.py. We don't test what's passed to AWS at the moment.
=> fix: appropriate mime type for emails with attachments

app/clients/email/aws_ses.py, tests/app/clients/test_aws_ses.py
Follow up of https://github.com/cds-snc/notification-api/pull/1260
Refactor + writing tests for 2 main cases:
- TXT + HTML, without attachments
- TXT + HTML + attachments
=> feat: write tests for AWS SES

app/clients/email/aws_ses.py, app/delivery/send_to_providers.py, tests/app/clients/test_aws_ses.py, tests/app/conftest.py, tests/app/delivery/test_send_to_providers.py, tests/app/v2/notifications/test_post_notifications.py
Add a `Content-Type` header when sending direct attachments with AWS SES.
It's recommend in [the documentation](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-email-raw.html#send-email-raw-mime) ("File attachments" section). Previously it was not set or AWS SES added a generic header like `Content-Type: application/octet-stream`.
Trello: https://trello.com/c/XzhQ42Jx/440-specify-content-type-when-sending-direct-attachments
=> feat: add content-type header for direct attachments

Makefile, app/status/healthcheck.py, tests/app/status/test_status.py
We do not use Travis, remove those fields from the Makefile and the healthcheck page https://api.notification.alpha.canada.ca.
They are creating confusion for developers.
=> Remove mention of Travis on healthcheck

app/notifications/validators.py, tests/app/v2/notifications/test_post_notifications.py
Fixing this because we had 500 errors in production.
According to the documentation, https://docs.python.org/3/library/base64.html
> A binascii.Error exception is raised if s is incorrectly padded.
Catching other exceptions as well.
=> feat: catch other exceptions for base64 decode

app/celery/tasks.py, app/delivery/send_to_providers.py, tests/app/celery/test_tasks.py, tests/app/delivery/test_send_to_providers.py
Add new StatsD metrics to help compute SLOs. Some SLOs were only computable using the Notify database, make sure that those metrics are available on CloudWatch to make it easy for us to consolidate metrics and create a CloudWatch dashboards for SLOs.
Adds:
- Delay to send emails (multiple categories with/without attachments are according to process type (normal/bulk/priority)
- Delay to send SMS (multiple categories according to process type)
- Delay for processed jobs (do those start on time)
[See SLOs](https://docs.google.com/spreadsheets/d/1fU-FJ7THfWEqNhbpQ4r22MQipFwC7SP851ZQnOf68cM/edit)
Trello: https://trello.com/c/GFHzZGgz/453-measure-slos-for-the-first-time
=> feat: new StatsD metrics to compute SLOs

app/celery/tasks.py, tests/app/celery/test_tasks.py
Fix a bug introduced in #1269, `scheduled_for` can be null if a job is not scheduled, which happens often.
=> fix: appropriate start date when recording stats for jobs

requirements-app.txt, requirements.txt
Adds:
- https://github.com/cds-snc/notification-utils/pull/77
- https://github.com/cds-snc/notification-utils/pull/78
=> Bump notification-utils to 43.6.0

app/celery/process_ses_receipts_tasks.py, app/celery/process_sns_receipts_tasks.py, app/celery/research_mode_tasks.py, app/clients/__init__.py, app/clients/email/aws_ses.py, app/dao/notifications_dao.py, app/notifications/notifications_ses_callback.py, tests/app/celery/test_process_ses_receipts_tasks.py, tests/app/clients/test_aws_ses.py, tests/app/notifications/test_notifications_ses_callback.py
Store better error messages for permanent or temporary failures on SES, in the `provider_response` field, as done recently for SNS https://github.com/cds-snc/notification-api/pull/1265
- Email address is on our email provider suppression list
- Email address is on the GC Notify suppression list
- Email was rejected because of its attachments
Trello: https://trello.com/c/HEZcloCO/460-better-error-messages-for-emails-in-case-of-failures
=> feat: add new error messages for SES

app/notifications/callbacks.py, tests/app/notifications/test_callbacks.py
We had a Celery error in production surfacing this bug. The bug's root cause is a typo, but it was not caught by tests.
Fixing the bug and adding tests as a result.
=> feat: add tests when generating callbacks

app/celery/provider_tasks.py, tests/app/celery/test_provider_tasks.py
Logging an exception counts as an error, while those things are "normal".
Happens in production at the moment when an email address contains accents, SES does not support email addresses with accents.
See https://gcdigital.slack.com/archives/CNWA63606/p1619182249228800
=> fix: adjust log level when email address is invalid

app/authentication/auth.py, tests/app/authentication/test_authentication.py
Fix a 500 error in production we just had where the `iat` value is not an integer.
=> feat: handle invalid iat value for JWT tokens

app/celery/tasks.py, tests/app/celery/test_tasks.py
Follow up of https://github.com/cds-snc/notification-api/pull/1268
Jobs (emails/SMS sent after uploading a spreadsheet on the admin) did not call the method in charge of checking the daily limit and sending warning emails if required.
Jobs already have a logic to not send notifications if the batch will go over limits
https://github.com/cds-snc/notification-api/blob/ed6d869f29914df7d7ab9ffe081b18a2b1944205/app/celery/tasks.py#L182-L194
And they also call `persist_notification` which increases the daily limit 
https://github.com/cds-snc/notification-api/blob/ed6d869f29914df7d7ab9ffe081b18a2b1944205/app/notifications/process_notifications.py#L114-L116
but checking the current usage against the limit and sending warning notifications if required was not done. Did that for emails, SMS (and …
=> feat: check jobs against the daily limit

app/celery/process_ses_receipts_tasks.py, tests/app/celery/test_process_ses_receipts_tasks.py
At the moment if we receive multiple delivery receipts for a notification, we ignore new delivery receipts. This is not okay as sometimes email bounce after we receive a delivered callback.
The [SES documentation](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/notification-contents.html) says that
> You might receive multiple types of Amazon SNS notifications for one recipient. For example, the receiving mail server might accept the email (triggering a delivery notification), but after processing the email, the receiving mail server might determine that the email actually results in a bounce (triggering a bounce notification). However, these are always separate notifications because they are different notification types.
Make sure we store the latest known state.
Example message:
> …
=> feat: process multiple SES receipts if needed

app/notifications/validators.py, app/v2/errors.py, tests/app/notifications/test_validators.py
Raise a different exception when services go over the daily limit, according to their service type (trial or live service).
This will enable us to have a warning alarm only for live services and not for trial services anymore.
At the moment we use a log line to raise the alarm, will switch to StatsD counters afterwards (see https://github.com/cds-snc/notification-terraform/pull/101 and https://github.com/cds-snc/notification-terraform/pull/108)
=> feat: split daily limit errors according to service type

app/service/rest.py
Rework https://github.com/cds-snc/notification-api/pull/1298
Got the following stracktrace in production
```
File "/app/app/service/rest.py", line 280, in update_service
dao_update_service(service)
File "/app/app/dao/dao_utils.py", line 13, in commit_or_rollback
res = func(*args, **kwargs)
File "/app/app/dao/dao_utils.py", line 58, in record_version
raise RuntimeError((
RuntimeError: Can't record history for Service (something in your code has casued the database to flush the session early so there's nothing to copy into the history table)
```
seems like sending notifications before updating the service flushes the session and then this exception is thrown. It's a shame we didn't get it in tests, because the call to `send_notification_to_service_users` is mocked.
Moved the service update …
=> fix: update service before sending notifications

requirements-app.txt, requirements.txt
Same as https://github.com/cds-snc/notification-admin/pull/1043
Will replace the hash with the version once the utils PR is merged and tagged
=> Bump utils to 43.11.0

app/models.py, tests/app/test_model.py
1) Sent an SMS to a CA number
2) Go to the list of notifications in the UI
3) Status show "Sent internationally" instead of "Sent"
Example URL https://notification.canada.ca/services/de598a67-4bf1-4ea0-b515-8014c36b4734/download-notifications.csv?message_type=sms&status=sending%2Cdelivered%2Cfailed
Status is "Sent"
Trello: https://trello.com/c/VWLjKJwr/678-reports-show-sent-sent-internationally-for-sms
=> fix: appropriate status for sms in reports

requirements-app.txt, requirements.txt
Release a fix to the FR GoC logo height for emails sent. https://github.com/cds-snc/notification-utils/pull/87
Email previews are not affected.
Trello: https://trello.com/c/EogJwolN/550-french-branding-is-stretched-tall
=> Bump utils to 43.11.1

app/celery/provider_tasks.py
Recent incident around AWS SMS rate exceeded in the us-west-2 region [forces us to slow down the rate of throttled SMS notifications](https://trello.com/c/XYrM21iF/582-sms-rate-incident-resolutions-for-2021-06-23) at 1 request / 2 seconds. This is a quick fix until we have a long term one. That will provide stability over speed which our clients would prefer when sending notifications.
I will perform a few local tests on Friday morning before any merge if approved.
* Send a batch of texto using a simulated long numbers
* Check the log for the message `POST simulated notification for id` and its frequency to every 2 seconds.
* The notification should be persisted too, despite not being sent. Hence we can check for the notifications in the database and look for the `notifications.sent_at` …
=> fix: slow down the rate of throttled SMS

app/celery/tasks.py, tests/app/celery/test_tasks.py
https://trello.com/c/Ijn2D73k/576-bulk-api-follow-up-improve-how-sender-id-is-passed
We moved `sender_id` into the job object, so we don't need to pass it around as a kwarg.
Notes:
Currently `process_job()` is only called in
- `run_scheduled_jobs()`
- `create_job()`
- `create_bulk_job()`
Note that it is never called with a `sender_id`. 
In `process_job()` we just use `sender_id` to send to `process_row()`. Since it gets the job, we can pull out the `sender_id` there instead of passing it in.
`process_row()` is called in
- `process_job()`
- `process_incomplete_job()`
In `process_incomplete_job()`, `sender_id` is not set when `process_row()` is called.
So we can stop passing `sender_id` around and set it in `process_row()`
Send some emails and make sure they go through?
In a given job, …
=> Stop passing around sender_id

app/delivery/send_to_providers.py
https://trello.com/c/vXs2FgT0/595-malware-checking-exploit-to-get-notifications-stuck-in-queue
App is trying to do malware scan when we don't want it to. I believe that the environment variable `MLWR_HOST` is a string, so its value of `"False"` is being evaluated as the boolean `True` in the `if` statement. Isn't Python grand?
Here we add a check that `https` is in `MLWR_HOST` to prevent such shenanigans.
Run this branch of api and notification-document-download-api locally, make sure that your service is allowed to send files, and do a curl such as
```
curl -i -X POST \
-H "Authorization:ApiKey-v1  *** API SECRET ***" \
-H "Content-Type:application/json" \
-d \
'{
"email_address": "*** your email address*** ",
"template_id": "*** TEMPLATE ID ***",
"personalisation": {
"some_file": { …
```
=> Only do malware scan if MLWR_HOST looks like a url

.github/workflows/build_and_push.yml
Most of this is copied from https://github.com/cds-snc/scan-websites/blob/main/.github/workflows/build_and_push.yml. All I did was copy in the name of our ECR repository in staging (`notify/api`) and set the branch name to "master".
This uses a new env variable that I haven't added yet: our aws account number (`AWS_ACCOUNT`).
I'm sure I missed some things so will keep this a draft for now.
=> Add a continuous deployment step for the lambda image

tests/app/celery/test_tasks.py
Added tests [around the changes](https://github.com/cds-snc/notification-api/pull/13590 that fixed the issue when cache would not properly load with a notification that had a sender ID defined.
Test the tests?
None.
=> Added tests around the cache not loading properly with reply address

app/notifications/validators.py, app/utils.py
https://trello.com/c/XXHbhWfq/688-validate-empty-sms-messages
Validate up front for empty sms messages sent through the api
Same instructions as for https://github.com/cds-snc/notification-api/pull/1372, but this time you'll get a `Bad Request` error when you post to the api, and no notification will be created.
None.
setup, …
=> Empty messages fail validation

.env.example, tests-perf/locust/locust-notifications.py, tests_smoke/smoke_test.py
[Trello card](https://trello.com/c/xkZD3br3/618-define-and-load-test-plans-api-bulk-api-in-staging)
This PR seeks to define load tests to test the one off email endpoint[1].
Prior to this, an example load tests already exists. This effort expands the one off email endpoint load test to cover attachment and link.
This choice is influenced by the already existing smoke tests for one off email.
Locust insists on have a task defined[2], which it uses to simulate the to run the task, this can be weighted which yields probable selection based on the weight.
The developers understand, would be that of isolated tasks that would run on their own greenlet(thread), hence this has led to the definition of separate class in order to achieve the aforementioned.
[1] \<domain>/v2/notifications/email
[2] …
=> [WIP] Define load tests for one off, bulk  email and SMS

.github/workflows/build_and_push_performance_test.yml, .github/workflows/performance.yml, tests-perf/locust/locust.conf, tests-perf/ops/Dockerfile
To get daily performance tests going, we have identified the need for a dedicated Docker file for this purpose.
This PR defines a new Docker file from which a runtime
Docker container will be created for usage in an AWS lambda.
With are defined the following environment variables:
- LOAD_TEST_PHONE_NUMBER
- LOAD_TEST_EMAIL
- LOAD_TEST_DOMAIN
- LOAD_TEST_SMS_TEMPLATE_ID
- LOAD_TEST_BULK_EMAIL_TEMPLATE_ID
- LOAD_TEST_EMAIL_TEMPLATE_ID
- LOAD_TEST_EMAIL_WITH_ATTACHMENT_TEMPLATE_ID
- LOAD_TEST_EMAIL_WITH_LINK_TEMPLATE_ID
- TEST_AUTH_HEADER
The aforelisted are used in [1], and these have been assigned for staging specific values.
Given the definition within the Docker file, these environment variables can overridden when this container is instantiated.
The performance tests defined in [1], …
=> Feature: Execute daily the performance tests

.github/workflows/lambda_production.yml, .github/workflows/lambda_staging.yml
```
tag invalid: The image tag 'latest' already exists in the 'notify/api-lambda' repository and cannot be overwritten because the repository is immutable.
```
We've marked the repo as immutable, so we can't change the image a tag refers to. This is probably a good thing. Also, since we're deploying by using the gitsha rather than `latest`, we don't need the `latest` tag.
None.
façon importante la …
=> bug fix: don't use latest tag for api lambda image

bin/execute_and_publish_performance_test.sh, tests-perf/locust/locust-notifications.py, tests-perf/locust/locust.conf, tests-perf/ops/Dockerfile
Related to https://github.com/cds-snc/notification-terraform/pull/317
Within this commit, we have defined a script that setups the performance test environment executes the performance test an publishes it to S3 bucket.
The run time duration has also been set to 5 minutes to discourage endless run of the performance tests
The s3 bucket is managed with a terraform script as defined here [1] and will be used to hold the performance test results per environment (production or staging).
[1] github.com/cds-snc/notification-terraform/pull/317
=> Publish performance test results

tests-perf/ops/Dockerfile
[Zenhub card](https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/183)
This PR increases the file descriptor maximum to 1000000, which is well above the 100000.
This PR is very experimental and seeks to test the viability of this within the AWS setup
```
cat /proc/sys/fs/file-max
```
Should return 100000
=> Performance tests: Increase the file descriptor maximum

app/celery/scheduled_tasks.py, tests/app/celery/test_scheduled_tasks.py
We bumped up the timeout from 30 minutes to an hour in #1375 but occasionally that's still not enough. As another quick hack let's bump it up to 2 hours.
After the current lambda / batch saving / perf testing we should fix this properly as discussed in https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/79
None. …
=> timeout jobs after 2 hours rather than 1

.github/workflows/test.yaml, tests/app/dao/test_services_dao.py
Basically, there's a test `test_create_service_and_history_is_transactional` that makes sure that creating a service without a name raises an error. Remotely we expect the error message to be
```
column "name" violates not-null constraint
```
and locally we expect
```
column "name" of relation "services_history" violates not-null constraint
```
Updating the version of postgresql in the action (and updating the test to the new error message) resolves the issue.
Run the tests locally!
None.
fonctionnalité …
=> pass tests locally and remotely

bin/execute_and_publish_performance_test.sh
[Zenhub card](https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/205)
Within we have added the --html flag that instructs the locust script to produce the performance test result in
html format.
This has been done so that the public facing url can quickly present its index html page for analysis via internet browsers.
Following this PR will be one that will expose a cloudfriont facade for the s3.
None.
=> Print out performance test result in html

heartbeat/heartbeat.py
Added better logs, error handing and an exit code.
Unfortunately, cannot check for response code as this is what the python client respond back:
```
{'content': {'body': 'This is the heartbeat test message.\r\n\r\nCeci est le test de battement de coeur pour Notify.', 'from_email': 'gc.notify.gc.notification@notification.canada.ca', 'subject': 'Heartbeat-test'}, 'id': '8e17b953-4b00-4b26-974c-3f153032f9aa', 'reference': None, 'scheduled_for': None, 'template': {'id': '7daa4f22-633b-4a7b-8b20-dfc5f66882bd', 'uri': 'https://api-lambda.notification.canada.ca/services/d6aa2c68-a2d9-4437-ab19-3ae8eb202553/templates/7daa4f22-633b-4a7b-8b20-dfc5f66882bd', 'version': 2}, 'uri': 'https://api-lambda.notification.canada.ca/v2/notifications/8e17b953-4b00-4b26-974c-3f153032f9aa'}```
=> Add more heartbeat log

application.py
[Zenhub card](https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/238)
Following on from PR #1420, we have decided to invoke register application to help register the our Lambda based notify applications.
This effort is experimental especially with the conditions highlighted in the activate application code [1], which is invoked by register_application [2].
[1] https://github.com/newrelic/newrelic-python-agent/blob/f99da493986f24a588af50e197bbe62f5ad6332a/newrelic/core/agent.py#L298
[2] https://github.com/newrelic/newrelic-python-agent/blob/f99da493986f24a588af50e197bbe62f5ad6332a/newrelic/api/application.py#L169
review | Voici une suggestion de liste de …
=> Experimental: Invoke New Relic's `register_application`

app/celery/tasks.py
Bug in the code:
```
Field | Value
-- | --
@ingestionTime | 1642176021240
@log | 239043911459:/aws/containerinsights/notification-canada-ca-staging-eks-cluster/application
@logStream | celery-675d96fc56-mbhdp_notification-canada-ca_celery-075a31b6158e89c90093b19e1cf60e01f210e93ae407abfd5d12791976218530
@message | {"log":"[2022-01-14 16:00:14,745: ERROR/ForkPoolWorker-2] Task save-emails[aedbcf53-3eac-4130-8702-400ee4beabf2] raised unexpected: UnboundLocalError(\"local variable 'reply_to_text' referenced before assignment\")\n","stream":"stderr","docker":{"container_id":"075a31b6158e89c90093b19e1cf60e01f210e93ae407abfd5d12791976218530"},"kubernetes":{"container_name":"celery","namespace_name":"notification-canada-ca","pod_name":"celery-675d96fc56-mbhdp","container_image":"public.ecr.aws/cds …
```
=> default value for reply_to_text

app/models.py, migrations/versions/0326_add_queue_notifications.py, tests/app/conftest.py, tests/app/db.py, tests/app/test_model.py
We are going to store the name of the queue we send the notification to in the notifications table.
Code was tested by running `flask db upgrade`
```
Table "public.notifications"
Column        |            Type             | Collation | Nullable | Default
---------------------+-----------------------------+-----------+----------+---------
id                  | uuid                        |           | not null |
to                  | character varying           |           | not null |
job_id              | uuid                        |           |          |
service_id          | uuid                        |           |          |
template_id         | uuid                        |           |          |
created_at          | timestamp without time zone |           | not null |
sent_at …
```
=> Add queue_name for notifications table

app/notifications/process_notifications.py, app/v2/notifications/post_notifications.py, tests/app/notifications/test_process_notification.py, tests/app/v2/notifications/test_post_letter_notifications.py, tests/app/v2/notifications/test_post_notifications.py
https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/149
Split `persist_notification()` into two functions (note: keeping the original there as well):
- `transform_notification()` that takes the same params as `persist_notification()` and returns a notification
- `db_save_notification()` which saves a notification to the database
Change the `/v2/notifications/email` and `/v2/notifications/sms` endpoints to use the two new functions instead of `persist_notification()`.
This will allow us to next replace `db_save_notification()` with something that pushes the notification to redis.
tested locally by posting to the `/v2/notifications/email` and `/v2/notifications/sms` endpoints
None. (in particular, we are still doing the same steps, …
=> batch saving: split up persist_notification function

scripts/run_tests.sh, tests/app/test_utils.py
Execute tests that will be tagged with the `@pytest.mark.serial` annotation without concurrent test workers. The goal is to tag the upcoming tests around the `RedisQueue` implementation with these to avoid concurrent access to the fixture cache database.
Watching for the GitHub pipeline and make sure nothing breaks.
None. …
=> Serial exec for tests

app/celery/tasks.py, app/dao/services_dao.py, tests/app/dao/test_services_dao.py
Refactored the `dao_fetch_service_by_id` function to remove the `tuple[Service, Dict]` return, because the `dict` return reflects exactly the same as the `Service` as the latter was created from the former. Inspection of the code shows that the `dict` return is not actually used anywhere.
Regression tests should cover usage and calls of this refactored function.
None. …
=> Refactored dao_fetch_service_by_id without tuple return

.devcontainer/devcontainer.json, .devcontainer/docker-compose.yml, .devcontainer/scripts/notify-dev-entrypoint.sh, README.md
Use the postCreateCommand in devcontainer.json to finish
the devcontainer init.
Also updates the README with instructions on how to get
started using the devcontainer.
The updated README section I've added looks like so:
https://github.com/cds-snc/notification-api/blob/fix/devcontainer-entrypoint/README.md#in-a-vs-code-devcontainer
=> fix: update how devcontainer is initialized

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/scripts/notify-dev-entrypoint.sh
Add kubectl, [kubectx](https://github.com/ahmetb/kubectx/) and command auto-complete to
the devcontainer.  This lets us monitor how the cluster
is behaving during API performance testing.
Also adds the [GitHub Copilot](https://copilot.github.com/) VS Code extension.
=> feat: add kubectl to devcontainer

.github/workflows/test.yaml, pytest.ini, tests/conftest.py
Add pytest logging for the `notify_db` fixture creation.  A `pytest.{worker_id}.log` file will be created for each worker and saved as a GitHub workflow artifact if the tests fail.
* cds-snc/notification-planning#389.
=> feat: add pytest logging to tests

tests-perf/locust/locust-notifications-with-bounce.py
Add a performance test that supports a `PERF_TEST_BOUNCE_RATE`
environment variable (value between 0 and 1) that determines the
percentage of requests that will be delivered to the
`PERF_TEST_EMAIL_BOUNCE` email address.
All other emails will be sent to the `PERF_TEST_EMAIL_SUCCESS`
email address.
* cds-snc/notification-planning#412
=> test: locust performance test with bounce rate

tests-perf/locust/locust-notifications-with-fail.py
This causes the performance to randomly select 1 of 4 different
email fail types.
* cds-snc/notification-planning#412
=> test: add multiple different fail email types

app/dao/notifications_dao.py, tests/app/dao/notification_dao/test_notification_dao.py
When we have a list of notifications and we use the bulk save functionality, if there are duplicate IDs, we should throw an error.
The code in this PR adds error handling and a test to handle the above scenario.
=> Bulk Notification Insert : Add test for duplicate ids

migrations/versions/0325_set_transaction_timeout.py, pytest.ini, tests/conftest.py
By default an `ALTER ROLE` statement applies to all databases on a server.  This was causing a race condition in the unit tests which run in multiple worker processes, each with their own database on the same PostgreSQL server.
Adding the `IN DATABASE` clause limits the `ALTER ROLE` to only apply to the database the migration is running against and removes the race condition.  More detail has been added in the [related issue comment](https://github.com/cds-snc/notification-planning/issues/389#issuecomment-1046256266).
This fix also removes the pytest logging configuration which had been added to help diagnose the issue.
* cds-snc/notification-planning#389
=> fix: limit ALTER ROLE migration to target database

app/aws/metrics.py, app/config.py
Currently the CloudWatch embedded metrics are being incorrectly being processed by the agent due to the logs being sent to the STATSD port. This PR will submit logs to the correct CloudWatch agent service residing on default port `25888`
=> fix: use default cloudwatch emf service port

app/aws/metrics.py, app/aws/metrics_scope.py, app/queue.py, tests/app/aws/test_metric_scope.py
Bringing in the metrics_scope from the aws projects so that we can manage the async aspects of the aws embedded metrics.
=> feat: use custom metrics_scope to manage async metrics

.devcontainer/devcontainer.json
The devcontainer is currently using docker compose to create the necessary infrastructure for local development, however the devcontainer persists even after the container is exited.
Configuring a `shutdownAction` will ensure vscode performs a `docker-compose down` when vscode is exited.
=> feat: stop devcontainer on exit

app/__init__.py, app/aws/metrics.py, tests/app/aws/test_metrics.py
Failures related to logging metrics should not generate error logs, instead we'll generate warnings going forward.
=> chore: dont log errors on metrics failures

.devcontainer/Dockerfile, .devcontainer/devcontainer.json
Octant provides a dashboard that makes it easier to manage
Kubernetes workloads.
This change also re-organizes package installs and uses
devcontainer `features` to install kubectl and helm.
=> feat: add Octant to devcontainer

app/aws/metrics.py, app/aws/metrics_logger.py, app/config.py, pytest.ini, tests/app/aws/test_metric_logger.py, tests/app/aws/test_metrics.py
CloudWatch metrics will not be managed via environment variable. Default to `disabled` if the environment variable is not present.
=> feat: ability to toggle metrics via env

app/queue.py, tests/app/test_queue.py
Currently metrics are being generated without checking if the redis queue poll returned results. This is resulting in metrics being inaccurate. This PR introduces an evaluation of whether the queue returned data before logging a metric.
**note:** `test_should_send_personalised_template_with_html_enabled` test will fail since validator.w3.org is currently offline and is required by the library that validates html templates.
=> feat: check if redis poll returned results

app/clients/zendesk.py, tests/app/clients/test_zendesk.py
The zendesk client was originally developed to interact with the zendesk `ticket` api. Unfortunately that endpoint is only available for authenticated users. This went undetected during development since all test emails originated from users with zendesk accounts.
Migrating to use the `requests` api allows for tickets to be associated with users without zendesk accounts.
=> feat: migrate to requests endpoint for zendesk

app/celery/tasks.py
Do not log a handled exception as an exception as this will trigger the celery workers to report and page support. Notifications that hit integrity errors on the batch code path will be redirected to the individual saving code path (if not already existing in the database). If these fail again, that will get reported. 
setup, …
=> Less noise around errors that are recovered from

.devcontainer/devcontainer.json, app/__init__.py, app/config.py, tests/app/test_config.py
This config logging can be used to troubleshoot app init problems and confirm
that future changes to how environment variables are set work as expected.
As part of this change, a list of sensitive config keys has also been
defined to avoid leaking secrets in the app logs.
* cds-snc/notification-planning#421
=> feat: add config logging during app initialize

Makefile, README.md, docker-compose.yml, scripts/run_app.sh
Add a Makefile `run` target to start the app locally.  This change was driven by me getting tried of copy/pasting the command out of the README.
=> feat: add `make run` to start app locally

.devcontainer/docker-compose.yml, app/celery/tasks.py, app/config.py, app/v2/notifications/post_notifications.py, pytest.ini, tests/app/delivery/test_send_to_providers.py, tests/app/v2/notifications/test_post_notifications.py
We had a problem where if the service was in `Trial` mode, we would not send a notification either through the bulk API or the individual post API. This was due to the fact that we were checking if `we could send the notification` with the wrong API key type (we hardcoded the Normal key type flow instead of using the Team key type flow). 
We moved the check of whether a service can send a notification or not into the API layer from the celery layer.
=> Remove check where service can send a notification from Celery and move it to API.

bin/sync_lambda_envs.sh
Update to use `export` directly to export the environment variables
into the Lambda's execution environment.
* cds-snc/notification-planning#421
=> fix: use `export` instead of `eval`

tests/app/test_config.py
Update the unit test with the missing `test_` prefix so that it
runs as part of the test suite.
* cds-snc/notification-planning#421
=> fix: add missing `test_` prefix

.github/workflows/lambda_staging.yml
This PR will prevent the lambda cli commands from dumping their outputs to the workflow logs.
=> fix: send AWS lambda function update to /dev/null

.github/workflows/lambda_production.yml, .github/workflows/lambda_staging.yml, .gitignore, bin/get_newrelic_layer.sh, ci/Dockerfile.lambda
This PR modifies the handler that will be invoked at runtime to the newrelic lambda handler. This handler will hook into the appropriate python modules and then invoke the handler specified in the environment variable `NEW_RELIC_LAMBDA_HANDLER` which is currently set to `application.handler`. This will give the newrelic agent access to the flask stdout and stderr for automatic metric logging.
Summary of changes
- Retrieve the required newrelic lambda layer from aws (ci)
- Install `libc6-compat` so that the necessary link libraries are available to the newrelic agent (dockerfile)
- Install `newrelic-lambda` to send logs directly to newrelic  (dockerfile)
- add `/opt/python/lib/python3.9/site-packages` to the containers pythonpath so that the newrelic wrapper is available  (dockerfile)
- …
=> feat: new relic lambda wrapper

app/config.py, requirements-app.txt, requirements.txt, tests/app/test_config.py
Use the Notification Utils `logging.get_class_attrs` to log the API's
config on startup.
* cds-snc/notification-planning#522
=> chore: switch to notification_utils config logging

app/dao/notifications_dao.py
Update `get_notification_with_personalisation` to improve logging.
This will be used to help troubleshoot the issue we're seeing where
the number of `No row was found for one()` warnings returned seems
high for the Lambda API.
* cds-snc/notification-planning#537
=> fix: improve logging for get notification by ID

app/dao/notifications_dao.py, tests/app/dao/notification_dao/test_notification_dao.py
Update the logging added to `get_notification_with_personalisation`
so that it only logs the query filters if a NoResultsFound exception
is raised.
* #1514
* cds-snc/notification-planning#537
=> fix: only log when no notification found

app/dao/notifications_dao.py
Update `get_notification_with_personalisation` exception
logging to include the stack trace.
* #1514
=> fix: add stack trace when NoResultsFound

app/dao/notifications_dao.py
Update `get_notification_with_personalisation` to print the full
invocation stack rather than the stack trace.
Using `traceback.format_exc()` was only giving the stack trace
from within the `try/except` block:
```python
Traceback (most recent call last):
File "/app/app/dao/notifications_dao.py", line 207, in get_notification_with_personalisation
return Notification.query.filter_by(**filter_dict).options(joinedload("template")).one()
File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3500, in one
raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
```
* #1514
* #1516
=> fix: print the invocation stack

migrations/versions/0420_add_redacted_template.py
We need a row for every template in the `template_redacted` table. This adds it for the forced password email template
=> Add redacted template

application.py, mypy.ini, requirements-app.txt, requirements.txt
Switch to the [`apig_wsgi` module](https://github.com/adamchainz/apig-wsgi), which provides support for multiple
GET parameters using the same name.  
This fixes the error we were seeing retrieving recent notifications for a 
service where the `status` URL parameter is passed more than once 
in the request.
* cds-snc/notification-planning#635
=> fix: multi-value param support for the Lambda API

app/v2/notifications/post_notifications.py
Ran this locally:
```
2022-05-03T18:19:53 api api INFO None "Trying to send notification for Template ID: 41e5b0bb-3d4f-42b0-ad6d-0be9c4ac8a77" [in /workspace/app/v2/notifications/post_notifications.py:202]
```
We are doing this so we can tell users which Templates are causing API key failures.
=> Add logging for template ID

.github/workflows/docker.yaml, .github/workflows/generate_sbom.yml, .github/workflows/lambda_production.yml
Add GitHub workflows to generate SBOMs and upload them
to Dependency-Track. This will allow us to have a view of all
the dependencies used by the org and their potential
vulnerabilities.
* cds-snc/platform-sre-security-support#94
=> feat: generate Software Bill of Materials

app/__init__.py, app/celery/scheduled_tasks.py, app/celery/tasks.py
We need to add code so that while there is data in the sms
and email queues, it still gets processed. No new data will be
added to those queues
I will test this on staging once merged
Butlocally
I switched off the feature flag and watch the queue get drained.
There was nothing left to acknowledge or expire in the old queue, but the old queues will stick around and will need to be removed after go-live
=> Add code for inbetween phase

app/config.py, app/notifications/validators.py, tests/app/v2/notifications/test_post_notifications.py
Added a file size validation on attachments, around 120k for now by default. This value can be overridden via the `ATTACHMENT_SIZE_LIMIT` environment variable. The 120k default limit might still be too high if two attachments of 119k would come in the same batch, but it offers for now a sensitive limit and highly reduce the risk as usually, high size attachments get way beyond.
If a client to the Notify API get past the attachment size limit, they will be met with a `400` HTTP status code just like any other validation error that can occur on personalisation data or other schema related check ups. The error describes which file by name got past the limit, mentioning the allowed limit and the actual size of the file.
New automated tests were added with file size larger to the allowed limit …
=> Apply attachment size limit on incoming notifications

Makefile, app/__init__.py, app/aws/metrics.py, app/celery/scheduled_tasks.py, app/celery/tasks.py, app/config.py, app/v2/notifications/post_notifications.py, pytest.ini, tests/app/aws/test_metrics.py, tests/app/celery/test_scheduled_tasks.py, tests/app/celery/test_tasks.py, tests/app/notifications/test_process_notification.py, tests/app/v2/notifications/test_post_notifications.py
Remove all code paths related to the below 4 configs being set to False:
1.     FF_NOTIFICATION_CELERY_PERSISTENCE = env.bool("FF_NOTIFICATION_CELERY_PERSISTENCE", True)
2.     FF_BATCH_INSERTION = env.bool("FF_BATCH_INSERTION", True)
3.     FF_REDIS_BATCH_SAVING = env.bool("FF_REDIS_BATCH_SAVING", True)
4.     FF_PRIORITY_LANES = env.bool("FF_PRIORITY_LANES", True)
The above 4 are true in prod.
This PR removes all extra code paths that occur when the above configs are `False`.
Tested by running unit test manually. Will further tests when on staging.
=> Remove old code paths - all feature flags (FF_*)

app/dao/notifications_dao.py, app/dao/service_user_dao.py, app/dao/templates_dao.py, app/models.py, app/template/rest.py, app/user/rest.py, requirements-app.txt, requirements.txt, requirements_for_test.txt, tests/app/dao/test_invited_user_dao.py, tests/app/dao/test_services_dao.py, tests/app/dao/test_templates_dao.py, tests/app/template/test_rest.py
Finish upgrading pytest to 5.3.2 (and others required)
Started the process in https://github.com/cds-snc/notification-api/pull/1564
Fixes largely copied from https://github.com/alphagov/notifications-api/pull/3228
Smoke test (in particular admin), specifically around the code this PR touched:
- `ServiceUser` and `ServicePermission`:
- add a user to a service
- change the user's permissions
- remove the user from the service
- archiving  templates:
- Make a template in a folder
- See it in the `template_folder_map` table
- Delete the template
- Ensure that in the `templates` table it has `archived = True`
- Ensure that it is no longer in the `template_folder_map` table
- query change in `delete_notifications_older_than_retention_by_type` and change to `insert_update_notification_history`: …
=> Upgrade Pytest to 5.3.2

app/__init__.py, app/authentication/auth.py, requirements-app.txt, requirements.txt, requirements_for_test.txt, tests/app/authentication/test_authentication.py
Updates API to werkzeug 2.0.2.
This required a small refactor of part of the app that used Flask internals directly (`authentication/auth.py` and `app/__init__.py`):
- Stop using `flask._request_ctx_stack`; instead use`flask.g`
=> Upgrade to werkzeug 2.0.2

app/v2/notifications/get_notifications.py, requirements-app.txt, requirements.txt, requirements_for_test.txt, tests/app/service/test_rest.py, tests/app/v2/test_errors.py
This PR upgrades:
- Flask to 2.0.3
- itsdangerous to 2.0.1
- locust (for testing) to 2.10.0
- the `send_file` method renamed the parameter `filename_or_fp` to `path_or_file`
=> Upgrade flask to v2 (api)

tests/app/v2/notifications/test_post_notifications.py
Finish up https://github.com/cds-snc/notification-planning/issues/29: Add a few tests that we deleted in #1570 around not sending using a team key if the recipient isn't on the team.
Essentially, parametrized the existing happy-path tests to also test cases where sending is not allowed.
=> add tests for team key with recipient not allowed

app/celery/tasks.py, tests/app/celery/test_tasks.py
We were incorrectly sending a list object to `send_notification_to_queue`. We fixed this and also cleaned up some logs we had added while debugging why this function wasn't working as expected.
=> Fix send-notify-no-reply

app/celery/tasks.py, tests/app/celery/test_tasks.py
This PR fixes the issue where notify was ignoring the key_type for bulk sends using a testing API key.  Now, when the notification is signed after being posted, the key_type is correctly carried over.
=> Re-create key_type prop when signing notifications.

.github/workflows/build_and_push_performance_test.yml, .github/workflows/lambda_production.yml, .github/workflows/lambda_staging.yml, .github/workflows/s3-backup.yml
We already use a Slack webhook to notify us if deploying to staging k8s fails - here we also add to the other actions.
None.
=> add slack alert for failing github actions

requirements-app.txt, requirements.txt
This PR bumps the notification-utils version to make use of the lang tag fixes from https://github.com/cds-snc/notification-utils/pull/129
This PR should be deployed along with:
- https://github.com/cds-snc/notification-admin/pull/1330
=> Bump notification-utils to 48.2.0

app/celery/tasks.py, app/notifications/rest.py, app/notifications/validators.py, app/service/send_notification.py, app/v2/notifications/post_notifications.py, tests/app/notifications/test_validators.py, tests/app/service/test_send_one_off_notification.py
There were several places that we were calling `check_service_over_daily_message_limit` that we weren't calling `check_service_over_daily_sms_limit`. This PR fixes that.
Basically, whenever you send an sms for the first time in a day, you should see the redis counter `sms-<service_id>-date-count` created.
(example: `sms-3ae2fb6a-bec7-47d6-8f8b-36e2519f7c6d-2022-09-27-count`)
None.
=> fix/check daily_sms_limit wherever we check daily_message_limit

scripts/run_celery_exit.sh
There were two bugs in the celery exit script.
1. The PIDs on the kube setup show up in the first column (locally it shows up in column 2)
2. I was only printing (🤦🏽 ) the kill command, I needed to execute it as well.
=> Fix issues regarding the celery script

app/celery/tasks.py
sends with `/sms` or `/bulk` that bring you up to your daily sms limit are created but not actually sent.
This is because we're checking **after** create the notifications and increment the daily sms counter - so the check finds that we're at the limit and fails. 
This PR removes that last check. Tested to ensure that 
- limit reaching sms go out correctly now
- we still block after reaching the limit.
There's another bug where we can hop over the limit sometimes, but that's dealt with in #1632 
What I did:
- Set sms limit to 6
- /sms one 2 fragment 
- 3 sent and received
- 4th blocked
- Reset sms limit to 10
- /bulk two 2 fragment sms - sent and received
- Another 2-2 : blocked
Another /sms one part: blocked
None.
=> fix/last sms / job reaching limit is stuck in limbo

mypy.ini, requirements_for_test.txt
I found another package with more type definitions for SQLAlchemy. This allows us to remove the "mypy ignore" setting for that import.
=> Added more type stubs/definitions for SQLAlchemy

migrations/versions/0424_sms_templates_in_redacted.py
https://github.com/cds-snc/notification-planning/issues/924
When we added the new SMS limit templates we forgot to add rows for them to the redacted table. This means that they cannot be edited 😞 
- `flask db upgrade`
- verify in `localhost:6011` that api sees that the database contains this migration
- can verify that the `template_redacted` table has the 3 new rows
- more to the point, verify that you can now edit and save the new SMS templates
None.
=> add new sms templates to template_redacted table

app/notifications/validators.py, tests/app/notifications/test_validators.py
This PR renames the statsd counter when the `LiveServiceTooManySMSRequestsError` and `TrialServiceTooManySMSRequestsError` errors are thrown so we can add alarms for sms daily limits going forward.
=> Update statsd counter name to differentiate from overall limit

app/service/rest.py
https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/949
We are sending the "sms limit updated" email when users go live in prod.
Tested locally:
- set `FF_SPIKE_SMS_DAILY_LIMIT` to false
- create a service, make it live
-  verify I don't get the "can send 1000 messages" email.
None.
=> fix: check FF before sending sms limit changed email

app/v2/notifications/post_notifications.py, tests/app/v2/notifications/test_post_notifications.py
Update the /bulk endpoint sms limit checking to use the shared logic.
This is a fix for a bug @andrewleith found where post requests to /bulk were not failing even though he had submitted more sms fragments for sending than his limit allowed. These SMS were stuck in sending.
=> Update the /bulk endpoint sms limit checking to use the shared logic

docker-compose.yml
This PR is to keep the docker image on the same version of redis as everything else.
=> fix(docker): pin redis to 6.2 to match staging/prod/devcontainer

app/celery/tasks.py, app/job/rest.py, app/notifications/validators.py, app/service/send_notification.py, app/v2/notifications/post_notifications.py, tests/app/notifications/test_validators.py, tests/app/service/test_send_one_off_notification.py
This to fix a bug Jimmy found where the SMS Limit related warning emails were not being triggered for a send via the Admin site.
The check we were performing (`check_if_request_would_put_service_over_daily_sms_limit`) did not include the logic to send the warning emails. I switched it to the other check function that is responsible for sending these emails:  `check_service_over_daily_sms_limit`.
See bug card.
=> Add the warning email trigger to the csv send via admin codepath

tests/app/v2/notifications/test_post_notifications.py
This PR adds 10 additional test cases for the SMS parts limits feature.  
- One-off API sends warning email, limit reached email, and blocks sends
- One-off API won't hop over limit using 3-fragment sms
- Bulk API sends warning email, limit reached email, and blocks sends
- Bulk API won't hop over limit using 1-fragment sms
- Bulk API won't hop over limit using 3-fragment sms
- One-off ADMIN sends warning email, limit reached email, and blocks sends
- One-off ADMIN won't hop over limit using 3-fragment sms
- CSV ADMIN  sends warning email, limit reached email, and blocks sends
- CSV ADMIN won't hop over limit using 1-fragment sms
- CSV ADMIN won't hop over limit using 3-fragment sms
=> Add additional tests for sms parts

renovate.json
This PR updates renovate to only do its magic to `requirements-app.txt` and `requirements_for_test.app` and not to touch `requirements.txt` anymore.
We will update that file via `make freeze-requirements` that will come in another PR.
=> chore(renovate): update config to ignore requirements.txt

app/dao/service_email_reply_to_dao.py, tests/app/dao/test_service_email_reply_to_dao.py, tests/app/service/test_rest.py
This is the API side of the fix for the reply-to bug and UX issues described on the attached card.
The API no longer returns an error when trying to archive the default reply-to address, as long as it is the only one. This allows the user to return to the initial state, before they entered a reply-to address. This makes adding a reply-to address a "reversible" action and solves that UX problem where they are not warned their action was irreversible.
Trying to delete the default reply-to address will still return an error, if other non-archived reply-tos exist. This is to ensure we don't get into a buggy state. If the user clicks to archive a default reply-to in this case, the Admin should warn them and then assign default to one of their other addresses before the deletion occurs.
Test …
=> Fix for reply to bug

.env.example
Removes unreferenced `SENDGRID_API_KEY` from .env.example that was missed in https://github.com/cds-snc/notification-api/pull/1291.
=> Remove SENDGRID_API_KEY

.github/workflows/test.yaml
API is having the same issue as what occurred yesterday in `notification-admin`: https://github.com/cds-snc/notification-admin/pull/1408 
CI should now pass.
=> Pin waffles to a version

app/celery/provider_tasks.py
This is to reduce alarms fatigue with our errors.
Do not log the exception right away when a SMS failure occurs but only after the first retry. That is because most likely error that happens at this stage is the db data replication did not propagate yet and could not find the notification. By retrying immediately as it is setup at the moment, it usually succeeds on second try. But prior to this change, the logging statement would trigger our alarms even though the 2nd attemps most likely succeed.
If there is other type of errors, an immediate retry following another failure will then log the exception and raise the alarms as usual.
This will have to be monitored via the logs, upon celery SMS sending failures.
None.
This is a suggested checklist of questions reviewers might ask during …
=> Report exception after first SMS sending retry only

.devcontainer/scripts/notify-dev-entrypoint.sh, .gitignore
- You need to add smoke test env files from Lastpass to the project root (`.env_smoke_staging` and `.env_smoke_prod`)
- from a devcontainer terminal can now run the alias `smoke-staging` or `smoke-prod`
=> add smoke test to dev container

app/celery/provider_tasks.py
We don't want the API to throw an error for one retry. We will throw a warning when there have been more than 10 retries.
This is from where I assume we have retry data:
https://github.com/celery/celery/blob/main/celery/app/task.py#L704
=> Change warning and exception logger for retries

app/notifications/validators.py, tests/app/notifications/test_validators.py
This PR updates the sms validator which checks the overall message length to include the length of service name which we always append to every sms message.
=> fix: take service name into account when checking sms message length

app/service/utils.py, tests/app/notifications/test_validators.py
Sending simulated SMS and Email notifications while using a team api key was returning a 400 error.
Create a service, add a Team API Key, and email and SMS templates. Hit `/v2/notifications/[sms|email] with the Team API Key. Observe that the request will now succeed.
setup, etc.) | Faudra-t-il mettre à jour la documentation à …
=> Fix bug where simulated email/sms sent via the API with a team key was not working

migrations/versions/0425_update_system_templates.py
This PR updates all of the GC Notify system templates to correct the french product name, as well as establishes a baseline for these templates in case we ever need to re-create an environment from scratch.
- Ensure that the templates being updated have the correct content
- Ensure there is no instances of "GC Notification" in any system templates
=> Update french product name in system templates

app/__init__.py, app/config.py, app/v2/notifications/post_notifications.py, tests/app/v2/notifications/test_post_notifications.py
We want to write to one redis instance and read from another. This will be used for the redis upgrade.
- created a new redis container in the devcontainer (basically just copy the one that's there and change the name and port)
- set both URLs to point to the old one. Verify that Notify still works.
- turn off the beat worker. new POSTs just pile up in the inbox since there's nothing moving them to an inflight.
- stop everything. set `REDIS_PUBLISH_URL` to the new container. Run everything. 
- old redis gets the inbox processed and sent.
- new POSTs pile up in inbox on new redis
- stop everything. Set both URLs to new redis. restart everything
- new inbox gets processed and sent
- new POSTs get sent
- nothing goes into old redis
=> Use a different redis cluster for publishing new POSTs

.devcontainer/Dockerfile
The currently pinned dev container image appears to be out of date, producing a GPG error when building. Unpinning the image resolves this issue.
```
GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <[yarn@dan.cx](mailto:yarn@dan.cx)>
```
=> Fix GPG error, unpin devcontainer version

.devcontainer/devcontainer.json
`Pylance` is now the default python formatter in VS code so we can change to that. And adding the `mypy` extension will hopefully make the type hints in the editor work better.
=> Update dev container extensions

poetry.lock, pyproject.toml
Update notification utils to use: https://github.com/cds-snc/notification-utils/releases/tag/50.1.5
=> Update notification utils to 50.1.5

app/dao/notifications_dao.py, tests/app/dao/notification_dao/test_notification_dao_bounce_rate.py
This PR updates the bounce rate queries to use `feedback_type = 'hard-bounce'` instead of relying on `notification_status` like we needed to before this point.
=> Update bounce rate queries to use `feedback_type`

migrations/versions/0428_add_bounce_type_known.py
This PR updates the `ALTER TYPE` migration (0428_add_bounce_type_known) to prevent this error happening in postgres 11.17:
```
psycopg2.errors.ActiveSqlTransaction: ALTER TYPE ... ADD cannot run inside a transaction block 
```
=> Fix failing migration in staging/prod

app/models.py, app/schemas.py, migrations/versions/0429_add_organisation_notes.py
This PR adds a new column `organisation_notes` to the `services` and `services_history` tables. This column will eventually contain strings entered by users creating new trial services. The `organisation_notes` string will be the combination of strings entered on this page:
I am thinking they will be combined like this: `"parent_organisation_name > child_organisation name"` but that is not set in stone.
This data would then be pulled from the db and inserted into the freshdesk ticket if/when the service requests to go live.
The `organisation_notes` column is `nullable` so we can merge this change before the rest of the admin code is ready. I tested this code locally with the `main` branch of notification-admin - new services are created successfully with `NULL`s in the …
=> Add the `organisation_notes` column

app/clients/salesforce/salesforce_account.py, app/clients/salesforce/salesforce_client.py, app/clients/salesforce/salesforce_contact.py, app/clients/salesforce/salesforce_engagement.py, app/service/rest.py, tests/app/clients/test_salesforce_account.py, tests/app/clients/test_salesforce_client.py, tests/app/clients/test_salesforce_contact.py, tests/app/clients/test_salesforce_engagement.py
Create a Salesforce Engagement when a new Notify service is created.  
The Notify user that creates the Engagement will have their associated Salesforce Contact updated.  If there is not already a Salesforce Contact for the Notify user, one will be created.
- cds-snc/platform-core-services#282
=> feat: Salesforce Engagement create

app/clients/salesforce/salesforce_account.py, app/clients/salesforce/salesforce_client.py, app/clients/salesforce/salesforce_contact.py, app/clients/salesforce/salesforce_engagement.py, app/service/rest.py, tests/app/clients/test_salesforce_account.py, tests/app/clients/test_salesforce_client.py, tests/app/clients/test_salesforce_contact.py, tests/app/clients/test_salesforce_engagement.py
Update the Salesforce Engagement stage as a Notify service goes through the `go live` flow.
This involves setting the Engagement stage to `Activiation` when the request to go live is made.  Once the service is set as live, the Engagement stage is then set to `Live`.
1. Login and create a new service.
1. Check Salesforce and expect to see a new Engagement with `stage = Trial`
1. Request for the service to go live.
1. Check Salesforce and expect the service Engagement to have `stage = Activation`
1. Set the service as live.
1. Check Salesforce and expect the service Engagement to have `stage = Live`
1. Repeat the above Notify steps and expect no Salesforce Engagement creation or stage updates.
- cds-snc/platform-core-services#285
=> feat: Salesforce Engagement go live flow

app/clients/salesforce/salesforce_auth.py, tests/app/clients/test_salesforce_auth.py
Update the Salesforce API requests to timeout after 10 seconds. This will prevent excessive waiting for Notify users if the Salesforce API is unresponsive.
=> feat: add timeout to Salesforce API requests

app/clients/salesforce/salesforce_auth.py
This will ensure Notify users don't wait too long for trial service creation, etc if the Salesforce API goes down.
=> Adjust Salesforce timeout to 3s

app/clients/salesforce/salesforce_client.py, app/clients/salesforce/salesforce_contact.py, app/clients/salesforce/salesforce_engagement.py, app/user/rest.py, tests/app/clients/test_salesforce_client.py, tests/app/clients/test_salesforce_contact.py
Update a Notify user's linked Salesforce Contact if the user profile is updated.
This change also applies the same Salesforce Contact refactor that was made to the Engagements, which will make it easier to support future update requirements.
- Closes cds-snc/platform-core-services#304
=> feat: update Salesforce contact if profile changes

app/clients/salesforce/salesforce_client.py, app/clients/salesforce/salesforce_contact.py, app/clients/salesforce/salesforce_utils.py, tests/app/clients/test_salesforce_contact.py, tests/app/clients/test_salesforce_utils.py
Fix the Salesforce Contact create if the Notify user's name is only one word.  Salesforce requires the `LastName` field to be set, but the `FirstName` field is optional.
- Closes cds-snc/platform-core-services#308
=> fix: Salesforce Contact one word names

app/clients/salesforce/salesforce_client.py, app/service/rest.py, app/user/rest.py, tests/app/clients/test_salesforce_client.py
Update the Salesforce Engagement for a service with the "go live" use case from the request.  This will be added to the Engagement's description.
- cds-snc/platform-core-services#310
=> feat: add service "go live" use case to Salesforce

app/clients/freshdesk.py, app/user/rest.py
Populate Freshdesk organisation in "go live" requests using `service.organisation_notes`
=> Populate Freshdesk organisation in "go live" requests using `service.organisation_notes`

app/user/rest.py
Update the `go live` contact request to check for a service ID.  If one does not exist, log the contact details so we can start to troubleshoot how contact requests are ending up in this code path.
=> fix: go live contact check for service ID

poetry.lock, pyproject.toml
Upgrade to latest utils:
- https://github.com/cds-snc/notification-utils/pull/174
- https://github.com/cds-snc/notification-utils/pull/181
- Run api locally and look for redacted env vars
- Send a team invite and make sure it works
=> bump up utils to 50.1.10

tests-perf/ops/Dockerfile
Docker image for perf test hadn't been poetry-ized and would fail to build, causing our ci pipeline to fail
Pretty much copy-pasted what we do in the app Dockerfile.
can build locally with `docker build -t perf-tests . -f tests-perf/ops/Dockerfile`
=> fix: poetry-ize perf test docker image

app/user/rest.py, tests/app/user/test_rest.py
Update the `go live` contact request to handle the case where a service does not have `organisation_notes` specified.  This will be the case for all services created before the Salesforce integration was turned on.
Currently this missing `organisation_notes` column is breaking the `go live` request flow and preventing the Freshdesk ticket from being created.
- #1817
=> fix: handle cases where no organisation notes

app/clients/freshdesk.py, app/user/rest.py, tests/app/user/test_rest.py
This adds some functionality I missed to cover the case where a service requests to go live that was created before the CRM integration feature was launched.
I tested using the following steps:
1. run this locally and connect a locally running `notification-admin` with `FF_SALESFORCE_CONTACT=False`
2. create a trial service 
3. change `FF_SALESFORCE_CONTACT=True` and restart `notification-admin`
4. go through the "go live" request process
5. observe that you are asked to enter an organisation name on the first step
6. make the go live request
7. this freshdesk ticket was created, displaying the organisation I entered at step 5 and no errors occurred: https://cds-snc.freshdesk.com/a/tickets/14961
=> Fix for missing org notes

.github/workflows/docker-vulnerability-scan.yml
Update to use the OIDC role in the same account as the ECR image being scanned.
=> fix: OIDC role used for docker vuln scan

poetry.lock, pyproject.toml
Bump utils version 5.3.0 -> 5.3.1. This PR should resolve issues with failing WAF rules check on https://github.com/cds-snc/notification-api/pull/1837
=> Bump utils version 5.3.0 -> 5.3.1

app/clients/freshdesk.py
This PR adds logging when we send Freshdesk tickets so we can better track them when troubleshooting Freshdesk related issues.
=> Add ticket info logging when creating freshdesk tickets

app/notifications/validators.py, tests/app/notifications/test_validators.py
Rename Rate limit function and add a docstring to reduce confusion about what this function is doing.
=> Rename Rate limit function and add a docstring

app/__init__.py
This is a bug fix for an issue where methods on the `BounceRateClient` were not actually saving things to Redis because they were failing this `if` check: https://github.com/cds-snc/notification-utils/blob/main/notifications_utils/clients/redis/redis_client.py#L140
We need to initialize the `BounceRateClient` with `redis_store` since that is what we are calling `.init_app()` on here: https://github.com/cds-snc/notification-api/blob/main/app/__init__.py#L130
and that sets `self.active = True`.
=> Fix for bug where `redis_client.active=False` for the running app

app/celery/process_ses_receipts_tasks.py, tests/app/celery/test_process_ses_receipts_tasks.py
Removed a call to `bounce_rate_client.set_sliding_notifications` that was resulting in double counting, updated tests.
Tests should pass, we can QA further in our staging environment.
=> Fix bounce rate double counting bug

app/notifications/validators.py, app/v2/notifications/post_notifications.py, tests/app/notifications/test_validators.py
Logging to track bounce rate statuses in `check_service_over_bounce_rate` is missing in cloudwatch logs. This PR will temporarily add additional logging for debugging this issue. After debugging and testing this PR will be reverted.
Add logging statements around calls to `check_service_over_bounce_rate` to determine which parts of the process are properly called.
Add log statements in `check_service_over_bounce_rate` to see a service's bounce rate and bounce status before logging by status, and to verify that the feature flag check is working correctly in this method.
=> Additional log statements for debugging

app/delivery/send_to_providers.py, app/notifications/validators.py, app/v2/notifications/post_notifications.py, tests/app/delivery/test_send_to_providers.py, tests/app/notifications/test_validators.py, tests/app/v2/notifications/test_post_notifications.py
Moved the bounce rate check to `send_to_providers.py` in celery. This allows us to call it from one place, and when we later suspend the service from here, it should work since we do not send to the provider if the service is suspended.
Tests should pass, we can QA the logs in Staging.
=> Fix bounce rate logging

poetry.lock, pyproject.toml
api uses the token generating and checking code from utils to create and check team invitation urls.
Here we switch api to use the [new token code from utils](https://github.com/cds-snc/notification-utils/pull/204) that uses "token" for the salt when generating tokens, but still accepts allows tokens signed with salt DANGEROUS_SALT.
After this has been in production long enough for all old tokens to expire (min 2 days) we will push another PR to api that stops sending the salt to the utils token code. (after that, we can update the utils token code to not accept a salt as an argument)
- run with the old utils (ie api/main)
- send an invitation to your service (say, to you+testutils1@cds-snc.ca)
- verify that if you click the link you get to the "create an account" page
- Don't make a new …
=> upgrade utils to 50.3.3 and rerun poetry lock

.github/workflows/test.yaml, pyproject.toml
Current we do not have safe guards in place to prevent an outdated `poetry.lock` file from being committed to main. When this occurs it can lead to our dev containers running into issues. This PR adds a check during the test CI job to ensure that the lock file is up to date and consistent with `pyproject.toml`.
=> Add check to CI to ensure poetry.lock is consistent with pyproject.toml

app/celery/process_ses_receipts_tasks.py, app/config.py, app/delivery/send_to_providers.py, app/models.py, app/v2/notifications/post_notifications.py, tests/app/conftest.py, tests/app/delivery/test_send_to_providers.py, tests/app/service/test_rest.py, tests/app/test_model.py
Create a new backend-specific feature flag for bounce rate. The purpose of this is so we can turn this on independently of the frontend, and start to collect data in Redis and log the bounce rate. There should be no user-visible changes related to this. 
This is to start populated data in Redis to enable us to display data from Redis in the UI for those services that have the bounce rate feature turned on: https://github.com/cds-snc/notification-admin/pull/1554 
CI should pass, should be no visible changes.
We will need a follow up PR to turn this feature flag on in Staging.
=> Create a new backend-specific feature flag for bounce rate

app/models.py, app/notifications/callbacks.py, tests/app/notifications/test_callbacks.py, tests/app/v2/notifications/test_get_notifications.py
Reverts cds-snc/notification-api#1870 while we address updating the API documentation, and restore the notification status, and add the formatted status message as a separate new property to avoid breaking any client integrations.
=> Revert "Improve api and callback status messages"

app/models.py, migrations/versions/0431_add_pt_organisation_type.py, tests/app/dao/test_services_dao.py, tests/app/organisation/test_rest.py
Add `province_or_territory` organisation type.
This will allow us to identify if a service is for a P/T or not, and apply some different rules for template redaction and data retention. 
We'll also need to add it in notification-admin before we are able to set this type for an organisation.
Tests should pass, new row should be visible in the `organisation_types` table.
=> Add `province_or_territory` organisation type

.github/workflows/build_and_push_performance_test.yml, .github/workflows/docker.yaml, .github/workflows/lambda_production.yml, .github/workflows/lambda_staging.yml, .github/workflows/performance.yml, .github/workflows/test.yaml
If we have a failure during the execution of the `build_and_push_performance_test` GitHub action, we notify Slack with a link to the repository. This PR changes the link to refer to the failed run ID directly so that we do not have to search through our actions manually.
Make the perf workflow fail and notice the link in the Slack notification.
It`s possible it might not work. If that does not, we can replicate the strategy adopted for the URL shortener:
https://github.com/cds-snc/url-shortener/blob/main/.github/workflows/workflow_failure.yml
=> Provide a direct link to the failed run when failure

app/clients/salesforce/salesforce_client.py, app/clients/salesforce/salesforce_engagement.py, app/service/rest.py, tests/app/clients/test_salesforce_client.py, tests/app/clients/test_salesforce_engagement.py, tests/app/service/test_rest.py
Update the Salesforce API so that as Notify service team members are added and removed, associated Engagement ContactRoles are also added or removed for each team member.
1. With `FF_SALESFORCE_CONTACT=true`, start the local API and admin.
2. Create a new service as user `A`.
3. Add a new team member to the service (user `B`) with the permission to manage service team members.
4. Accept the invitation and login to Notify with the new team member `B`.
5. In Salesforce, expect to see ContactRoles on the service's Engagement for users `A` and `B`.
6. As user `B` in Notify, remove user `A` from the service.
7. In Salesforce, there should now only be one ContactRole on the Engagement for user `B`.
- cds-snc/platform-core-services#344
=> feat: sync Salesforce Engagement ContactRoles

app/models.py
The type annotations that were included here (mostly by me) are actually incorrect. These should all be `sqlalchemy.Column` types like this:
They are not just `UUID` or `int` or `str` - they have lots of special methods that can be used in queries, and we will get type errors inside our DAO files if we don't use the correct type.
Tests should pass in CI.
=> Remove incorrect types from models.py

app/dao/templates_dao.py, app/template/rest.py, tests/app/dao/test_templates_dao.py, tests/app/template/test_rest.py
After testing creating new templates on staging for P/T services, I observed that the templates were not always auto-redacted and I found `Template not found for redaction.` in the logs. This is logged when we try to fetch the template by id, and we get a `NoResultFound` error: https://github.com/cds-snc/notification-api/blob/main/app/template/rest.py#L106
This indicated that the template has not been created in the db yet and that is causing the redaction to fail. Instead, we can just set the `redact_personalisation` property to `True` when we create the template, and that seems to work.
I removed the optional `tempate_id` argument from `create_template`, since I had added that in the original PR for this feature and it is no longer needed: …
=> Fix bug where template redaction for P/Ts is flaky

tests/app/celery/test_tasks.py
Test was failing between midnight and 2 AM UTC because `now.hour() - 2` was negative. Here we subtract hours using datetime objects instead.
=> use timedelta to subtract time in test

app/clients/salesforce/salesforce_engagement.py
Update the Salesforce logic that adds or removes
Engagement ContactRoles to only attempt to parse
the request result if an operation has been performed.
This will fix the Salesforce errors being logged by the API when
it was attempting to parse results that were in an 
unexpected format.
- cds-snc/platform-core-services#344
=> fix: errors when adding/removing ContactRoles

app/celery/process_ses_receipts_tasks.py, tests/app/celery/test_process_ses_receipts_tasks.py
Getting lots of KeyErrors raised here
https://github.com/cds-snc/notification-api/blob/main/app/notifications/notifications_ses_callback.py#L39
Believe it is because of the recently added new sending domains. AWS does verification calls when you first create them.
This causes us to try to process an AWS response of "AmazonSnsSubscriptionSucceeded" which our code cannot understand so it throws an error.
Note that if these are related to the new sending domains then these are not associated with notifications, and so our system should not be processing them.
This PR moves the query for the associated notification in front of the response parsing, so if there is no related notification we will not do the parsing. This means that in this case we will not get to the parsing code and not throw …
=> bug fix KeyErrors from AWS sending domain verification

app/aws/metrics.py
[This](https://github.com/cds-snc/notification-api/pull/1894) didn't work - I think because we already flushed() the metric, we need to use a new one.
try it again on staging...
=> Fix expired inflight metric

app/service/rest.py, tests/app/service/test_rest.py
Update the Salesforce Engagement name when its linked Notify service name changes.
1. Create a new Notify service and check that a linked Salesforce Engagement was created.
2. Update the service's name in Notify.
3. Check that the Salesforce Engagement name was also updated.
- https://github.com/cds-snc/platform-core-services/issues/343
=> feat: update engagement when service name changes

poetry.lock, pyproject.toml
Upgrade to `notifications-utils` version 51.0.2 with `poetry add git+https://github.com/cds-snc/notifier-utils.git#51.0.2`. I also ran `poetry lock`.
Tests should pass.
=> Install notifications-utils version 51.0.2

.gitignore, .vscode/launch.json
I needed this to debug this PR: https://github.com/cds-snc/notification-api/pull/1912
We probably want to run the celery debugger like this all the time since that is how we are running it in production (I think?).
=> Set `--concurrency=4` for celery debugger

Makefile
Add some make targets for running the celery scripts to make local running a little easier.
Run the celery workers with `make run-celery-beat` and either `make run-celery` or `make run-celery-clean`
=> Add celery worker make targets

.github/workflows/test.yaml, poetry.lock, pyproject.toml
CPython 3.0 released recently which appears to have [introduced a regression](https://github.com/yaml/pyyaml/issues/601#issuecomment-1011355313) that leads to [failures when installing PyYaml](https://github.com/yaml/pyyaml/issues/724) (and likely other packages). This PR reverts PyYaml to 5.3.1 for the time being until either the regression is corrected or a more appropriate work around is identified by us or the community.
=> Revert PyYaml to 5.3.1

app/dao/services_dao.py, app/email_limit_utils.py, tests/app/dao/test_services_dao.py, tests/app/test_email_limit_utils.py
First updates for email daily limits. This PR puts the daily service limit into redis.
We also add a func to find the number of emails sent in a day. Added tests for the above functionality as well.
=> Daily Email Limits - Add limits to redis

app/celery/scheduled_tasks.py, app/celery/tasks.py, app/config.py, app/dao/notifications_dao.py, tests/app/celery/test_scheduled_tasks.py, tests/app/celery/test_tasks.py, tests/app/dao/notification_dao/test_notification_dao.py
This PR:
- removes the `job_complete` calls from `process_job` and `process_incomplete_job` since these calls were happening before all notifications had been added to the db, and update the associate tests
- adds a new periodic celery task that runs every minute called `mark-jobs-complete`. This queries for "in progress" jobs and checks if the notifications for that job exist in the notifications table yet. If the do exist, the job is marked "complete"
- tests for `mark_jobs_complete`
- adds a new function to `notifications_dao.py` called `get_notification_count_for_job`, as well as tests for this
1. Run `./scripts/run_celery_purge.sh` locally
2. run notification-api locally using this branch (`fix/celery-task-job-complete`), also run celery
3. point notification-admin to your local api …
=> New celery task for marking jobs as complete

app/celery/scheduled_tasks.py, tests/app/celery/test_scheduled_tasks.py
For jobs that are not complete after 2 hours, the `job_status` gets updated to `error` here: https://github.com/cds-snc/notification-api/blob/main/app/celery/scheduled_tasks.py#L192.
Those jobs are then set to `process-incomplete-jobs` and the remaining rows are added to the `notifications` table. Once all the rows are added to the notifications table, these jobs can be marked `complete`.
=> `mark-jobs-complete` should also run on jobs with the error status

app/schemas.py
This PR:
- makes the validator functions for the marshmallow `JobSchema` work for timezone-aware and timezone-naive times, since these both have a `.timestamp()` method that converts a datetime to a number of seconds since Jan 1, 1970 UTC time: https://docs.python.org/3/library/datetime.html#datetime.datetime.timestamp
- removes some unused validator functions that looked like they contained the same bug
1. check out the `main` branch and run locally
2. send an api request to `http://host.docker.internal:6011/v2/notifications/bulk` with the following data:
```
{'name': 'send 22',
'scheduled_for': '2023-07-25T19:34:43-05:00',
'rows': [['email address'], ['success@simulator.amazonses.com']],
'template_id': 'your-template-id'}
```
3. observe that you get a 500 error back
4. check out this …
=> Fix 500 error when `scheduled_for` time contains a timezone offset

scripts/run_celery.sh
Double the number of celery concurrent workers. The current value of `4` was probably selected for the number of CPU cores present on the machines running our workers. But as our workers are probably not CPU bound (we do not do numbers crunching) but most likely bound by the network, we can test with more celery concurrent workers, as these would wait on either some AWS service calls, the database or Redis.
Testing in a scratch environment might be preferable.
=> Double number of concurrent celery workers (DO NOT RELEASE TO PROD)

scripts/run_celery.sh
Use the new `CELERY_CONCURRENCY` env var.
Note that if the variable is not defined, the concurrency will be the default value of 4.
1. run `make run-celery` without the env var. Note the concurrency is 4. Kill celery and see 4 workers stopped.
2. set `export CELERY_CONCURRENCY=8` and run `make run-celery` again. This time the concurrency is 8.
=> use CELERY_CONCURRENCY

migrations/versions/0433_update_daily_email_limit_templates.py, migrations/versions/0433_update_email_templates.py
Updated to the new content from here: https://www.figma.com/file/j7NLJsOY8UQkGNH50Js00t/Sending-capacity---capacit%C3%A9-d'envoi?type=design&node-id=1538-12097&mode=design&t=8vuUvcO0SyrJXTgQ-0
I created test templates using the new markdown to make sure they looked correct.
Near limit:
At limit:
Limit updated:
1. check out locally
2. run the migration
3. view the new email templates
4. make sure they match the designs in figma
=> Update to the new content for emails regarding the email daily limits

app/notifications/validators.py, app/utils.py, migrations/versions/0434_update_email_templates_sms.py, tests/app/notifications/test_validators.py, tests/app/test_utils.py
Add the new SMS limit email content from here: https://www.figma.com/file/j7NLJsOY8UQkGNH50Js00t/Sending-capacity---capacit%C3%A9-d'envoi?type=design&node-id=1623-2924&mode=design&t=87MnIuJOGMSnVZ8C-0
Made the limit reset time dynamic with a new function.
I tested locally and the emails looked correct:
Limit reached:
Near limit:
1. Check out locally, run api and admin
2. run `poetry run flask db upgrade`
3. view the templates and make sure they look correct
4. try sending sms to trigger the various emails, and make sure the email you receive is correct (should contain 8PM / 20 heures at this time of year)
=> Add the new sms content

app/notifications/validators.py, migrations/versions/0435_update_email_templates_2.py, tests/app/notifications/test_validators.py
I left the content of these emails the same, and added personalisation variables for the limit reset time.
1. check out locally
2. run the migration `poetry run flask db upgrade`
3. make sure you have `FF_EMAIL_DAILY_LIMIT=True` in your .env file for both api and admin
4. start both api and admin locally
5. set your service's daily email limit to 5
6. send 4 emails
7. verify that you get the "near limit" warning email and that it contains 8PM / 20 heures
8. send 1 more email
9. verify that you get the "limit reached" email and that it contains  8PM / 20 heures
=> Add the limit reset time variable to the email limit templates

app/celery/scheduled_tasks.py, app/celery/tasks.py, app/config.py, app/models.py, app/notifications/process_notifications.py, app/notifications/rest.py, app/service/send_notification.py, app/utils.py, app/v2/notifications/post_notifications.py, migrations/versions/0433_update_email_templates.py, scripts/run_celery.ps1, scripts/run_celery.sh, tests/app/celery/test_scheduled_tasks.py, tests/app/celery/test_tasks.py, tests/app/notifications/rest/test_send_notification.py, tests/app/notifications/test_process_notification.py, tests/app/service/test_send_one_off_notification.py, tests/app/test_config.py, tests/app/test_model.py, tests/app/test_utils.py
https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/186
Move sms sending (ie `deliver_sms()`) to their own queues (send-sms-high, send-sms-medium, send-sms-low)
note that these queues are still all services with the same celery works as the other queues.
- Send some sms
- one-off, bulk
- priority, normal, and bulk templates
- see what delivery queues are being used by looking for lines in the celery logs like "... sent to the .... queue for delivery"
- ensure the correct queue was used in each case
- We will need alarms added to terraform for these queues
- also need to add "age of oldest message" charts to the SMS dashboard
=> send sms using 3 new queues

app/dao/fact_notification_status_dao.py, tests/app/dao/test_fact_notification_status_dao.py
We had an incorrect query for finding when an api_key was last used. If the api_key was used before 7days (in notification_history), we were not taking that into account. This Pr fixes that and adds a test.
=> Correct the query for when api key was last used. Added test

Makefile, scripts/run_celery.sh, scripts/run_celery_beat.sh, scripts/run_celery_local.sh, scripts/run_celery_no_sms_sending.sh, scripts/run_celery_send_sms.sh, scripts/run_celery_sms.sh
As part of the process of moving sms sending to its own pod deployment, we need a new script for those pods to run!
Our code is all over the place, so this is the process:
- created new celery queues for sms sending (and associated alarms) **DONE**
- create new scripts for 
- the new SMS celery pod deployment (**this PR**)
- the old celery pod deployment (ie not containing the send-sms-* queues) (**this PR**)
- create the new deployment that uses this script in staging ([manifest repo PR](https://github.com/cds-snc/notification-manifests/pull/1980))
I've also added some documentation to the scripts, as well as a new script for running all the queues locally.
=> tweak celery scripts

app/v2/notifications/post_notifications.py
This PR adds error handling so that we don't cause a 500 error when and API caller doesn't set the `Content-Type` header to `application/json`. You can reproduce the error on staging with the following command:
```
curl -i -X POST \
-H "Authorization:ApiKey-v1  gcntfy-talend_key-3********" \
-H "Content-Type:" \
-d \
'{
"email_address": "stephen.astels@cds-snc.ca",
"template_id": "eb3a6c36-2e4d-4e55-9e25-ed4b314ff3e9",
"personalisation": {
"var": "test /email"
}
}' \
'https://api.staging.notification.cdssandbox.xyz/v2/notifications/email'
```
Check out this branch locally and try the above curl command. You should get a 415 error back now instead of a 500 error.
=> Handle the `UnsupportedMediaType` error

app/api_key/rest.py, app/dao/api_key_dao.py, app/models.py, migrations/versions/0436_add_columns_api_keys.py, tests/app/api_key/test_rest.py, tests/app/dao/test_api_key_dao.py
Add an internal API so that SRE can call it and revoke API keys
=> Add an internal api so that we might revoke api keys

app/dao/date_util.py, app/dao/fact_notification_status_dao.py, tests/app/dao/test_fact_notification_status_dao.py
This PR fixes the daily stats query to use midnight UTC which aligns with the way we handle daily limits.
=> Update daily notification stats to use 12am utc 

app/celery/provider_tasks.py, app/config.py
https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/80
make the celery worker rate limit for `deliver_sms` a config variable so we can keep prod as it is while we play with staging.
- make sure sms still send
- run another `INTERNAL_TEST_NUMBER` perf test in staging and verify that using the default we still get approx 3 sms / sec
=> use config variable for deliver_sms rate limiting

.github/workflows/docker.yaml
Forgot to modify the GitHub action to push image to the new celery-sms-send deployments in staging when the api image changes.
Production should be fine (once we add celery-sms-send) - the celery-sms-send in prod will use the specified api image, so releasing a new api will redeploy celery-sms-send too.
=> update celery-sms-send image in staging

scripts/run_celery_send_sms.sh
Bump up the concurrency on the sms-send celery pods from 4 to 6 to try to get them to do more work.
Note that these pods / script are currently only in staging.
=> increase concurrency on staging sms celery pods

scripts/run_celery_send_sms.sh
sms send pods concurrency 6 -> 10 📈
=> staging sms celery concurrency to 10

app/clients/email/aws_ses.py, app/delivery/send_to_providers.py, tests/app/delivery/test_send_to_providers.py
This PR changes the way we are encoding the "friendly from" field in the email headers, so that we can include non-ascii characters that show up in service names. The AWS documentation provided examples of how to do this. There are 2 steps:
1. encode the utf-8 characters as base64
2. replace the ascii-encoded "friendly from" field with "MIME encoded-word syntax" that includes the base64 encoded string
Here is a link to [the AWS docs](https://docs.aws.amazon.com/ses/latest/dg/send-email-raw.html#send-email-mime-encoding-headers) that I used.
Reproduce the bug:
1. log into staging
4. visit your service settings page
5. change the name of your service to `Accent service èé ÀÂËÎÏÔŒÙÛâçêëîïôœû`
6. send an email to yourself 
7. observe that the accents are missing from the "friendly from" part …
=> Encoding unicode in "friendly-from" field

scripts/run_celery.sh, scripts/run_celery_no_sms_sending.sh, scripts/run_celery_send_sms.sh, scripts/run_celery_sms.sh
This PR will implement a status check on the CWAgent in Kubernetes before starting celery. This is required to alleviate a race condition between CWAgent and Celery when starting up on an autoscaled node.
- Deploy on staging
- Run several load tests in staging to see if we get any alerts re: race condition
None.
setup, etc.) | …
=> Adding a check to wait for cwagent before starting

scripts/run_celery.sh, scripts/run_celery_no_sms_sending.sh, scripts/run_celery_send_sms.sh, scripts/run_celery_sms.sh
Removing the init process from a function and putting it in-line instead. There can be issues with sending echos from functions.
- Soak/Smoke/Perf test in staging.
=> Reworking the celery init on k8s so I can see logging

scripts/run_celery.sh, scripts/run_celery_no_sms_sending.sh, scripts/run_celery_send_sms.sh, scripts/run_celery_sms.sh
I had the run init condition backwards in the if statement. Need to run if the value is not empty, not if it is empty.
=> Celery init fix

migrations/versions/0439_add_index_n_history.py
Need to use the notification history table in the data portage. As I am getting the created_by_id - it is v v slow.
Added an index so filtering should be faster. Tested locally
```
"ix_nh_created_by_id" btree (created_by_id)
"ix_notification_history_api_key_id" btree (api_key_id)
"ix_notification_history_created_at" btree (created_at)
```
=> add index for notification history

scripts/run_celery_core_tasks.sh
Had an extra newline in the new core celery script :O
=> fix new celery script

scripts/run_celery_beat.sh, scripts/run_celery_core_tasks.sh, scripts/run_celery_send_email.sh
There were a few celery run scripts that weren't checking that cwagent was ready before launching.
Deploy to staging
Ensure the waiting for cwagent line is in celery logs
Smoke test staging
=> Adding cwagent wait script to all celery launchers

Makefile, scripts/run_celery_beat_local.sh
add a local celery-beat script that doesn't contain the CWAgent stuff (this causes an error when running locally)
```
make run-celery-beat-local
```
=> add local celery beat script

gunicorn_config.py
Remove the server response. Tested this locally.
``` gunicorn -c gunicorn_config.py application```
you would need to bind the guincorn port to 6011 when testing locally
after
before
=> Remove server from response

app/celery/celery.py, app/celery/provider_tasks.py, app/celery/tasks.py
In an effort to downsize the size of logs we send from our FluentBit agent to CloudWatch, this PR contains changes to demote redundant or unnecessary log messages currently set at INFO level into DEBUG level.
* The list of notifications IDs that are processed and about to be sent to providers.
* The notification IDs that are saved into the database.
* The Celery task execution time: **this one can be sensitive** if we have a dashboard that builds a metric on top of this. I verified and didn't see any but that would require double verifications from a team members. I've also set a statsd metric to send this data instead, as this would be more reliable and on purpose with statsd.
I tested locally to make sure that the new integration of the `statsd_client` into the `make_task` factory …
=> Move some verbose celery INFO-level logs to reduce log size

app/celery/celery.py, app/celery/provider_tasks.py, app/celery/tasks.py
Reverts cds-snc/notification-api#2019
I think this is causing celery errors...
=> Revert "Move some verbose celery INFO-level logs to reduce log size"

app/config.py
Enabling a low retry period for SMS high priority queue in production. This allows for lower retry periods when a retry fail for SMS high priority lane. We had this setting set to true in staging environment for a week. This PR turns it on in production next!
Testing has been done in staging in the past week.
Move the CloudWatch logs insight query from staging to production to monitor this feature, i.e. how long does the retries for notifications take.
modification de la politique de …
=> Enable low retry period for SMS high queue in production

scripts/run_celery.sh, scripts/run_celery_core_tasks.sh, scripts/run_celery_exit.sh, scripts/run_celery_local.sh, scripts/run_celery_no_sms_sending.sh, scripts/run_celery_purge.sh, scripts/run_celery_send_email.sh, scripts/run_celery_send_sms.sh, scripts/run_single_test.sh, scripts/run_tests.sh
These fixes a bunch of shellcheck errors and ignores a few I didn't test, actually I didn't test any of this, most of the fixes were pretty straightforward ones, there was one I fixed with co-pilot that should be tested and the others I didn't fix I just assumed they worked as is since they were in the existing codebase.
- **Fixes**: https://www.shellcheck.net/wiki/SC1091 Couldn't find the file that was being referenced (`environment_test.sh`) in `scripts/run_single_test.sh` so I just the source to /dev/null
- **Fixes**: https://www.shellcheck.net/wiki/SC2028 Replaces some echo's where a control character was passed "\n" with a printf so it should work the same and not complain
- **Fixes the read -p error**: https://www.shellcheck.net/wiki/SC3045 by asking co-pilot to fix it, I can't …
=> Fix Shellcheck errors by doing as little work as possible

tests-perf/locust/locust.conf
Looking at [this script](https://github.com/cds-snc/notification-api/blob/9cf34043b1a99136132926c2588f5fc908af55f0/bin/execute_and_publish_performance_test.sh#L9), I think the changes here will make the perf test run longer. This should allow the email deployment time to spin up to a sustained level.
See what happens to the nightly perf tests?
=> make perf test longer

tests-perf/locust/locust.conf
perf test running longer, but still hasn't gotten to levelling off.
check perf test after it runs
=> 10m -> 20m perf test

poetry.lock, pyproject.toml
This PR pins `cryptography` and `certifi` to address security issues.
Added a section in `pyproject.toml` to consolidate our pined dependencies and document the rationale.
https://github.com/cds-snc/notification-api/security/dependabot/119
https://github.com/cds-snc/notification-api/security/dependabot/118
=> Pin vulnerable dependencies

app/dao/fact_notification_status_dao.py, migrations/versions/0440_add_index_n_history_comp.py
We are timing out when we go to the api key page for certain services.
We are running:
-- SELECT max(created_at) as last_notification_created
-- FROM notification_history
-- WHERE api_key_id = xxx
-- GROUP BY api_key_id;
and that takes a couple of seconds to return.
Just doing a count to see how many notifications get returned in for that api - key we are looking at : 6,728,109
Essentially we get 6mil rows back and then reorder them which is the problem. I will optimize this query by 1. removing the group by api_key_id (that doesnt do anything here) (this PR)
and by adding a composite index on (created_at, api_key_id)
again as I am adding an index on a very large table - I expect our usual process to time out. I will add it manually with the OL this week
Added the composite index locally: …
=> Remove redundant group by and add a composite index

tests-perf/locust/locust.conf
Temporarily reverting the nightly load test back to 5 minutes so that we can verify the autoscaling changes from this week.
Verify nightly load test run.
=> Temporarily reverting perf test for a quiet weekend

app/dao/services_dao.py, app/job/rest.py, app/service/send_notification.py, app/sms_fragment_utils.py, app/v2/notifications/post_notifications.py, poetry.lock, pyproject.toml, tests/app/dao/test_services_dao.py, tests/app/v2/notifications/test_post_notifications.py
This PR changes the way we count SMS messages toward a services daily limit, we now count in a 1:1 manner instead of counting fragments toward their daily limit, provided the message does not exceed 4 fragments. 1 SMS message = 1 count toward the daily limit.
Previously we counted individual fragments toward a service's daily limit in Redis. This resulted in a situation where, when a service with 50 daily SMS messages remaining, sends a bulk job of 25 SMS messages with a template size totally 3 SMS parts was counting 75 messages counted toward their daily limit, preventing them from performing the send.
Related work: https://github.com/cds-snc/notification-utils/pull/256
Checkout the branch: [align-csv-sms-counting-locally-test](https://github.com/cds-snc/notification-api/tree/align-csv-sm …
=> Count by sms messages not sms parts for daily limit

poetry.lock, pyproject.toml
This PR reverts bumps to dependencies that may be the cause of smoke test auth issues in staging.
TODO: Regenerate lock file once the [Utils PR](https://github.com/cds-snc/notification-utils/pull/262) has been merged and tagged.
=> Bump utils

.github/workflows/docker.yaml
I don't think that setting the image in deployment is a reliable way to get the deployment to restart. I've added a new build step that will explicitly restart the deployments
I've also added in celery-email-send as one of the deployment images to set and restart as it was missing.
=> Explicitly restarting deployments in staging and adding email celery

.github/workflows/docker.yaml
I had a typo in the workflow where I was trying to assign an image to celery-sms-email instead of celery-email-send
=> Typo in celery-email-send

app/dao/date_util.py, app/dao/fact_notification_status_dao.py, tests/app/dao/test_date_utils.py, tests/app/dao/test_fact_notification_status_dao.py
Reverts cds-snc/notification-api#2064
=> Revert "Notification stats discrepancy take 2 - Handling UTC window and DST when fetching notification stats"

app/dao/date_util.py, app/dao/fact_notification_status_dao.py, tests/app/dao/test_fact_notification_status_dao.py
When [the nightly task that populates ft_notification_status](https://github.com/cds-snc/notification-api/blob/main/app/celery/reporting_tasks.py#L60) runs, the timeframe it uses for fetching notifications to put into the table is 5AM to 5AM UTC, NOT midnight to midnight UTC. We can see this timeframe in the logs:
Since we used a midnight to midnight UTC timeframe to fetch today's notifications, notifications between `00:00` and `05:00` UTC were being counted twice
This PR adjusts the timeframe used to fetch the current day's notifications to match the timeframe used when populating the `ft_notification_status` table. Removing the 5 hour overlap where notifications were being counted twice. 
The date objects used are EST/EDT timezone aware, and will "self-adjust" when `timedelta` math is …
=> Match the 5AM->5AM time window used to populate ft_notifications

app/celery/process_ses_receipts_tasks.py
Initialize variables at the start so that error handling is simplified and existence of variables doesn't need to be checked before logging.
=> Fix ses-process-results error handling

app/celery/process_ses_receipts_tasks.py, tests/app/celery/test_process_ses_receipts_tasks.py
Add a further exception if the process_ses_results times out for different reasons.
Tested:
- added unit tests
https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1478
=> Add a further exception to process ses results

app/api_key/rest.py, app/authentication/auth.py, app/dao/api_key_dao.py, tests/app/api_key/test_rest.py, tests/app/authentication/test_authentication.py, tests/app/dao/test_api_key_dao.py, tests/app/v2/notifications/test_post_notifications.py
We wanted to do three things:
1. Check the notify prefix is sent through the api key
2. Check the service key is part of the secret
3. Return the result from the secret key
Added unit tests and tested locally
Anyone who isnt sending in a whole key, will have to update their api key
=> Add API Validation

app/models.py, migrations/versions/0443_add_apikey_last_used_column.py, tests/app/dao/test_api_key_dao.py
Added a last_used column for api_key
https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1413
Tested locally by running the upgrade
=> Added a last_used column for the api_key

app/config.py
The celery beat schedule needed to be fixed for UTC instead of EST. This PR does that.
=> Clean up celery config for beat schedule

app/dao/fact_notification_status_dao.py, tests/app/dao/test_fact_notification_status_dao.py
Reverting last used so as to not read from the notification history table. This is so that we don't timeout on the api keys page.
=> Reverting Notification History read for api last used key

app/dao/fact_notification_status_dao.py, tests/app/api_key/test_rest.py, tests/app/dao/test_fact_notification_status_dao.py
Given we have backfilled the last_used_timestamp column in api_keys, we do not want to fallack to the notifications table, if that column is empty
=> Remove notification fallback

app/dao/fact_notification_status_dao.py, app/dao/services_dao.py, app/service/rest.py, tests/app/dao/test_fact_notification_status_dao.py, tests/app/dao/test_services_dao.py, tests/app/service/test_rest.py
We need a way to filter heartbeats when calculating the activity for daily usage. We added a default param with no value, to add a way to filter heartbeat templates
https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1495
=> Task: Filter Heartbeats

app/job/rest.py, tests/app/job/test_rest.py
This PR corrects an issue from https://github.com/cds-snc/notification-api/pull/2112 that was causing smoke test failures. Added a few tests to cover a blind spot that caused the issue to slip by in the first place.
=> Fix missing import

pull_request_template.md
Updated the PR template to latest agreed format!
And this very PR uses the latest format itself, this is meta. 🤖
* https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/304
Please proceed below 👇 to check the new boxes in the reviewer's checklist please. 🙏
None.
as the README, setup instructions, a related ADR or the technical documentation.
=> Updated the PR template to latest agreed format

app/job/rest.py
The api lambda is sometimes taking so long to run that the api gateway times out. This PR adds some logging to the culprit function to try to see where the time is being spent.
* https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/308
This has to be run in staging. After the logging is added, we'll upload a 50K file to the test template as described in the [card](https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/308).
> ⚠ If boxes cannot be checked off before merging the PR, they should be moved to the "Release Instructions" section with appropriate steps required to verify before release. For example, changes to celery code may require tests …
=> add diagnostic logging to create_job

app/job/rest.py
- Add another log line to help diagnose where the slowdown in `create_job` is
- changed usage of `recipient_csv` to use cached values rather than recalculating. Note that
- [`recipient_csv.rows == list(recipient_csv.get_rows()`](https://github.com/cds-snc/notification-utils/blob/9d9e8c7c32e3608f4dd8f320eaba4bb67edfcbf5/notifications_utils/recipients.py#L176-L180)
- [ `len(recipient_csv) == len(list(recipient_csv.get_rows()` ](https://github.com/cds-snc/notification-utils/blob/9d9e8c7c32e3608f4dd8f320eaba4bb67edfcbf5/notifications_utils/recipients.py#L108-L111)
* https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/308
upload the big test CSV (on staging) to the IRCC test template and see what happens!
None.
> ⚠ If …
=> Add logging and tweak recipient_csv use

app/job/rest.py
A recent incident was caused by `create_job` taking too long. We traced it to the `recipient_csv.get_rows()` function, which was being called repeatedly to use to get the count of notifications. This PR instead uses the `notification_count` included in the s3 metadata. It falls back to a `get_rows()` based approach if the metadata is missing.
- https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/308
Upload test file in staging.
None.
> ⚠ If boxes cannot be checked off before merging the PR, they should be moved to the "Release Instructions" section with appropriate steps required to verify before release. For example, changes to celery code may require tests on staging to verify that performance has not been …
=> get notification count faster

app/job/rest.py
In #2133 we tried to avoid calling `len(recipient_csv)` by using
```
notification_count = int(data.get("notification_count", len(recipient_csv)))
```
However, the default value in the `get` is being evaluated regardless of whether `notification_count` in a key of `data`.
For example:
```
>>> data = {"notification_count": 12}
>>> data.get("notification_count", print("not needed"))
not needed
12
```
This PR switches to an if/else.
* https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/308
Run on staging...
None.
> ⚠ If boxes cannot be checked off before merging the PR, they should be moved to the "Release Instructions" section with appropriate steps required to verify before release. For example, changes to celery code …
=> Fix slow create_job for real this time

poetry.lock, pyproject.toml
Upgrade notification-utils to latest
* the utils change fixed: https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/305
=> Upgrade utils to 52.1.5

catalog-info.yaml
Updating base catalog info to set the component as a Service part of the larger GC Notification system, that will provide an API (to be defined hereafter if possible), owned by the notify-dev team and already in production.
None.
=> chore: update base catalog info

app/aws/s3.py, app/celery/nightly_tasks.py, app/dao/jobs_dao.py, tests/app/celery/test_nightly_tasks.py
Reverts cds-snc/notification-api#2139
Getting a `psycopg2.errors.InvalidRowCountInLimitClause` on staging since the PR merged 😞
=> Revert "Batch up job archiving code a bit"

app/dao/email_branding_dao.py, app/email_branding/rest.py, tests/app/dao/test_email_branding_dao.py, tests/app/db.py, tests/app/email_branding/test_rest.py
We want to get all the email_brands that belong to a particular organisation. This PR will let us do that.
* https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1157
This can be tested with the related admin PR
=> Add filtering with an organisation id

.github/workflows/docker.yaml, scripts/callManifestsRollout.sh
We had an auth error on the k8s rollout that was not reporting as an error. Wrapped the curl call in a script to make sure that we catch auth errors in the future.
* https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/293
- Merge to main, verify that the release still works. I have verified locally that the script works, but need to make sure it works in the workflow context.
None.
=> Adding error detection around the k8s rollout

app/authentication/auth.py, tests/app/authentication/test_authentication.py
We noticed that when doing an api call to send an email, if there is an extra space in the auth line we now get an error.
For example, using
```
Authorization:ApiKey-v1   gcntfy-new...
```
gets a 403 "Invalid token: Enter your full API key"
But
```
Authorization:ApiKey-v1 gcntfy-new...
```
works fine. This PR allows extra spaces between `ApiKey-v1` and the key.
Add extra spaces and see if there's an auth error.
None.
=> handle extra spaces in api key auth line

.vscode/launch.json, app/celery/service_callback_tasks.py, app/config.py, scripts/run_celery.ps1, scripts/run_celery.sh, scripts/run_celery_core_tasks.sh, scripts/run_celery_local.sh, scripts/run_celery_no_sms_sending.sh, tests/app/celery/test_service_callback_tasks.py, tests/app/test_config.py
Bringing callback changes from GDS upstream repository.
- Reduce callback http request timeout from 60 to 5 seconds.
- Retry callbacks into a dedicated queue to not affect other retriable tasks.
* [Callback URLs timeout and slows down all Celery workers](https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/1](https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/326))
These changes bring 2 changes from GDS repo upstream:
1. [Reduce timeout for service callback attempt to 5 seconds](https://github.com/alphagov/notifications-api/commit/0d952b4d8c3ea97e95134c24b402e82dcf071441)
1. [Put service callback retries on a different …
=> Bug fix: callback URL timing out and preventing notification processing slowdown

Makefile, README.md
Removing very out of date local steps and fixed the make file/dev container steps to avoid confusion
follow readme to build and run the api locally in your VS Code Dev Container
=> adjustments to readme for running api in dev

app/celery/service_callback_tasks.py, tests/app/celery/test_service_callback_tasks.py
Applying GDS upstream goodie [from this PR changes](https://github.com/alphagov/notifications-api/pull/3289):
> if we're served a 429, put the item on the retry queue and retry the same as if the service returned a 5xx. 429 is commonly returned for rate limit exceeding, and retrying on a delay is a typical response to that.
* [Callback URLs timeout and slows down all Celery workers](https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/326)
1. Setup a service with a callback URL such as https://httpstat.us/429?sleep=100 (which will return a 429 status code after 100ms).
2. Send a batch of notifications through the newly configured service with the associated 429 callback URL. 
3. Verify the notifications are retried. …
=> Retry callbacks on 429 'too many requests' code

app/models.py, migrations/versions/0446_add_alt_text.py, tests/app/email_branding/test_rest.py
Add alt text columns in the branding table
* https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1541
None.
=> Added alt text for email_branding table

.github/workflows/test.yaml, app/v2/notifications/post_notifications.py, poetry.lock, pyproject.toml, tests/app/celery/test_tasks.py, tests/app/v2/notifications/test_post_notifications.py
Add proper error message handling when an API user attempts a Bulk SMS send where the variable content exceeds the allowed SMS message limit when combined with their template's content.
https://github.com/cds-snc/notification-utils/pull/290
1. Send a bulk SMS request via the API
2. Note that an error message indicating the message length is too long, possibly due to custom content.
3. Note that the error message is accompanied by the affected row number.
None.
=> Add error message for rows_with_combined_variable_content_too_long

.github/workflows/test.yaml, app/v2/notifications/post_notifications.py, poetry.lock, pyproject.toml, tests/app/celery/test_tasks.py, tests/app/v2/notifications/test_post_notifications.py
Reverts cds-snc/notification-api#2160
=> Revert "Add error message for rows_with_combined_variable_content_too_long"

tests_smoke/send_many.py, tests_smoke/smoke/common.py
Add a script to send an arbitrary number of notifications to the api (in batches).
This will make it easier to do a large send, ie 1M or so, without having to manually upload many 50K files.
`python send_many.py -n 9 -j 3`
None.
=> add script to send arbitrary many notifications

app/celery/tasks.py, app/job/rest.py, app/v2/notifications/post_notifications.py, tests/app/celery/test_tasks.py, tests/app/job/test_rest.py, tests/app/v2/notifications/test_post_notifications.py
Have a case where a [service with a dedicated number is not using the number for bulk sends](https://cds-snc.freshdesk.com/a/tickets/17255) though it is for individual sends.
Found that the `reply_to_text` is not being set for these notifications. Admin one-offs still are working fine, but the other 3 ways to send are affected.
I think there's an issue where foreign keys set in other tables but referencing the `services` table do not appear in the services table when we cache it. In this case, though, we can just set the reply_to_text / sender_id when the job or notification is created.
- Set a dedicated phone number for a service (locally you can just choose one from staging and add it to your local setup as an inbound number, then assign it to your service)
- send yourself some sms. All …
=> fix/use a service's fixed phone number if set

.github/workflows/test.yaml, app/delivery/send_to_providers.py, app/email_branding/email_branding_schema.py, app/user/contact_request.py, app/user/rest.py, tests/app/delivery/test_send_to_providers.py, tests/app/email_branding/test_rest.py, tests/app/user/test_rest.py
Add fields to add alt text en/fr to the Branding update/modidfy as well as Intake form. 
* https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1542
Will need to test along with the [admin PR here](https://github.com/cds-snc/notification-admin/pull/1820)
Cannot merge without this: https://github.com/cds-snc/notification-admin/pull/1820
=> Add alt text en/fr intake

app/config.py
The `process-pinpoint-result` task does not appear in staging in the list of registered celery tasks and so when the lambda calls it, celery doesn't run it. I have no idea why it is not registered but, for example, `process-sns-result` is. Possibly there's some dynamic code where it's registering `process-*` over a list, but searches for this and similar strings came up empty. However, If I explicitly add the `process_pinpoint_receipts_tasks` to the list of celery imports than the task does get registered locally. Hopefully in k8s as well.
* https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/286
Send pinpoint in staging and see if the task runs
None.
> ⚠ If boxes cannot be checked off before merging the PR, they …
=> register process-pinpoint-result task explicitly

app/clients/freshdesk.py, app/user/contact_request.py, app/user/rest.py, tests/app/clients/test_freshdesk.py
We need to send alt_text_en, alt_text_fr and branding_logo_name to the freshdesk ticket
hard to test as we dont have freshdesk locally
=> Added fix for freshdesk ticket for name and logos

app/aws/mocks.py, app/celery/process_pinpoint_receipts_tasks.py, tests/app/celery/test_process_pinpoint_receipts_tasks.py
Pinpoint returns a `SUCCESSFUL` receipt when it sends the text to the carrier. Right now we'll just ignore these (the notification is already set to "sent") and wait for a `DELIVERED` or some sort of failure.
* https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/286
send in staging and make sure the `process-pinpoint-result` task doesn't complain
None.
=> Ignore SUCCESSFUL pinpoint receipts

migrations/versions/0451_create_db_users.py
Adding a migration that handles the creation of db roles/users and the granting them superuser role powers -- includes quicksight_db_user and app_db_user.  
https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/359
Follow this migration across dev and staging -- if the users are created, or ignored if they exist and granted rds_superuser rights, then it's working.  if the migration fails, or that doesn't happen then this is broken.
None.
> ⚠ If boxes cannot be checked off before merging the PR, they should be moved to the "Release Instructions" section with appropriate steps required to verify before release. For example, changes to celery code may require tests on staging to verify that performance has not been …
=> Migration Creation of DB Users/roles

app/delivery/send_to_providers.py, tests/app/delivery/test_send_to_providers.py
Pinpoint is having a problem sending to international phone numbers. This PR sends them with SNS instead.
Send a SMS to the UK BT Text number +4408456021111
SNS should be used to send (in the logs "AWS SNS request finished in...")
None.
=> Use SNS for international phone numbers

app/delivery/send_to_providers.py, tests/app/delivery/test_send_to_providers.py
Default to SNS for another corner case: the code we use to parse the country can fail 😞
None.
None.
=> Default to SNS if we can't parse the number country

migrations/versions/0453_set_supports_international.py, tests/app/dao/test_provider_details_dao.py
In the code SNS and Pinpoint are not allowed to send internationally. At some point in the past we changed the production database to allow SNS to send internationally.
This PR sets `supports_international` for both SNS and Pinpoint through a migration. This will allow us to test international sending in unit tests as well as in staging.
- Check the admin providers page and verify that SNS and Pinpoint are both listed at the bottom as international providers.
- Send to the [fake French number](https://en.wikipedia.org/wiki/Fictitious_telephone_number) +33 1 99 00 11 11 (it should fail but there will be an SNS boto call / delivery receipt and no celery errors) …
=> Allow sns and pinpoint to send internationally

app/delivery/send_to_providers.py, tests/app/delivery/test_send_to_providers.py
Allow Pinpoint to send to international numbers again.
Merge after https://github.com/cds-snc/notification-api/pull/2197 and https://github.com/cds-snc/notification-terraform/pull/1396
Send to the [fake French number](https://en.wikipedia.org/wiki/Fictitious_telephone_number) +33 1 99 00 11 11 (it should fail but there will be a Pinpoint boto call / delivery receipt and no celery errors)
None.
> ⚠ If boxes cannot be checked off before merging the PR, they should be moved to the "Release Instructions" section with appropriate steps required to verify before release. For example, changes to celery code may require tests on staging to verify that performance has …
=> use Pinpoint for international numbers

app/delivery/send_to_providers.py, tests/app/delivery/test_send_to_providers.py
We're sorting out how to set a default sender id for pinpoint. While we do that let's at least get Pinpoint out the door for domestic SMS.
Send to [one of these international test numbers](https://www.proovl.com/test) and [verify that SNS is used](https://ca-central-1.console.aws.amazon.com/cloudwatch/home?region=ca-central-1#logsV2:live-tail$3FlogGroupArns$3D~(~'arn*3aaws*3alogs*3aca-central-1*3a239043911459*3alog-group*3asns*2fca-central-1*2f239043911459*2fDirectPublishToPhoneNumber~'arn*3aaws*3alogs*3aca-central-1*3a239043911459*3alog-group*3asns*2fca-central-1*2f239043911459*2fDirectPublishToPhoneNumber*2fFailure)).
None.
> ⚠ If boxes cannot be checked off …
=> Use sns for international sending

app/delivery/send_to_providers.py, tests/app/delivery/test_send_to_providers.py
Getting a `NO_ORIGINATION_IDENTITIES_FOUND` when trying to use a Pinpoint pool to send to the fake Guam number 16715550123. Works with SNS, so changing to use that for now.
Send to 16715550123. Should send via SNS (and fail because that's not a real number)
None.
=> Use sns for non-CA zone 1

app/models.py, tests/app/dao/test_template_categories_dao.py
1. Updated the model to add a sms_sending_vehicle column
2. Added tests
* https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1609
=> TemplateCategory : updated the template category model

app/schemas.py, app/template/rest.py
This PR introduces the `ReducedTemplateSchema`, which excludes the `content` property. The front end fetches all templates when creating the global `current_service` object, however we do not need this data until we are editing a template.
- [Incident](https://gcdigital.slack.com/archives/C07BV518NH1/p1720635761141479)
1. Log in and access your service
2. Check Redis and note that the `service-<id>-templates` key does not contain template content
=> Add a template schema that excludes the content prop

app/template/template_category_rest.py, tests/app/template/test_template_category_rest.py
This PR updates changes the `delete_template_category` API endpoint to return a 204 if a TC was successfully deleted, fixing an issue with the API client in Admin.
* https://github.com/cds-snc/notification-admin/pull/1890
Tests pass
None.
=> Change delete_template_category http code to 204

app/dao/template_categories_dao.py, app/template/template_category_rest.py, tests/app/dao/test_template_categories_dao.py, tests/app/template/test_template_category_rest.py
Raise an exception when attempting to delete a template category, without `cascade=True`, that's currently associated with templates.
* https://github.com/cds-snc/notification-admin/pull/1890
1. Import [this postman collection](https://github.com/user-attachments/files/15975957/Test.Template.Categories.postman_collection.json)
2. Associate a category with one or more templates
3. Attempt to delete the category
4. Note an error message is raised
None.
=> Raise exception when deleting cat that is linked to template(s)

poetry.lock, pyproject.toml
NewRelic Agent v9 Upgrade to try and bring it several versions ahead, and potentially fix slow pod startups in K8s
https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/313
1. ensure the api is deployed properly on staging
2. go to this link: [API K8s Entity in NR](https://one.newrelic.com/nr1-core/apm/overview/MjY5MTk3NHxBUE18QVBQTElDQVRJT058NTExMzk5NjEx?account=2691974&duration=1800000&state=6beff9aa-43f8-ee8e-16e4-d369c2f7f37d)
3. Check the metadata to see if the version is upgraded from version 6.x to 9.x
None.
> ⚠ If boxes cannot be checked off before merging the PR, they should be moved to the "Release Instructions" section with appropriate steps required to verify before release. For example, changes to celery …
=> NewRelic Agent v9 Upgrade

app/dao/template_categories_dao.py, app/template/template_category_rest.py
Adding some logging to debug and issue in production with the Template Categories platform admin page.
[Related Incident](https://gcdigital.slack.com/archives/C07E28HUJ49/p1721832314507579?thread_ts=1721827102.222079&cid=C07E28HUJ49)
Revert post-resolution of the issue.
=> Add logs when getting all TC's

application.py, mypy.ini, poetry.lock, pyproject.toml
Adding the Xray SDK references/packages and some recorder code.  The idea is that Xray will potentially be able to see this when deployed.
(https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/319)
- Login to AWS staging Cloudwatch
- Find the XRay Tracing section
- Verify if any metrics are available!
None.
=> Adding Xray SDK and Recorder Code

app/delivery/send_to_providers.py, app/models.py, app/schemas.py, tests/app/template/test_rest.py, tests/app/test_model.py
We want template.process_type to return template.process_type if that had data, else it should return the process_type from the TemplateCategory associated with that template.
Create a new template and set the TemplateCategory.
Use an existing template where the TemplateCategory is NOT set.
Edit and existing template and set the TemplateCategory
=> Add hybrid_property and expression property for template.process_type

application.py, poetry.lock, pyproject.toml
8.10.0 is the latest Agent we have successfully deployed without significantly slowing our pod startup times.  This is to test and see if the code changes between 8.10.0 and 8.11.0 is the culprit.
https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/313
Deploy to staging, and watch the api pod come to live and verify if it takes < 60seconds or > 90seconds
None.
=> New Relic Agent 8.11 Test

app/celery/scheduled_tasks.py, mypy.ini, poetry.lock, pyproject.toml, run_celery.py
Implementing Xray Tracing for Celery Pods (Scheduled Tasks Specifically)
Verify in Xray that the Celery Pods are tracing
None.
=> Celery xray

app/celery/celery.py, app/celery/scheduled_tasks.py
Rearranging some code for better organization and potentially better efficiency.
None.
=> Moving xray code to a more centralized location

app/celery/scheduled_tasks.py
Removing problematic xray/celery code :'(
None.
=> Xray celery rollback

poetry.lock, pyproject.toml
Bumping utils version to resolve some dependabot security vulnerabilities. Tested locally with API and Admin both running the latest utils version.
* https://github.com/cds-snc/notification-api/security/dependabot/164
* https://github.com/cds-snc/notification-utils/pull/298
* https://github.com/cds-snc/notification-admin/pull/1847
Tests pass
None.
=> Bump utils version

app/models.py, app/schemas.py, tests/app/dao/test_services_dao.py, tests/app/service/test_rest.py
We are not currently storing the reply_to_email_addresses which is a field on the Service model, to show up when we retrieve the Service from the cache. This meant that the reply_to_address was empty for the end user which is incorrect
Two parts:
1. The service gets added to the cache when the admin gets loaded - we needed to change the model Schema so we send the reply_to_email_addresses to the admin
2. We need to change the model to_json, so we might appropriately set the reply_to_email_addresses as a ServiceReplytoEmail model
[ ] Set the reply_to_email_address
[ ] Stay on the main branch: Send an email using the csv method  - it will send an email WITHOUT the reply-to set
[ ] Switch to this branch: Send an email using the csv method - it will send an email WITH the reply-to set …
=> We want to save the reply_to_email_addresses in the cache

app/dao/services_dao.py, app/models.py, app/service/rest.py, migrations/versions/0459_add_sensitive.py, tests/app/dao/test_services_dao.py, tests/app/db.py, tests/app/service/test_rest.py
Currently, Admin has a flag in the application where self._sensitive_services has all the IDs of sensitive services (which is pulled from config). We need to change this as this list is getting to large for config size limits.
This PR:
1. Adds a new field called sensitive_service in the services table
2. Adds an API to get all the sensitive services ids - this will be passed on to admin
* https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1635
*
> ⚠ If boxes cannot be checked off before merging the PR, they should be moved to the "Release Instructions" section with appropriate steps required to verify before release. For example, changes to celery code may require tests on staging to verify that performance has not been …
=> Add sensitive services

app/celery/celery.py
To be extra safe, we want to disable x-ray at the moment for Celery so it does not ship yet. Because it outputs Celery errors and it could trigger some alarms.
* https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/400
* Check if there are any Celery log output related to X-Ray.
None.
=> Disable x-ray by removing signals registration

app/celery/celery.py
The X-RAY integration with the Celery stack produces errors around missing X-Ray segment/sub-segments. This PR hopefully fixes these. This has not been tested locally. We can test in the dev environment first to have a full integrated environment (for X-Ray enabled and working) with no impact on the development pipeline.
The analysis of the Celery logs reveals that the segment and subsegment only impacts the [Celery periodic tasks](https://docs.celeryq.dev/en/stable/userguide/periodic-tasks.html):
```
[2024-08-20 19:45:39,836: INFO/MainProcess] xray-celery: **before publish: sender: beat-inbox-email-bulk headers**: {'lang': 'py', 'task': 'beat-inbox-email-bulk', 'id': '25421edd-3981-4a0f-a571-6f093224d18a', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, …
```
=> Wire the beat tasks signals with X-Ray

app/celery/celery.py, app/config.py, application.py, run_celery.py
Adding logic to rely upon an environment variable to turn Xray Tracing on or off
- Update the .env file on staging from true to false (or vice versa) on staging
- Deploy the app on staging
- Verify the Xray tracing/maps to see if it's on or off depending on configuration
Verify the config value in the production .env file to ensure it's what we want it to be.
=> Adding Config switch for Xray

app/celery/celery.py, app/config.py, application.py, run_celery.py
just a code tweak to handle our xray config env variable as a boolean rather than a string
nothing... everything should work the same as before
None.
=> updating code to use booleans rather than 'true''false'

app/celery/celery.py
Log beat signals for xray integration testing, no impact and to investigate the Celery / xray integration errors we currently have.
No testing required.
None.
=> Log beat signals for xray integration testing

app/celery/celery.py
Reverts cds-snc/notification-api#2263
The signals don't like the lambdas, so we will revert this and use good old fashioned functions.
=> Revert "Log beat signals for xray integration testing"

app/aws/xray_celery_handlers.py, app/celery/celery.py
Added back logging signals for beat workers
* https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/400
No testing. 
None.
=> Added back logging signals for beat workers

app/celery/celery.py, app/config.py, application.py, run_celery.py
Changing code to rely on the AWS_XRAY_SDK_ENABLED flag built into XRay SDK to toggle scanning off/on rather than our custom flag.
When toggled off or on in the .env files it should be reflected in the Xray scanning/maps
None.
=> removing references to the old configs for xray

app/aws/xray_celery_handlers.py, app/celery/celery.py
There is a possible situation when a Celery periodic task starts itself and has no segment in the current thread context. This will lead to errors as a subsegment will be created without a parent segment, which is required.
We can opt to skip the subsegment creation as this would normally be applied in a context of a parent task that would call down the current task. If there is no current segment, skip the creation of the subsegment and let the prerun signal handler to create the segment later down the road.
The same applies on closing the subsegment on the `after_task_publish` signal, i.e. check if a current subsegment exists before closing and if not, log a warning along with the task details to know on which one that happened, which should be a periodic tasks.
Also, I added missing …
=> Skip subsegment creation if segment is missing in current thread context

app/celery/tasks.py, tests/app/celery/test_tasks.py
Get the full service object when sending in batches so that reply-to's can be resolved and used.
- Setup a service with a reply to address
- Send a bulk message, ensure reply-to is present on received emails
None.
=> Get service reply-to's when sending in batch

app/aws/xray/context.py, application.py, run_celery.py
Adding custom context to add a warning level log for X-Ray messages.
Configuring the `AWS_XRAY_CONTEXT_MISSING` environment variable or via the recorder's constructor and setting it to `LOG_WARNING` will log the missing context as warning instead of an error. An error is deemed a bit too drastic as this could trigger a few of our alarms and we do not consider these non-stopping errors as worth of constant monitoring.
* https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/400
Set the different values to the `AWS_XRAY_CONTEXT_MISSING` environment variable and check the logs to see how errors of missing context behaves.
None.
> ⚠ If boxes cannot be checked off before merging the PR, they should be moved to the "Release …
=> Adding custom context to add a warning level log for X-Ray messages

app/schemas.py
Add sensitive_service to the schema so it might be returned to the frontend. 
* https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1635
1. Go to this branch, and use the equivalent branch on the frontend https://github.com/cds-snc/notification-admin/pull/1931
2. When you check redis for a service, you should have a service.sensitive_service (assuming the service is set)
=> add sensitive service to the schema

application.py, run_celery.py
Simply renaming the xray SDK service name (across the API, Admin and Celery Code) to Notify to see if traffic will be traced through the stack.
- After API and Admin are both deployed to staging, check the Xray maps and see if they are linked as the same service
=> Rename xray service to Notify

application.py
https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-python-patching.html
Adding a simple library reference and line of code to patch our libraries to enable full stack tracing through Admin -> API
> Check the Xray section after it's been merged to staging and verify if the map shows the nodes as being connected
=> Adding Patching for AWS Xray (API)

application.py
Lookig to differentiate between the api and admin for Xray simply
none
None.
=> Xray Service Name change

app/dao/service_callback_api_dao.py, app/models.py, app/service/callback_rest.py, tests/app/dao/test_service_callback_api_dao.py, tests/app/service/test_callback_rest.py
We want an API that will set the suspension to false for a given callback
* https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1648
You can test it with the admin PR 
None.
=> Add api to suspend a callback

app/dao/service_callback_api_dao.py, app/notifications/callbacks.py, tests/app/db.py, tests/app/notifications/test_callbacks.py
This PR adds a check to ensure we do not create callback tasks in Celery if a service's callback api is currently suspended.
Tests pass
1. Configure a service with a [callback url](https://beeceptor.com/)
2. Send a notification and note the callback is delivered
3. In the service settings, suspend the service's callbacks
4. Send a notification and note the callback is not delivered
=> Only queue callback tasks when a service's callback API is not suspended

app/aws/xray_celery_handlers.py
Cloudwatch was logging errors for celery:
`logger.warn(\n  File \"/usr/local/lib/python3.10/logging/__init__.py\", line 1494, in warn\n    self.warning(msg, *args, **kwargs)\n  File \"/usr/local/lib/python3.10/logging/__init__.py\", line 1489, in warning\n    self._log(WARNING, msg, args, **kwargs)\nTypeError: Logger._log() got an unexpected keyword argument 'headers'","stream":"stderr","time":"2024-09-04T17:58:48.904435306Z"}`
This was related to a minor string formatting error in our code.
Once deployed to Staging, check here to see if the celery errors have stopped being logged:
[Here](https://ca-central-1.console.aws.amazon.com/cloudwatch/home?region=ca-centr …
=> Code Fix for Xray Errors in Celery

app/config.py, app/delivery/send_to_providers.py
`sleep` for a bit to simulate the [production average latency of the AWS send_sms network call](https://ca-central-1.console.aws.amazon.com/cloudwatch/home?region=ca-central-1#metricsV2?graph=~(metrics~(~(~'NotificationCanadaCa~'production_notifications_celery_clients_pinpoint_request-time~'metric_type~'timing~(id~'m1)))~view~'timeSeries~stacked~false~region~'ca-central-1~stat~'Average~period~300~title~'p90*20Pinpoint*20request*20time*20in*20ms~start~'-PT3H~end~'P0D)) when we're sending to the `INTERNAL_TEST_NUMBER` (which does not perform the real network call).
* https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/396
- send to yourself. You should not see the sleep logging line
- send to 16135550123. You should …
=> add boto call latency for sending to internal sms number

app/user/rest.py
Fix the template link as we were sending https:// twice
=> Freshdesk: fix template link

app/dao/date_util.py, tests/app/dao/test_date_utils.py
This PR adds a utility function that will compute the date value to use when query notifications based on retention date.
* https://github.com/cds-snc/notification-planning/issues/1651
None.
=> Add date utility for retention queries

app/celery/reporting_tasks.py, app/dao/fact_notification_status_dao.py, tests/app/dao/test_fact_notification_status_dao.py
When we are updating the facts notification table, we don't want to delete all the data for the day, instead we only want to delete the data for the service_ids we are updating. This updates the function so we might do that.
None.
> ⚠ If boxes cannot be checked off before merging the PR, they should be moved to the "Release Instructions" section with appropriate steps required to verify before release. For example, changes to celery code may require tests on staging to verify that performance …
=> Fix the update for facts notifications

app/config.py
_TODO: 1-3 sentence description of the changed you're proposing._
None.
=> Set job to just 30 min past midnight est

app/dao/fact_notification_status_dao.py, tests/app/dao/test_fact_notification_status_dao.py
- We want query the facts table for 6 days prev to the current day
- We want to query notifications for todays data. due to timezones/ and when the job runs to populate facts, we will take the max existing date in facts from the last 6 days and use that as a starting point to query notifications for
- We added a filter for notification_type as there is a part in the frontend that fetches this query only for a singular notification type
* https://github.com/cds-snc/notification-planning/issues/1651
Updated and added unit tests
=> Update the fetch for notifications to take the correct datetimes into account

app/dao/jobs_dao.py, tests/app/dao/test_jobs_dao.py, tests/app/job/test_rest.py
This PR updates the date used in `dao_get_jobs_by_service_id` as part of the [Dashboard Errors epic](https://github.com/cds-snc/notification-planning/issues/1651).
* https://github.com/cds-snc/notification-planning/issues/1651
None.
=> Update date in `dao_get_jobs_by_service_id`

app/dao/notifications_dao.py
This PR updates `delete_notifications_older_than_retention_by_type` to use common date method in `date_utils`, `get_query_date_based_on_retention_period` which should help to make things consistent across the dashboard.
* https://github.com/cds-snc/notification-planning/issues/1651
None.
=> Refactor `delete_notifications_older_than_retention_by_type`

app/clients/sms/aws_pinpoint.py, app/delivery/send_to_providers.py, tests/app/clients/test_aws_pinpoint.py, tests/app/delivery/test_send_to_providers.py
Instead of faking a boto call for SMS to our `INTERNAL_TEST_NUMBER` we can do a real boto call with the parameter `DryRun` set to `True`. This should give us better timing estimates and still not cost anything (Dryrun does not actually send the message or charge us).
* https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/426
Send to +16135550123. See in the logs `Dry run enabled for SMS to +16135550123`...
None.
=> Use dryrun for sms to INTERNAL_TEST_NUMBER

app/delivery/send_to_providers.py
Broke the smoke test in #2320 because we stopped sending a delivery receipt for SMS to `INTERNAL_TEST_NUMBER`.
Here we add it back in.
* https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/426
Verify in staging that the smoke test works (ie SMS to 16135550123 are marked "delivered")
None.
=> fix/send delivery receipt for INTERNAL_TEST sms

.github/workflows/docker-vulnerability-scan.yml, .github/workflows/docker.yaml, .github/workflows/lambda_production.yml
Update the Docker scan actions to use a self-hosted Trivy vulnerability database. This is being done to address the rate limiting of the publicly hosted database.
- https://github.com/cds-snc/platform-core-services/issues/597
=> fix: use CDS Trivy vulnerability database

ci/Dockerfile.lambda
We depend on `libexecinfo-dev` which was removed in Alpine 3.17. This change pulls `libexecinfo-dev` in from the 3.16 Alpine repo so we can still utilize it.
* [Action failure](https://github.com/cds-snc/notification-api/actions/runs/11487080226/job/31970816800)
Run `docker build --no-cache -f ci/Dockerfile.lambda -t your-image-name:tag .` locally and ensure the Dockerfile builds.
None.
=> Pull libexecinfo-dev from alpine 3.16 repo

app/models.py
The origination id can be a long string so we relax the constraint on it. We also make the notifications and history table have the same length constraints.
* https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/438
Send SMS. Look at the new fields in the database
None.
=> tweak length constraints for new sms fields

migrations/versions/0467_add_annual_limits_data.py
Add a table to store data on usage for annual limits per service. This will be used to send a quarterly email to all service owners about their usage.
* https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1681
Ran flask upgrade locally and you will see the new table
```
notification_api=# \d annual_limits_data
Table "public.annual_limits_data"
Column       |       Type        | Collation | Nullable | Default 
--------------------+-------------------+-----------+----------+---------
service_id         | uuid              |           | not null | 
time_period        | character varying |           | not null | 
annual_email_limit | bigint            |           | not null | 
annual_sms_limit   | bigint            |           | …
```
=> Add a table to store annual_limits data

.github/workflows/test.yaml, app/__init__.py, app/aws/mocks.py, app/celery/process_pinpoint_receipts_tasks.py, app/celery/process_ses_receipts_tasks.py, app/celery/process_sns_receipts_tasks.py, poetry.lock, pyproject.toml, tests/app/celery/test_process_pinpoint_receipts_tasks.py, tests/app/celery/test_process_ses_receipts_tasks.py, tests/app/celery/test_process_sns_receipts_tasks.py
This PR hooks into the `ses`, `sns`, and `pinpoint` receipt processing tasks to increment counts, in Redis, of delivered and failed notifications for a service. 
* https://github.com/cds-snc/notification-utils/pull/330
* https://github.com/cds-snc/ADR/pull/14
Since we cannot receive AWS receipts locally testing needs to be done in staging post-merge. We can use the [simulator email addresses](https://docs.aws.amazon.com/ses/latest/dg/send-an-email-from-console.html) and [simulator phone numbers](https://docs.aws.amazon.com/sms-voice/latest/userguide/test-phone-numbers.html) from AWS for testing.
Send a successful email to `success@simulator.amazonses.com`
Send an email that fails to: `bounce@simulator.amazonses.com`
Send an email that fails to: `suppressionlist@simulator.amazonses.com` …
=> Track delivered & failed notification counts

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/docker-compose.yml
Create a custom docker network for all vscode containers to communicate between each others.
None
Once you have admin related PR merged and ready, from the terminal, try to ping the admin container:
```
$ ping notify-admin            
PING notify-admin (172.21.0.5) 56(84) bytes of data.
64 bytes from notification-admin_devcontainer-notify-admin-1.notify-network (172.21.0.5): icmp_seq=1 ttl=64 time=0.061 ms
64 bytes from notification-admin_devcontainer-notify-admin-1.notify-network (172.21.0.5): icmp_seq=2 ttl=64 time=0.066 ms
64 bytes from notification-admin_devcontainer-notify-admin-1.notify-network (172.21.0.5): icmp_seq=3 ttl=64 time=0.057 ms
```
None.
> ⚠ If boxes cannot be checked off before merging the PR, they should be moved to the "Release Instructions" section with appropriate …
=> Create a custom docker network for the devcontainers

.devcontainer/devcontainer.json
This PR adds Dependi to the API devcontainer, described as:
> ... the ultimate extension for seamless and efficient dependency management in Visual Studio Code (VSCode). Originally launched as Crates in 2018, our journey began by catering to the needs of Rust developers. Today, Dependi.io stands as a rebranded and expanded powerhouse, now supporting Go, JavaScript, and Python, alongside Rust.
- Rebuild dev container
- ensure extension installs
None.
=> chore: add dependi to devcontainer

.github/workflows/docker.yaml
This will modify the build and push github workflow to auto-generate the VPN config rather than relying on 1password. This way when we make changes to the VPN, we don't have to make changes to any other repositories.
chore
Verify that docker build/push works upon merge to main
None.
=> Automatically generate the VPN config instead of reading from 1pass

.github/workflows/test.yaml, poetry.lock, pyproject.toml
This PR incorporates bug fixes to the annual limit redis client.
* https://github.com/cds-snc/notification-utils/pull/335
None.
=> Bump utils for annual limit client fixes

.github/workflows/test.yaml, poetry.lock, pyproject.toml
Reverts cds-snc/notification-api#2352. We ran into a few issues with the Redis pipeline when clearing annual limit notification counts and re-seeding data and need to investigate further.
=> Revert "Bump utils for annual limit client fixes"

gunicorn_config.py
Increasing the gunicorn graceful timeout at 35 seconds and hard timeout at 40 seconds. The previous config of 25g/30h was not high enough for NewRelic increased load.
* https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/313
Watch k8s pods restart in staging env.
None.
=> Increasing the gunicorn graceful timeout at 40s

gunicorn_config.py
Increasing gunicorn timeout to 45s graceful / 50s hard. Previous values did not work with the increased New Relic initialization time. 
* https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/313
None.
=> Increasing gunicorn timeout to 45s graceful / 50s hard

gunicorn_config.py
…n timeout for staging env
Increasing gunicorn timeout to 85s graceful / 90s hard. Previous values did not work with the increased New Relic initialization time.
* https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/313
None.
=> Increasing gunicorn timeout to 85s graceful / 90s hard

newrelic.ini, poetry.lock, pyproject.toml
This version of New Relic includes performance improvements around package metadata discovery [which made New Relic slower in version 8.10.1](https://github.com/newrelic/newrelic-python-agent/issues/927):
* [Release notes](https://docs.newrelic.com/docs/release-notes/agent-release-notes/python-release-notes/python-agent-90102/)
* [Code fix](https://github.com/newrelic/newrelic-python-agent/pull/970)
BUT... we can also altogether disable the package discovery process via the `package_reporting.enabled` New Relic property that this PR sets in the *newrelic.ini* file. 
* [Issue](https://github.com/newrelic/newrelic-python-agent/issues/918)
* [Code fix](https://github.com/newrelic/newrelic-python-agent/pull/982)
* https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/ …
=> Upgraded to New Relic v9.2.0

newrelic.ini
In version 9.1.0 of NewRelic Python agent, there were improvements done on the package reporting. I want to test it out in staging to see if we can keep this feature or should just disable it. 
* https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/313
Trigger restart of kubernetes API deployment and monitor timing + potential loop crash. At this time, this is the config for probes that work for the API and with New Relic reporting disabled:
```
livenessProbe:
failureThreshold: 3
httpGet:
path: /_status?simple=true
port: 6011
scheme: HTTP
initialDelaySeconds: 30
periodSeconds: 3
successThreshold: 1
timeoutSeconds: 1
name: api
ports:
- containerPort: 6011
protocol: TCP
readinessProbe:
failureThreshold: 10
httpGet: …
```
=> Enable NewRelic package reporting to monitor perf improvements

app/celery/reporting_tasks.py, app/config.py, app/dao/annual_limits_data_dao.py, app/dao/users_dao.py, app/user/rest.py, tests/app/celery/test_reporting_tasks.py, tests/app/dao/test_annual_limits_data_dao.py, tests/app/dao/test_users_dao.py
Completed and merged in this PR: https://github.com/cds-snc/notification-api/pull/2345
1. Funcs to take notification counts per service, per quarter and store it in the annual_limits_data table
2. Funcs to decide what quarter we should be finding data for depending on today's current date.
In this PR:
1. Jobs to insert the data into the facts table. This job runs on the first day of every quarter (other than April 1)
2. Func to get all active services for all active users (user_id, lof(service_ids))
3. Func to find cumulative data about a service from annual_limits_data table
4. Celery task that will send an email with the cumulative data to each user_id, for all their services
Run this branch locally and open up a python REPL. This assumes you have a service with a lot of messages sent …
=> Func to find service annual stats and send an email

gunicorn_config.py, newrelic.ini, poetry.lock, pyproject.toml, run_celery.py
1. Upgraded NewRelic to v10.3.0 
2. Disable package reporting for all environments. We get dependency vulnerability detection with renovate and New Relic adds initialization boot up time with that feature, so this is not beneficial for us. 
* https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/458
Monitor deployment in the staging environment and make sure this is not going in a crash loop with the kubernetes pods. 
Monitor deployment in the staging environment and make sure this is not going in a crash loop with the kubernetes pods. 
> ⚠ If boxes cannot be checked off before merging the PR, they should be moved to the "Release Instructions" section with appropriate steps required to verify before release. For …
=> Upgraded NewRelic to v10.3.0 

.github/workflows/build_and_push_performance_test.yml, .github/workflows/docker-vulnerability-scan.yml, .github/workflows/docker.yaml, .github/workflows/lambda_production.yml, .github/workflows/lambda_staging.yml
GHA Secrets configured to reflect TF changes
* https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/299
Once the TF secrets PR has been merged, verify that the workflows all still work.
None.
=> normalizing secrets

.github/workflows/build_and_push_performance_test.yml, .github/workflows/docker-vulnerability-scan.yml, .github/workflows/docker.yaml, .github/workflows/lambda_production.yml, .github/workflows/lambda_staging.yml
Second take on switching to the github managed api secrets. I resolved the original issue where this was not working due to missing secrets.
* https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/299
Verify all workflows still work
None.
=> Api gh secrets

scripts/run_celery_delivery.sh
Add a new run_celery script to use for a new delivery-receipts deployment of celery pods.
* https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/473
none really, this doesn't work locally...
None.
=> Add a new run_celery script for delivery receipts

app/notifications/validators.py, tests/app/notifications/test_validators.py
Add the annual email limit sending in this PR
* https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1666
None.
=> Limit emails

app/service/rest.py, tests/app/service/test_rest.py
When the annual limits are changed, send a message to the service owners.
* https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1701
Run locally and check if the email comes
=> Added email message for change in annual limits

app/notifications/validators.py, app/service/rest.py, app/v2/notifications/post_notifications.py, tests/app/notifications/test_validators.py, tests/app/service/test_rest.py, tests/app/v2/notifications/test_post_notifications.py
This PR fixes several issues surrounding annual limit validation and warning email sending.
- Warning and reached email sent keys will now be properly deleted from Redis when a service's annual limits are changed
- `check_email_annual_limit` now calls `annual_limit_client.set_over_email_limit()` instead of `set_over_sms_limit()`
- `check_sms_annual_limit` now calls `set_nearing_sms_limit()` instead of `set_nearing_email_limit()` and no longer sends a `nearing_email_limit` email when a `nearing_sms_limit` email should be sent
- The annual limit error message should now take precedence over the daily limit error when posting a bulk job via the API. 
* …
=> Fix several annual limit bugs:

app/celery/tasks.py, tests/app/celery/test_tasks.py
This PR adds `FF_ANNUAL_LIMIT` checks to `__sending_limits_for_job_exceeded`, ensuring that if the FF is off then jobs that would otherwise go over the annual limit are not prevented from sending.
1. Create a new service
2. Set to live
3. Set annual email limit to 4
4. Set daily email limt to 5
5. Send bulk of 5
6. Not that bulk send works, annual limit ignored
None.
=> Add FF check to job sending limit validation

app/celery/tasks.py
This PR updates annual and daily limit validation that takes place before a job begins processing in the back end. 
- `__sending_limits_for_job_exceeded` should now properly check job size against a services annual limits
- Error logging when annual or daily limits would be exceeded now include: job size, daily/annual limits, total_sent_today / total_send_this_fiscal, and how far over the limit a service would be if the job were to be sent.
1. Send a job that would go over the annual limit  and one that would go over the daily limit
2. Check cloudwatch logs for the error logging
3. Send is prevented
None.
> ⚠ If boxes cannot be checked off before merging the PR, they should be moved to the "Release Instructions" section with appropriate steps required to verify before release. For …
=> Fix job sending limit validation

app/notifications/validators.py, app/service/rest.py, migrations/versions/0471_edit_limit_emails2.py
This PR updates the annual limit emails to:
- use the correct terms for notification types (emails/courriels and text messages/messages texte)
- use thousands separators in both french and english for long numbers
- properly link to the usage report page
- fix missing space in one of the templates
- Update your annual **SMS** limit
- Send more than 80% of your annual **SMS** limit
- Reach 100% of your annual **SMS** limit
-  Update your annual **email** limit
- Send more than 80% of your annual **email** limit
- Reach 100% of your annual **email** limit
None.
> ⚠ If boxes cannot be checked off before merging the PR, they should be moved to the "Release Instructions" section with appropriate steps required to verify before release. For example, changes to celery code may require tests on …
=> Update to the annual limits emails

app/celery/tasks.py, tests/app/celery/test_tasks.py
This PR removes duplicated message limit validation that was occurring when sending a job via the UI. At that point in the job process we are unable to (for the third time...) check the annual limits as notifications in that job will be counted in Redis already, causing jobs to fail to send if the service was near their annual limit.
None.
=> Removed duplicate message limit validation for jobs

bin/get_newrelic_layer.sh, ci/Dockerfile.lambda
Having issues with the official New Relic layers after 3.9 and alpine. Builds fine but cannot register with AWS Lambda.
Here we
- switch to the recommended Debian distribution (well, Debian-slim).
- download the official New Relic layer for 3.10 rather than using the one we made ourselves. (the download script has been changed to reflect this)
Surprisingly this debian based image is 20% smaller than the current alpine based image. 
We will test this in staging and if all is good we will revert it and see if the 3.12 upgrade works with Debian.
* https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/465
This has been built and deployed to dev and can be tested there.
- go to the [dev lambda …
=> Use official 3.10 New Relic later and Debian slim

app/clients/document_download.py, tests/app/clients/test_document_download.py
I spent a good couple hrs last week trying to figure out why document download was up but was returning 503's (service unavailable) when being called by api. Removing hard-coded 503 to return the actual http status code and also improving messaging.
Chore
Break document download and view the errors.
None.
=> Improving error reporting on document download

app/dao/fact_notification_status_dao.py
Add a try/except + rollback for the fact notifications job
=> Add try/except + rollback for fact notifications

app/service/rest.py, tests/app/service/test_statistics_rest.py
Reverts cds-snc/notification-api#2401
I believe this PR: https://github.com/cds-snc/notification-admin/pull/2029
will fix the issue that was being caused by sending the wrong year.
=> Revert "Task/fix stats"

app/celery/process_pinpoint_receipts_tasks.py, app/celery/process_ses_receipts_tasks.py, app/celery/process_sns_receipts_tasks.py, app/dao/date_util.py, app/dao/fact_notification_status_dao.py, app/service/rest.py
For this func:
1. We were taking today's UTC and converting it to midnight in a given timezone, we they were converting it back to UTC. 
2. We changed the callers and the actual function to fix this
https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1717
- Test things locally by setting up this PR on localhost
=> Remove date conversion

scripts/bootstrap.sh
This is a file that (as far as I know) is only used if you need to set up a new database from scratch.
Without the `poetry run` I was getting the error `command not found: flask`.
You could try running this locally.
=> Update `bootstrap.sh` so it works with `poetry`

poetry.lock, pyproject.toml
switch to utils tag 53.1.0 instead of branch
* https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/465
Test in staging. Verify annual limits in particular.
None.
=> use utils tag instead of branch

.github/actions/call-manifests-update-docker-tag.yaml, .github/workflows/call-manifests-update-docker-tag.yaml, .github/workflows/docker.yaml
Adding a workflow that runs on merge to main, calls a workflow in manifests to update the docker image tag in our manifests configuration files.
> watch that this runs on merge to main, and then check to see if the file has been updated in manifests here: 
https://github.com/cds-snc/notification-manifests/blob/main/helmfile/overrides/staging.env
https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/491
=> Updating Docker Image Tags for Helm Release Process

.github/workflows/docker.yaml, .github/workflows/test.yaml
updating an action because of this:
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
just check our tests on the repo to make sure they work
None.
=> updating upload artifact

.github/workflows/build_and_push_performance_test.yml, .github/workflows/docker.yaml, .github/workflows/lambda_production.yml, .github/workflows/lambda_staging.yml, .github/workflows/performance.yml, .github/workflows/test.yaml
Update the way the json is encoded when passed to a slack webhook in a github workflow.
* https://github.com/cds-snc/notification-planning/issues/1737
None.
=> Fix workflow json encoding

scripts/run_celery_receipts.sh
Copy `run_celery_delivery.sh` to a more appropriately named `run_celery_receipts.sh`.
We will delete the original `run_celery_delivery.sh` after we've changed the script used in the manifest repo.
=> copy script `run_celery_delivery.sh` to `run_celery_receipts.sh`

app/notifications/process_notifications.py, tests/app/notifications/test_process_notification.py
We are in an incident where updating the api key last_used is locking the database #1731 
None.
=> incident fix maybe

app/celery/tasks.py, app/notifications/process_notifications.py, tests/app/notifications/test_process_notification.py
_TODO: 1-3 sentence description of the changed you're proposing._
None.
=> Move last used from persist_notifications to process_job

app/config.py, app/service/utils.py
This PR switches where we are loading the gc-organisation data from to S3 to improve reliability.
* https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1151
Run locally with the following new line in your .env file:
```
GC_ORGANISATIONS_BUCKET_NAME=notification-canada-ca-staging-gc-organisations
```
Run the admin app and test creating a new service with an organisation from the dropdown list. You should be able to create the service successfully with no API errors.
None. The new env variable is already in staging and prod.
> ⚠ If boxes cannot be checked off before merging the PR, they should be moved to the "Release Instructions" section with appropriate steps required to verify before release. For example, changes to celery …
=> Get the gc-org data from s3

app/clients/freshdesk.py, tests/app/clients/test_freshdesk.py
This PR improves the formatting of the support emails for the "PT service skip Freshdesk" feature while still using the existing `_generate_ticket` method.
This PR removes the `product_id`, 'priority`, `status`, and `tags` data from the email. `priority` and `status` were being hardcoded in this case so those numbers weren't meaningful. `product_id` will always be the same for the prod app. And `tags` are only meaningful to freshdesk. So I think it is safe to remove this data for this feature since it makes the email less confusing for the support team. 
Here is an example:
Before:
After:
* https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1738
1. Set the following in your .env:
```
FF_PT_SERVICE_SKIP_FRESHDESK=true …
```
=> Improve the formatting of the support emails for PTs

app/celery/provider_tasks.py, app/clients/sms/aws_pinpoint.py, app/exceptions.py, tests/app/celery/test_provider_tasks.py, tests/app/clients/test_aws_pinpoint.py
If Pinpoint is throwing an error due to a ConflictError or ValidationError - we do not want to retry the notification. We will store the error so it might be propagated to the frontend in the future.
https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1760
=> Added error handling for pinpoint errors

app/data/gc-organisations-all.json, app/service/utils.py, tests/app/service/test_utils.py
This PR adds fallback gc-organisations data to the repo. I used this datafile: https://github.com/cds-snc/gc-organisations/blob/main/data/all.json
This will be used if we are unable to connect to S3 or if any other exception occurs while trying to fetch this data.
* https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1151
1. check out branch
2. remove `GC_ORGANISATIONS_BUCKET_NAME` from your .env file if you have it
3. run admin and api locally
4. verify that you can create a new service and that the organisations are showing up in the dropdown on step 3
None.
> ⚠ If boxes cannot be checked off before merging the PR, they should be moved to the "Release Instructions" section with appropriate steps required to verify before …
=> Add fallback data for gc-organisations to the repo

app/delivery/send_to_providers.py
The code path is:
`provider_tasks.py _deliver_sms`
->
`send_to_provider.py send_sms_to_provider`
->
`aws_pinpoint.py send_sms`
In this PR: https://github.com/cds-snc/notification-api/pull/2430
I wrongly assumed if I raise in the last step and catch the error in the first step, we should be okay.
After testing on staging: 
I found that after the Pinpoint error was raised, this func was raising an error:
```
"log": "  File \"/app/app/dao/provider_details_dao.py\", line 27, in get_provider_details_by_identifier",     "stream": "stderr",     "time": "2025-01-28T21:50:00.745570699Z" } | {"_p":"F","kubernetes":{"annotations":{"kubectl.kubernetes.io/restartedAt":"2025-01-22T11:02:19-05:00","kubernetes.io/config.seen":"2025-01-28T21:40:11.970146584Z","kubernetes.io/config.source":"api"},"container …
```
=> catch and reraise pinpoint errors

migrations/versions/0473_change_pt_support_email.py
This update has already been performed manually on templates in Staging and Prod. I'm just making the migration script so that we have the correct content if we ever need to recreate an environment from scratch.
- Check out the branch locally and run `poetry run flask db upgrade`
- visit [this template](http://localhost:6012/services/d6aa2c68-a2d9-4437-ab19-3ae8eb202553/templates/4bf8c15b-7393-463f-b6fe-e3fd1e99a03d) verify that your local copy looks like this:
None.
=> Update PT support email template

app/celery/process_ses_receipts_tasks.py
Getting errors in prd that a notification can't be found when it goes into 
```
_check_and_queue_complaint_callback_task(*handle_complaint(ses_message))
```
Changing this so that this might be caught in an error handler
Will test on staging
=> Change how the exception handling will work

app/v2/notifications/post_notifications.py, tests/app/v2/notifications/test_post_notifications.py
This PR adds the rate limit check to the `v2/notifications/bulk` endpoint.
When `check_rate_limiting` is called, it calls [`exceeded_rate_limit`](https://github.com/cds-snc/notification-utils/blob/main/notifications_utils/clients/redis/redis_client.py#L136-L182) in utils. This adds the current timestamp to the redis sorted set that tracks api calls, and checks if the 1000/minute rate has been exceeded.
* https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1757
Reproduce the bug
1. check out `main` and run the api locally
2. open pgadmin and change the rate limit for one of your services in the `services` table from `1000` to `10`
3. send 12 api requests to the `v2/notifications/email` endpoint in less than 1 minute
4. observe …
=> Add the rate limit check to the bulk endpoint

.dockerignore
I think the reason the new Python 3.12 perf tests weren't even running was because we stopped copying the `tests-perf` directory into the image.
* https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/521
See if they run!
None.
=> perf test image needs tests-perf directory

app/config.py
* Turnoff Freshdesk in all environments except production
By default, freshdesk should be off in all environments except production. 
* None
Trigger freshdesk tickets in each environment.
None.
=> Turnoff Freshdesk in all environments except production

tests-perf/locust/locust-notifications.py
The [template](https://staging.notification.cdssandbox.xyz/services/44c1a3f5-6a11-4952-b6f4-94dd46d009f2/templates/9fb324a5-821d-4b54-9d52-d9ba1fa8373a) we're using to send file links in the perf test has a `((var))` but our perf test code uses `application_file`. We could change the template, but other code could be using it. Safer to change the perf test.
* https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/521
Perf tests should run with no errors (after we get the annual limits issue fixed)
None.
> ⚠ If boxes cannot be checked off before merging the PR, they should be moved to the "Release Instructions" section with appropriate steps required to verify before release. For example, changes to celery code may …
=> fix perf test link sending

bin/execute_and_publish_performance_test.sh
Perf test uses a flat directory of days, this gets really long fast (currently GitHub will not list the full directory). Here we store results in a month / day structure.
Also fixed a bunch of things vscode was complaining about, for example putting quotes around directory name variables.
* https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/521
After tests run, check that s3 and Github has the new files in the correct directory structure
None.
> ⚠ If boxes cannot be checked off before merging the PR, they should be moved to the "Release Instructions" section with appropriate steps required to verify before release. For example, changes to celery code may require tests on staging to verify that performance has not …
=> put perf test results in a month directory

.github/workflows/build_and_push_performance_test.yml, bin/execute_and_publish_performance_test.sh, tests-perf/locust/send_rate_sms.py
Add a test to the nightly perf test that will max out our SMS sending rate
* https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/485
Look at the results of the perf test [here](https://ca-central-1.console.aws.amazon.com/cloudwatch/home?region=ca-central-1#dashboards/dashboard/Notify-System-Overview-SJA-internal-test-SMS).
None.
=> add sms send rate perf test

app/config.py
Both the queue name and the variable it is assigned to only appear in this file.
=> Remove unused celery queue

app/config.py, scripts/run_celery.ps1, scripts/run_celery.sh, scripts/run_celery_core_tasks.sh, scripts/run_celery_local.sh, scripts/run_celery_no_sms_sending.sh, tests/app/test_config.py
This does not appear to be used anywhere - it looks like we are now using:
`-priority-database-tasks.fifo`, `-normal-database-tasks`, `-bulk-database-tasks`
Find in project: `QueueNames.DATABASE` turns up nothing
Find in project: `database-tasks` turns up nothing, only matches of other queue names
Find in project: `DATABASE` turns up nothing, only matches of other variable names
Find in project in notification-terraform does turn up some matches for `database-tasks`:
https://github.com/cds-snc/notification-terraform/blob/main/env/production_config.tfvars#L152
https://github.com/cds-snc/notification-terraform/blob/main/aws/common/cloudwatch_alarms.tf#L100
So it looks like we still have some alarms defined on for this task that could be removed as well.
=> Remove unused database-tasks queue

.github/workflows/build_and_push_performance_test.yml
In #2449 I didn't realize there's a filter down in the middle of the file :/
* https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/485
🤞 
None.
=> add file to perf test GitHub action filter

.devcontainer/devcontainer.json, app/annotations.py, app/aws/xray_celery_handlers.py, app/encryption.py, app/queue.py, pyproject.toml, tests/app/test_annotations.py, tests/app/test_encryption.py
Added utility annotations `@unsign_params` and `@sign_return`.
The `@unsign_params` will inspect the decorated function for parameters with the `SignedNotification` and `SignedNotifications` types. When it finds these, it will attempt to run the `CryptoSigner.verify` method and replace the original parameter's value with the newly unsigned value, for the decorated function to receive the unsigned value. This removes the burden to handle this operation which happens often in the code base in a cross-cut manner. The `SignedNotification` type is meant to handle atomic value whereas the `SignedNotifications` is meant for list of `SignedNotifications` (alias `str` type). 
This annotation is not used in any place at the moment. This PR is meant to only introduce the utility. Next PRs will …
=> Added annotations to auto-manage the sign/unsign input parameters and return

app/dao/api_key_dao.py
I re-wrote the query in this function to be more performant (hopefully). Using update() directly should be more efficient than the previous query. I tested locally to make sure the `last_used_timestamp` is still being set correctly.
I'd like to see what effect this has on the DB load during our nightly performance tests.
* https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1769
Run locally and verify that the api key `last_used_timestamp` gets updated when you send a notification via the local api. You can see it in admin on the following page: API Integration > API Keys
None.
> ⚠ If boxes cannot be checked off before merging the PR, they should be moved to the "Release Instructions" section with appropriate steps required to …
=> Improve performance of `update_last_used_api_key` fn

.devcontainer/scripts/notify-dev-entrypoint.sh, Makefile, tests_smoke/smoke_test.py
Tweak the smoke test so `smoke-dev` runs but omits things dev currently can't do (sending files and admin csv upload)
- set up a .`env_smoke_dev` in the repo root dir
- run `smoke-dev`
- see emails and sms send successfully!
None.
=> tweak smoke test for dev

tests_nightly_performance/execute_and_publish_performance_test.sh
Post perf test start and end to slack
* https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/544
Requires https://github.com/cds-snc/notification-terraform/pull/1793
None
None.
=> post perf test start and end to slack

tests_nightly_performance/Dockerfile
Forgot to install curl in the perf test container 🤦 
* https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/544
[Tested](https://gcdigital.slack.com/archives/C012W5K734Y/p1741208429992409) by pushing an image with just the curls
None.
=> Fix perf test start / end Slack post

tests_nightly_performance/locust.conf, tests_nightly_performance/src/blast_api.py, tests_nightly_performance/src/common.py, tests_nightly_performance/src/email_send_rate.py, tests_nightly_performance/src/sms_send_rate.py
There's a variable to set the host but we're not using it, just hard coding to staging :/
* https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/484
Tested on dev
None.
=> get perf test host from variable

.devcontainer/scripts/notify-dev-entrypoint.sh, poetry.lock
This fixes the issue where locally, celery was not able to send emails. Here is what I did:
```
git checkout 278bbd48 poetry.lock
poetry lock --no-update
poetry install
```
Check this branch out locally, run poetry install, verifiy that you are able to send emails.
None.
=> Revert `poetry.lock` file to 278bbd48

app/models.py, migrations/versions/0476_add_reports_table.py, tests/app/notifications/rest/test_send_notification.py, tests_nightly_performance/src/blast_api.py, tests_nightly_performance/src/email_send_rate.py, tests_nightly_performance/src/sms_send_rate.py
This PR adds a new table to capture metadata for reports, to support the new async reports feature.
Note: there are a few random formatting changes that Ruff is forcing me to do
Here is a design where some of the data from this table will be used: https://www.figma.com/design/rzjRLTIzVjM4sHpzI6e0Xl/Reports-%2F-Rapports?node-id=35-1228&t=EaEFXy9k4CMRdvus-4
The lifecycle of a report will be roughly this:
1. user clicks a button to "generate" a report
2. a row is added to the `reports` table with status `"requested"`
3. a celery task picks up the requested report, changes the status to `"generating"` and starts to create the CSV file in an S3 bucket
4. once finished, the status is changed to `"ready"`
5. the report is shown as available to download in notification-admin
6. after 3 days, we …
=> Add a new DB table: `reports`

app/__init__.py, app/dao/reports_dao.py, app/models.py, app/report/rest.py, tests/app/dao/test_reports_dao.py, tests/app/report/test_rest.py
This PR adds:
- a new report endpoint that notification-admin can use to add reports that are requested by users
- a new dao function that adds new reports to the `reports` table
- a `serialize` method on the `Reports` model that we can use to return report data from the new endpoint
- unit tests for the endpoint and dao functions
* https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1805
- verify the code looks good, tests pass
=> Add a new endpoint `create_service_report`

app/report/rest.py, app/schemas.py
Add marshmallow schema validation for `reports`
* https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1805
Tests should pass.
None.
=> Add schema validation for `reports`

app/models.py, app/report/rest.py, app/schemas.py, migrations/versions/0478_add_report_language.py, tests/app/celery/test_scheduled_tasks.py, tests/app/conftest.py, tests/app/dao/test_reports_dao.py, tests/app/report/test_rest.py
Add a `language` column to the reports table and update the following:
- update `create_service_report` endpoint to add the language
- update tests
- add a migration file
* https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1807
1. check this branch out and run locally
2. run `flask db upgrade`
3. verify that you have the new `language` column in your `reports` table
None.
=> Add `language` column to the `reports` table

app/models.py, migrations/versions/0479_update_reports_url.py
Increase the `report` `url` column length to 2000 chars
We are seeing the following error on staging:
```
2025-04-08T15:36:00.822500406Z stderr F [2025-04-08 15:36:00,820: ERROR/ForkPoolWorker-4] Task generate-
report[0a605206-12fb-4197-81c6-cf81ffcae8da] raised unexpected: 
DataError('(psycopg2.errors.StringDataRightTruncation) value too long for type character varying(800)\n')
```
There isn't an official maximum url length in the AWS docs, and it is possible for the pre-signed url to be more than 1000 chars: [stack overflow](https://stackoverflow.com/questions/70975517/aws-s3-signed-url-length-max#:~:text=There%20is%20no%20official%20limit,S3%20object%20of%201669%20characters.)
The unofficial character limit for a url is 2000 characters, so that seems like a safe limit to use here.
1. …
=> Increase the `report` `url` column length to 2000 chars

app/celery/scheduled_tasks.py, app/config.py, app/report/rest.py, tests/app/celery/test_scheduled_tasks.py, tests/app/report/test_rest.py
This PR simplifies the way reports are generated in celery. Instead of running a scheduled task every minute to get new reports, just add a `generate_reports` async task directly from the endpoint whenever a new report is requested. This speeds up processing time and removes the db call to find new reports that happens every minute. 
* https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1807
1. run this branch locally
2. generate a report
3. verify that it is created successfully and you can download it
> ⚠ If boxes cannot be checked off before merging the PR, they should be moved to the "Release Instructions" section with appropriate steps required to verify before release. For example, changes to celery code may require …
=> Call `generate-report` from the reports endpoint

app/aws/s3.py, app/celery/tasks.py, app/report/utils.py, tests/app/aws/test_s3.py, tests/app/celery/test_tasks.py, tests/app/report/test_utils.py
This PR:
- uses the "copy" feature in postgresql https://www.postgresql.org/docs/current/sql-copy.html 
- reduces memory usage in the celery worker by streaming the csv data to s3, rather than trying to store the whole csv file in memory
- adds tests for this
I'd like to test this on staging with our perf test service to see how it does with a large file.
- check out the branch locally
- generate a report
- verify that the report looks correct
=> Switch to using postgres `copy` and stream csv data to s3

scripts/run_celery_local.sh, scripts/run_celery_report_tasks.sh
Add a script to set up a new celery queue, that will run on its own pod
* https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1845
None, we just need a script to run this so that a celery pod can be set up. Once merged we will switch generate reports to this queue
None.
=> Add a celery worker for reports

app/aws/s3.py, app/celery/tasks.py, app/report/rest.py, app/report/utils.py, app/schemas.py, tests/app/aws/test_s3.py, tests/app/report/test_rest.py, tests/app/report/test_utils.py
This PR:
- adds the language to the report creation endpoint so that it will be stored in the db
- adds logic to translate the headers in the "Delivery report"
- removes unused code and tests that are not needed now that we are doing translation as part of the postgres "copy" command
- add some unit tests
I will translate the values as a follow up PR
* https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1846
1. check out this branch
2. run locally with admin `main`
3. switch your language to french in admin and generate a report
4. download the report and open it
5. observe that the headers in the report are in french 
> ⚠ If boxes cannot be checked off before merging the PR, they should be moved to the "Release Instructions" …
=> Translate the Delivery report headers

app/report/utils.py
Make the job report consistent with the existing feature:
- remove the "sent by" and "sent by email" column
- add the row number
- sort by row number
Before:
After:
1. check out this branch and run with admin `main`
2. send a csv job via admin (or use an existing job for one of your services)
3. click "prepare report"
4. download the report and verify that it matches what you see in the screenshot above
=> Make the job report consistent with the existing feature

app/celery/process_ses_receipts_tasks.py
The quotes were wrong in one of the logs - which would cause an exception if hit.
I also removed a duplicate log.
=> Fix a bug with `process_ses_receipts_tasks` logging

.github/workflows/test.yaml, app/annual_limit_utils.py, app/celery/process_ses_receipts_tasks.py, poetry.lock, pyproject.toml, tests/app/celery/test_process_ses_receipts_tasks.py
When testing the annual limits code, there are times when the seeded_at key for notifications_v2 is set, but the data for the other mappings is not set. We changed the function to check if the seeded_at exists, then the mappings MUST exist (even if they are zero) - else we reseed the data. 
None.
=> Fix mapping by adding a double check

app/annual_limit_utils.py, app/celery/process_pinpoint_receipts_tasks.py, app/celery/process_sns_receipts_tasks.py, tests/app/celery/test_process_pinpoint_receipts_tasks.py, tests/app/celery/test_process_ses_receipts_tasks.py, tests/app/celery/test_process_sns_receipts_tasks.py
This PR applies the same [changes made to process_ses_receipts](https://github.com/cds-snc/notification-api/pull/2527) to fix annual limit seeding issue.
* https://github.com/cds-snc/notification-api/pull/2527
CI passes
Verify in staging tomorrow post-perf test that the seeding occurred correctly.
None.
=> Fix annual limit seeding in pinpoint and sns receipt tasks

app/dao/services_dao.py, tests/app/dao/test_services_dao.py
We were getting this error in production where we are adding a user to a service, and the user has already been added to the service. Previously we caught the error in app/service/rest.py but between checking for the user in the service, and trying to add the user again - we believe there is a race condition (by another process accessing an adding a user to the same service).
Trying to formulate why this might happen:
Why the UniqueViolation Error Still Occurs
The error is still occurring because of a race condition in the database operations. Potential sequence:
1. The error happens because of how SQLAlchemy handles sessions and transactions:
1. You check if the user is in [service.users](which is a Python-side check)
1. If not, you proceed with [dao_add_user_to_service()]
1. But before …
=> Add code to test for an user being added to a service they are already in

.github/CODEOWNERS
Added CODEOWNERS file with db changes stakeholders, i.e. Pat, Bryan W. and Jumana B. This came up in a discussion within the team where we need to communicate the database changes so that our data consumers can react accordingly. We should notify via more traditional means (Slack, emails, in person?) but this should be a catch all so nothing should escape their attention. 
No specific task. Quick change for delivering quick notifications on database changes.
Open new PR on database migration and users should get a notification from github with their preferred notif methods.
None.
> ⚠ If boxes cannot be checked off before merging the PR, they should be moved to the "Release Instructions" section with appropriate steps required to verify before release. For example, changes to celery code …
=> Added CODEOWNERS file with db changes stakeholders

.github/workflows/test.yaml, poetry.lock, pyproject.toml
Bump to notify utils 53.2.3
* https://github.com/cds-snc/notification-planning/issues/1917
None.
=> chore: bump utils

.github/CODEOWNERS, app/dao/jobs_dao.py, app/job/rest.py, tests/app/dao/test_jobs_dao.py, tests/app/job/test_rest.py
Add a new dedicated `/has_jobs` endpoint that does an efficient query to check this. Admin was previous getting all the jobs data for a given service to make this check.
* https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1919
Same test as over here: https://github.com/cds-snc/notification-admin/pull/2187
=> Add a dedicated `/has_jobs` endpoint that is more efficient

app/aws/mocks.py, app/celery/process_ses_receipts_tasks.py, app/dao/notifications_dao.py, app/notifications/notifications_ses_callback.py, tests/app/celery/test_process_ses_receipts_tasks.py, tests/app/celery/test_process_sns_receipts_tasks.py, tests/app/notifications/test_notifications_ses_callback.py
Reverts cds-snc/notification-api#2537
- Added [missing receipt payload attributes](https://github.com/cds-snc/notification-api/pull/2538/commits/4757496fd069b82decbac3d793c3947c85eb547a) to our typed receipt classes, mitigating the potential for data loss when marshalling the raw receipt JSON into the typed data structures.
- Fixed a [typing issue](https://github.com/cds-snc/notification-api/pull/2538/commits/7f484f2bbd355863dd180fba4935158905b70403#diff-6da9ce98a04287a9303a293329834f04247e54bccb8ab2483969918bdc0b5ecbR147) that caused crashes during complaint receipt handling if the receipt did not contain a list of complainedRecipients
- [Refactored how we handle complaints when it's associated notification is not yet in the DB](https://github.com/cds-snc/notification-api/pull/2538/commit …
=> Revert "Revert "Batch save ses receipts""

app/cypress/rest.py
Update the cypress cleanup function to exclude the cypress templates explicitly.
- After a few hours the scheduled test runs will fail if this didnt work
None.
=> Ensure testing templates don't get removed up during cleanup

app/models.py, migrations/versions/0483_index_jobs.py
Every time we call `dao_get_jobs_by_service_id` (which the dashboard does at every load) we are doing a full table scan on the jobs table. This is because we are filtering on `created_at` which is not indexed. Adding an index for this and `processing_started` (which we are ordering by) should improve the dashboard load time for services with a lot of jobs.
* https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1953
1. check out branch
2. run `flask db upgrade`
3. verify that you are on the new alembic version and that the new indexes have been added to the jobs table
> ⚠ If boxes cannot be checked off before merging the PR, they should be moved to the "Release Instructions" section with appropriate steps required to verify …
=> Add 2 new indexes to the `jobs` table

app/dao/jobs_dao.py, tests/app/dao/test_jobs_dao.py, tests/app/job/test_rest.py
Sort null values of `processing_started` last
Tests should pass.
=> Sort null values of `processing_started` last

app/v2/api_spec/get_api_spec.py, application.py
This PR corrects an issue where the `wsgi` lambda handler was assuming and treating the `application/yaml` content type as binary content and applying base64 encoding on the response body. 
1. Run this curl command `curl --location 'https://api.dev.notification.cdssandbox.xyz/v2/openapi-en'` to fetch the spec from dev where this code is currently running
2. Note that the spec is properly returned as yaml instead of a base64 encoded string
None.
=> Exclude application/yaml from binary content types

openapi/v2-notifications-api-en.yaml, openapi/v2-notifications-api-fr.yaml
- /v2/notifications/email
- /v2/notifications/sms
- /v2/notifications/{notification-id}
- Added many examples payloads
- Added all error codes and descriptions / examples
Copy and past the yaml file into https://editor.swagger.io/ to view it.
None.
=> Add static spec mapping for various endpoint

app/__init__.py
Having localhost as an origin for CORS could be a potential security issue, so here it is removed.  The result is that we won't be able to use the "try it out" feature of Swagger locally.  We can still use it in the review environment, dev, staging, and prod, so this isn't really a big deal.
* https://github.com/cds-snc/notification-planning/issues/1933
- Ensure `localhost:8081` is not returned as a CORS origin when making an options request to the API at `/v2/notifications`
None.
=> Remove localhost from allowed CORS origins

openapi/v2-notifications-api-en.yaml, openapi/v2-notifications-api-fr.yaml
This PR updates the open api spec  files with examples for the /v2/bulk endpoint as well as fixing the format example for the api key so it includes the `ApiKey-v1` prefix
None.
=> Add examples for /v2/bulk

scripts/run_celery.ps1, scripts/run_celery.sh
Adding `generate-reports` queues to the run scripts cause some issues in staging.
* https://gcdigital.slack.com/archives/C012W5K734Y/p1750955925213049
CI is passing
None.
=> Remove generate-reports from queue run args

app/models.py, migrations/versions/0487_revert_security_key_auth.py
Reverts changes from cds-snc/notification-api#2589
We decided against only allowing a specific key for login. Instead we will continue to allow you to log in using any of your currently existing security keys.
=> Drop fido2_key_id from users table

app/user/rest.py, tests/app/user/test_rest_verify.py
This PR helps to simplify E2E testing by enabling the test account to authenticate with any verification code. 
See also, a similar PR that allowed verifying phone numbers for e2e tests: https://github.com/cds-snc/notification-api/pull/2585
✅ Production Safety: does not occur in production environments
✅ Domain Protection: Blocked on any notification.canada.ca domains
✅ Environment Isolation: Only active in development mode
✅ User checks: Only active for users with a specific email address pattern
- Test cases covering all environment and host combinations
- Negative tests confirming shortcut not possible in production
> ⚠ If boxes cannot be checked off before merging the PR, they should be moved to the "Release Instructions" section with appropriate steps required to verify before …
=> Allow  test accounts to login with any code

migrations/versions/0488_update_2fa_templates.py
Redo the 2fa template migration but do not use the `process_type` column. 
The `process_type` column was null in prod - we don't need to copy this over to the template history table.
* https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/2196
=> Redo the 2fa template migration but do not use the `process_type` column

newrelic.ini
Disabling New Relic via the newrelic.ini file
We need a PR to trigger an API lambda deployment, so here it is.
None
Make sure in New Relic that no new data consumption is present. Also check the lambdas environment variables.
None.
=> Disabling New Relic via the newrelic.ini file

application.py, ci/Dockerfile.lambda
Disable New Relic completely for the lambda:
* Disabled the New Relic lambda handler override.
* Target the lambda handler directly to GCNotify one.
* Disable New Relic initialization on application's startup. It should still activate in Kubernetes pods because these go through gunicorn..
Incident channel #incident-2025-08-21-500s-on-admin
Deploy in staging first and make sure lambda runs properly without New Relic enabled.
None.
=> Disabling New Relic completely for the AWS lambda.

ci/Dockerfile.lambda
Remove new relic from the build to help with incident where we are executing too many lambdas
#incident-2025-08-21-500s-on-admin
=> Remove newrelic from lambda

ci/Dockerfile.lambda
Fixed the typo with the lambda handler, which tried to refer to the GCNotify lambda handler instead of the New Relic wrapper.
Incident #incident-2025-08-21-500s-on-admin
Try it in staging, make sure lambda boots good in Lambda AWS console and check for errors in the lambda log group!
None.
=> Fixed typo in lambda handler

ci/Dockerfile.lambda
Testing if the NR layer can work without triggering lambda timeout issue. We fixed the issue in production but we want to pinpoint the actual fix and how we can work out a better code maintenance strategy.
Incident #incident-2025-08-21-500s-on-admin
Deploy in staging environment and look if lambda timeout issue triggers again.
None.
=> Testing if the NR layer can work without triggering lambda timeout issue

bin/entry.sh
outputting some useful logging info for env variables to the entry.sh script
=> Logging env vars in Entry.sh

tests_cypress/package-lock.json, tests_cypress/package.json
Fixes: [Dependabot issue 263](https://github.com/cds-snc/notification-api/security/dependabot/263)
1. Cypress still runs
None.
=> Pin transitive dep `form-data` to >=4.0.4

bin/sync_lambda_envs.sh
Adjusting Lambda Sync Script to load ALL param store variables rather than just the ones that aren't already preloaded in the lambda static config.  
None.
=> Adjusting Lambda Sync Script to load ALL param store variables

.github/workflows/lambda_staging.yml, ci/Dockerfile.newrelic.lambda
Creating separate docker file for NR that will build conditionally if it's enabled, and if not it builds the regular docker file for lambda
None.
=> New Relic Discrete Docker File

ci/Dockerfile.newrelic.lambda
Looks to be hopefully the culprit as we were removing the extension files with the other ones
=> Fixing extension files

application.py, ci/Dockerfile.newrelic.lambda
Replacing NR Zip with NR Docker Layer -- also removing a few lines of code that were in the app because it's handled by the included layer in the docker file now.
=> Replacing NR Zip with NR Docker Layer

application.py, bin/entry.sh, bin/get_newrelic_layer.sh, ci/Dockerfile.lambda, ci/Dockerfile.newrelic.lambda, poetry.lock, pyproject.toml
Replacing NR Zip with NR Docker Layer -- also removing a few lines of code that were in the app because it's handled by the included layer in the docker file now.
Adjusting where NR gets initialized (moving to cold start) because we don't want the lambda to show up as piles and piles of lambda functions in NR
=> New Relic Cold Start Initialization/APM Variables and Handler
